-- Migration 069: 匯入打卡點「開放資訊(access_note)」，供玩家判斷開放時段/可否前往
-- 來源 xlsx 開放性備註（已去除內部『V2 GPS建議…』設定文字）。
ALTER TABLE explore_bosses ADD COLUMN IF NOT EXISTS access_note TEXT NOT NULL DEFAULT '';

UPDATE explore_bosses SET access_note='全天候公園；實際活動管制需確認' WHERE code='DOR-TPE-001';
UPDATE explore_bosses SET access_note='活動日可能管制；需確認公告' WHERE code='DOR-TPE-002';
UPDATE explore_bosses SET access_note='校園場地；開放狀態需確認' WHERE code='DOR-TPE-003';
UPDATE explore_bosses SET access_note='河濱開放；橋下空間施工或活動需確認' WHERE code='DOR-TPE-004';
UPDATE explore_bosses SET access_note='河濱開放；賽事日管制' WHERE code='DOR-TPE-005';
UPDATE explore_bosses SET access_note='河濱開放；橋面人流需注意' WHERE code='DOR-TPE-006';
UPDATE explore_bosses SET access_note='河濱開放；假日人潮多' WHERE code='DOR-TPE-007';
UPDATE explore_bosses SET access_note='河濱開放；活動日需確認' WHERE code='DOR-TPE-008';
UPDATE explore_bosses SET access_note='河濱開放；假日遊客多' WHERE code='DOR-TPE-009';
UPDATE explore_bosses SET access_note='公園開放；部分設施需確認' WHERE code='DOR-TPE-010';
UPDATE explore_bosses SET access_note='公園開放；環湖人流需注意' WHERE code='DOR-TPE-011';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TPE-012';
UPDATE explore_bosses SET access_note='河濱開放；夜間照明需確認' WHERE code='DOR-TPE-013';
UPDATE explore_bosses SET access_note='公園開放；環湖人流需注意' WHERE code='DOR-TPE-014';
UPDATE explore_bosses SET access_note='公園開放；假日人流較多' WHERE code='DOR-TPE-015';
UPDATE explore_bosses SET access_note='公園開放；部分設施需確認' WHERE code='DOR-TPE-016';
UPDATE explore_bosses SET access_note='河濱開放；雨後河道需注意' WHERE code='DOR-TPE-017';
UPDATE explore_bosses SET access_note='公園開放；展覽日人潮多' WHERE code='DOR-TPE-018';
UPDATE explore_bosses SET access_note='公園開放；大型活動日需確認' WHERE code='DOR-NTP-001';
UPDATE explore_bosses SET access_note='場館開放依公告與賽事安排' WHERE code='DOR-NTP-002';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-NTP-003';
UPDATE explore_bosses SET access_note='場館開放依公告與賽事安排' WHERE code='DOR-NTP-004';
UPDATE explore_bosses SET access_note='河濱開放；強風與夜間照明需注意' WHERE code='DOR-NTP-005';
UPDATE explore_bosses SET access_note='河濱開放；假日自行車多' WHERE code='DOR-NTP-006';
UPDATE explore_bosses SET access_note='公園開放；設施使用需確認' WHERE code='DOR-NTP-007';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-NTP-008';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-NTP-009';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-NTP-010';
UPDATE explore_bosses SET access_note='河濱開放；假日人潮多' WHERE code='DOR-NTP-011';
UPDATE explore_bosses SET access_note='水岸開放；遊客人潮多' WHERE code='DOR-NTP-012';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-NTP-013';
UPDATE explore_bosses SET access_note='河濱開放；夜間照明需確認' WHERE code='DOR-NTP-014';
UPDATE explore_bosses SET access_note='河濱開放；風大時需注意' WHERE code='DOR-NTP-015';
UPDATE explore_bosses SET access_note='河濱開放；路段辨識需現地確認' WHERE code='DOR-NTP-016';
UPDATE explore_bosses SET access_note='公園開放；天候變化較大' WHERE code='DOR-NTP-017';
UPDATE explore_bosses SET access_note='山徑開放狀態需確認' WHERE code='DOR-NTP-018';
UPDATE explore_bosses SET access_note='河濱開放；遊客多' WHERE code='DOR-NTP-019';
UPDATE explore_bosses SET access_note='水岸開放；假日人潮多' WHERE code='DOR-NTP-020';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-KEE-001';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-KEE-002';
UPDATE explore_bosses SET access_note='海岸開放；強風與浪況需注意' WHERE code='DOR-KEE-003';
UPDATE explore_bosses SET access_note='假日人潮多；路線需注意車流' WHERE code='DOR-KEE-004';
UPDATE explore_bosses SET access_note='河濱開放；夜間照明需確認' WHERE code='DOR-KEE-005';
UPDATE explore_bosses SET access_note='公園開放；階梯與坡道需留意' WHERE code='DOR-KEE-006';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-TAO-001';
UPDATE explore_bosses SET access_note='公園開放；設施使用需確認' WHERE code='DOR-TAO-002';
UPDATE explore_bosses SET access_note='公園開放；周邊施工需注意' WHERE code='DOR-TAO-003';
UPDATE explore_bosses SET access_note='公園開放；山路天候需注意' WHERE code='DOR-TAO-004';
UPDATE explore_bosses SET access_note='公共空間開放；活動日人潮多' WHERE code='DOR-TAO-005';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TAO-006';
UPDATE explore_bosses SET access_note='河濱開放；假日人潮多' WHERE code='DOR-TAO-007';
UPDATE explore_bosses SET access_note='公園開放；環湖人潮需注意' WHERE code='DOR-TAO-008';
UPDATE explore_bosses SET access_note='山路開放狀態需確認' WHERE code='DOR-TAO-009';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TAO-010';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TAO-011';
UPDATE explore_bosses SET access_note='開放空間；風勢與補給需注意' WHERE code='DOR-TAO-012';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-HSZ-001';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-HSQ-001';
UPDATE explore_bosses SET access_note='山徑開放；雨後濕滑' WHERE code='DOR-HSZ-002';
UPDATE explore_bosses SET access_note='河濱開放；強風需注意' WHERE code='DOR-HSQ-002';
UPDATE explore_bosses SET access_note='步道開放；假日人潮多' WHERE code='DOR-HSZ-003';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-HSQ-003';
UPDATE explore_bosses SET access_note='道路與步道狀態需確認' WHERE code='DOR-HSQ-004';
UPDATE explore_bosses SET access_note='風勢強；部分路段需注意' WHERE code='DOR-HSQ-005';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-HSQ-006';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-HSZ-004';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-HSZ-005';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-MIA-001';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-MIA-002';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-MIA-003';
UPDATE explore_bosses SET access_note='河濱開放；夜間照明需確認' WHERE code='DOR-MIA-004';
UPDATE explore_bosses SET access_note='路線開放；季節人潮多' WHERE code='DOR-MIA-005';
UPDATE explore_bosses SET access_note='街道路線需注意車流' WHERE code='DOR-MIA-006';
UPDATE explore_bosses SET access_note='風勢強；補給需自行規劃' WHERE code='DOR-MIA-007';
UPDATE explore_bosses SET access_note='風勢與路況需現地確認' WHERE code='DOR-MIA-008';
UPDATE explore_bosses SET access_note='公園開放；活動日管制' WHERE code='DOR-TXG-001';
UPDATE explore_bosses SET access_note='公園開放；部分路段坡度明顯' WHERE code='DOR-TXG-002';
UPDATE explore_bosses SET access_note='校園／場館開放狀態需確認' WHERE code='DOR-TXG-003';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-TXG-004';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-TXG-005';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-TXG-006';
UPDATE explore_bosses SET access_note='綠道開放；自行車多' WHERE code='DOR-TXG-007';
UPDATE explore_bosses SET access_note='河岸開放；路口與車流需注意' WHERE code='DOR-TXG-008';
UPDATE explore_bosses SET access_note='山徑開放狀態需確認' WHERE code='DOR-TXG-009';
UPDATE explore_bosses SET access_note='公園開放；路況需確認' WHERE code='DOR-TXG-010';
UPDATE explore_bosses SET access_note='公園開放；假日人潮多' WHERE code='DOR-TXG-011';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TXG-012';
UPDATE explore_bosses SET access_note='園區開放時間需確認' WHERE code='DOR-TXG-013';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-CHA-001';
UPDATE explore_bosses SET access_note='開放空間；階梯與坡道需注意' WHERE code='DOR-CHA-002';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-CHA-003';
UPDATE explore_bosses SET access_note='公園開放；假日車流多' WHERE code='DOR-CHA-004';
UPDATE explore_bosses SET access_note='綠道開放；遊客與自行車多' WHERE code='DOR-CHA-005';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-CHA-006';
UPDATE explore_bosses SET access_note='路線需自行規劃；活動日管制' WHERE code='DOR-CHA-007';
UPDATE explore_bosses SET access_note='道路路線需注意車流' WHERE code='DOR-CHA-008';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-NAN-001';
UPDATE explore_bosses SET access_note='公共道路；路口與車流需注意' WHERE code='DOR-NAN-002';
UPDATE explore_bosses SET access_note='道路與山路狀態需確認' WHERE code='DOR-NAN-003';
UPDATE explore_bosses SET access_note='道路路線需注意車流與補給' WHERE code='DOR-NAN-004';
UPDATE explore_bosses SET access_note='開放狀態需確認' WHERE code='DOR-NAN-005';
UPDATE explore_bosses SET access_note='道路與遊客人潮需注意' WHERE code='DOR-NAN-006';
UPDATE explore_bosses SET access_note='道路路線；天候與車流需注意' WHERE code='DOR-NAN-007';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-NAN-008';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-YUN-001';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-YUN-002';
UPDATE explore_bosses SET access_note='公共空間；夜間照明需確認' WHERE code='DOR-YUN-003';
UPDATE explore_bosses SET access_note='河濱開放；假日人潮多' WHERE code='DOR-YUN-004';
UPDATE explore_bosses SET access_note='假日遊客多' WHERE code='DOR-YUN-005';
UPDATE explore_bosses SET access_note='公園開放；風勢需注意' WHERE code='DOR-YUN-006';
UPDATE explore_bosses SET access_note='道路與河堤需注意車流' WHERE code='DOR-YUN-007';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-YUN-008';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-CYI-001';
UPDATE explore_bosses SET access_note='公園開放；坡道需注意' WHERE code='DOR-CYI-002';
UPDATE explore_bosses SET access_note='道路路線；夜間照明需確認' WHERE code='DOR-CYI-003';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-CYI-004';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-CYQ-001';
UPDATE explore_bosses SET access_note='園區開放時間需確認' WHERE code='DOR-CYQ-002';
UPDATE explore_bosses SET access_note='綠道開放；補給需規劃' WHERE code='DOR-CYQ-003';
UPDATE explore_bosses SET access_note='園區開放時間與天候需確認' WHERE code='DOR-CYQ-004';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-CYQ-005';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-TNN-001';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-TNN-002';
UPDATE explore_bosses SET access_note='公園開放；假日人潮多' WHERE code='DOR-TNN-003';
UPDATE explore_bosses SET access_note='園區開放時間需確認' WHERE code='DOR-TNN-004';
UPDATE explore_bosses SET access_note='公園開放；人流需注意' WHERE code='DOR-TNN-005';
UPDATE explore_bosses SET access_note='水岸開放；假日人潮多' WHERE code='DOR-TNN-006';
UPDATE explore_bosses SET access_note='風勢與夜間安全需注意' WHERE code='DOR-TNN-007';
UPDATE explore_bosses SET access_note='路線與開放時間需確認' WHERE code='DOR-TNN-008';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-TNN-009';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-TNN-010';
UPDATE explore_bosses SET access_note='公共空間；夜間照明需確認' WHERE code='DOR-TNN-011';
UPDATE explore_bosses SET access_note='園區開放時間與收費需確認' WHERE code='DOR-TNN-012';
UPDATE explore_bosses SET access_note='公園開放；距離較短' WHERE code='DOR-TNN-013';
UPDATE explore_bosses SET access_note='公園開放；距離較短' WHERE code='DOR-TNN-014';
UPDATE explore_bosses SET access_note='場館周邊開放；主場館依公告' WHERE code='DOR-KHH-001';
UPDATE explore_bosses SET access_note='公園開放；假日人潮多' WHERE code='DOR-KHH-002';
UPDATE explore_bosses SET access_note='水岸開放；夜間人流多' WHERE code='DOR-KHH-003';
UPDATE explore_bosses SET access_note='公園開放；活動日人潮多' WHERE code='DOR-KHH-004';
UPDATE explore_bosses SET access_note='開放與收費規則需確認' WHERE code='DOR-KHH-005';
UPDATE explore_bosses SET access_note='水岸開放；假日人潮多' WHERE code='DOR-KHH-006';
UPDATE explore_bosses SET access_note='假日人潮多；路線需注意行人' WHERE code='DOR-KHH-007';
UPDATE explore_bosses SET access_note='商圈人流與車流需注意' WHERE code='DOR-KHH-008';
UPDATE explore_bosses SET access_note='校園與海岸路線開放需確認' WHERE code='DOR-KHH-009';
UPDATE explore_bosses SET access_note='山徑開放狀態與獼猴出沒需注意' WHERE code='DOR-KHH-010';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-KHH-011';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-KHH-012';
UPDATE explore_bosses SET access_note='道路與開放狀態需確認' WHERE code='DOR-KHH-013';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-KHH-014';
UPDATE explore_bosses SET access_note='園區開放時間需確認' WHERE code='DOR-KHH-015';
UPDATE explore_bosses SET access_note='公園開放；人流多' WHERE code='DOR-KHH-016';
UPDATE explore_bosses SET access_note='開放與天候狀態需確認' WHERE code='DOR-KHH-017';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-PIF-001';
UPDATE explore_bosses SET access_note='公園開放；人流需注意' WHERE code='DOR-PIF-002';
UPDATE explore_bosses SET access_note='河濱開放；風勢與夜間照明需確認' WHERE code='DOR-PIF-003';
UPDATE explore_bosses SET access_note='道路與園區開放狀態需確認' WHERE code='DOR-PIF-004';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-PIF-005';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-PIF-006';
UPDATE explore_bosses SET access_note='道路路線需注意車流' WHERE code='DOR-PIF-007';
UPDATE explore_bosses SET access_note='沙灘與道路狀態需確認' WHERE code='DOR-PIF-008';
UPDATE explore_bosses SET access_note='公園開放；場館依公告' WHERE code='DOR-ILA-001';
UPDATE explore_bosses SET access_note='公園開放；活動日管制' WHERE code='DOR-ILA-002';
UPDATE explore_bosses SET access_note='園區開放狀態需確認' WHERE code='DOR-ILA-003';
UPDATE explore_bosses SET access_note='河濱開放；雨後需注意' WHERE code='DOR-ILA-004';
UPDATE explore_bosses SET access_note='風勢與沙灘狀況需注意' WHERE code='DOR-ILA-005';
UPDATE explore_bosses SET access_note='山徑與園區開放需確認' WHERE code='DOR-ILA-006';
UPDATE explore_bosses SET access_note='公園開放；設施狀態需確認' WHERE code='DOR-ILA-007';
UPDATE explore_bosses SET access_note='道路與遊客人潮需注意' WHERE code='DOR-ILA-008';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-HUA-001';
UPDATE explore_bosses SET access_note='海岸開放；強風與浪況需注意' WHERE code='DOR-HUA-002';
UPDATE explore_bosses SET access_note='公園開放；雨後路面需注意' WHERE code='DOR-HUA-003';
UPDATE explore_bosses SET access_note='海岸開放；強風與落石告示需注意' WHERE code='DOR-HUA-004';
UPDATE explore_bosses SET access_note='園區開放；遊客與車流需注意' WHERE code='DOR-HUA-005';
UPDATE explore_bosses SET access_note='公園開放；活動日需確認' WHERE code='DOR-HUA-006';
UPDATE explore_bosses SET access_note='校園開放狀態需確認' WHERE code='DOR-HUA-007';
UPDATE explore_bosses SET access_note='道路路線需注意車流' WHERE code='DOR-HUA-008';
UPDATE explore_bosses SET access_note='開放與道路狀態需確認' WHERE code='DOR-HUA-009';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-TTT-001';
UPDATE explore_bosses SET access_note='園區開放時間與收費需確認' WHERE code='DOR-TTT-002';
UPDATE explore_bosses SET access_note='海岸開放；強風需注意' WHERE code='DOR-TTT-003';
UPDATE explore_bosses SET access_note='園區開放狀態需確認' WHERE code='DOR-TTT-004';
UPDATE explore_bosses SET access_note='人流多；慢跑需注意行人' WHERE code='DOR-TTT-005';
UPDATE explore_bosses SET access_note='道路與天候需確認' WHERE code='DOR-TTT-006';
UPDATE explore_bosses SET access_note='觀光人潮多；自行車與車流需注意' WHERE code='DOR-TTT-007';
UPDATE explore_bosses SET access_note='綠道開放；補給需規劃' WHERE code='DOR-TTT-008';
UPDATE explore_bosses SET access_note='海岸與道路狀態需確認' WHERE code='DOR-TTT-009';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-PEN-001';
UPDATE explore_bosses SET access_note='海岸開放；風勢需注意' WHERE code='DOR-PEN-002';
UPDATE explore_bosses SET access_note='沙灘狀況與潮汐需注意' WHERE code='DOR-PEN-003';
UPDATE explore_bosses SET access_note='橋上風大；交通安全需注意' WHERE code='DOR-PEN-004';
UPDATE explore_bosses SET access_note='行人與車流需注意' WHERE code='DOR-PEN-005';
UPDATE explore_bosses SET access_note='沙灘與潮汐需注意' WHERE code='DOR-PEN-006';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-KIN-001';
UPDATE explore_bosses SET access_note='道路與遊客人潮需注意' WHERE code='DOR-KIN-002';
UPDATE explore_bosses SET access_note='海岸與道路狀態需確認' WHERE code='DOR-KIN-003';
UPDATE explore_bosses SET access_note='道路與開放狀態需確認' WHERE code='DOR-KIN-004';
UPDATE explore_bosses SET access_note='遊客人潮與街巷安全需注意' WHERE code='DOR-KIN-005';
UPDATE explore_bosses SET access_note='橋區風大；交通安全需注意' WHERE code='DOR-KIN-006';
UPDATE explore_bosses SET access_note='場館開放依公告' WHERE code='DOR-LIE-001';
UPDATE explore_bosses SET access_note='港區動線需注意' WHERE code='DOR-LIE-002';
UPDATE explore_bosses SET access_note='潮汐與風勢需注意' WHERE code='DOR-LIE-003';
UPDATE explore_bosses SET access_note='交通與開放狀態需確認' WHERE code='DOR-LIE-004';
UPDATE explore_bosses SET access_note='風勢強；道路安全需注意' WHERE code='DOR-LIE-005';
UPDATE explore_bosses SET access_note='本校操場於101年四月完工，供學校師生與社區民眾使用' WHERE code='DOR-TRK-TPE-001';
UPDATE explore_bosses SET access_note='有田徑場、籃球場3座、排球場3座、網球場3座、高爾夫球場，可供運動之外亦可辦理活動及民眾休憩運動使用，並提供夜間照明' WHERE code='DOR-TRK-TPE-002';
UPDATE explore_bosses SET access_note='童遊戲設施，供全校師生使用，並於每日5點半至隔日上午7點對外開放，社區居民皆可到校使用' WHERE code='DOR-TRK-TPE-003';
UPDATE explore_bosses SET access_note='本校操場為200公尺跑道，有二面籃球場，平日晚上及假日供學生及民眾使用。(興建經費87年為1331112元，103年改建經費為3232879元)' WHERE code='DOR-TRK-TPE-004';
UPDATE explore_bosses SET access_note='地下1層設有游泳池；地下3樓是停車場；1樓設有櫃檯服務中心、社區教室、兒童遊戲室；2樓設有攀岩場、籃球場、桌球撞球場；3樓設有壁球場、健身中心、5樓設有舞蹈教室、羽、網球場，提供多元使用需求' WHERE code='DOR-TRK-TPE-005';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TPE-006';
UPDATE explore_bosses SET access_note='籃球場一面兼排球場一面，亦可進行瑜伽課程及有氧舞蹈課程，同時可供校內外各類運動競賽舉辦用' WHERE code='DOR-TRK-TPE-007';
UPDATE explore_bosses SET access_note='包含室外籃球場及室外排球場，於非假日的17:10-21:00開放民眾使用自由使用' WHERE code='DOR-TRK-TPE-008';
UPDATE explore_bosses SET access_note='本校田徑場為開放社區民眾使用空間，歡迎社區民眾多加利用' WHERE code='DOR-TRK-TPE-009';
UPDATE explore_bosses SET access_note='育大學田徑場於85年9月鋪設橡膠跑道，除提供教學外，平時早晚開放社區民眾使用' WHERE code='DOR-TRK-TPE-010';
UPDATE explore_bosses SET access_note='於80年10月完工自今共23年,提供學生體育課及校慶活動,並開放民眾傍晚活動使用' WHERE code='DOR-TRK-TPE-011';
UPDATE explore_bosses SET access_note='場為柏油地，另設有四面籃球架，供本校日間部、進修學校，及大安社區大學使用，本校已不敷使用，已無空間對外開放' WHERE code='DOR-TRK-TPE-012';
UPDATE explore_bosses SET access_note='本田徑場地可供一般民眾慢跑，中間為草地可供足球場地使用' WHERE code='DOR-TRK-TPE-013';
UPDATE explore_bosses SET access_note='本校運動場於上學時間除外，開放給社區民眾使用' WHERE code='DOR-TRK-TPE-014';
UPDATE explore_bosses SET access_note='本場地與社區活動用，並於學生放學後對外開放' WHERE code='DOR-TRK-NTP-001';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-NTP-002';
UPDATE explore_bosses SET access_note='到操場活動身體，非常便利，平日供本校師生使用，放學及假日時間開放給一般民眾使用，是一個運動休閒的好去處' WHERE code='DOR-TRK-NTP-003';
UPDATE explore_bosses SET access_note='本校田徑場為200公尺跑道，內場設有2面手球場、1面排球場，可供相關球類訓練，並可進行壘球、足球、籃球等戶外等多元活動使用' WHERE code='DOR-TRK-NTP-004';
UPDATE explore_bosses SET access_note='100年起免費對外開放,內含排球場,手球場' WHERE code='DOR-TRK-NTP-005';
UPDATE explore_bosses SET access_note='本場於本校設立之初即已興建，為鄰近居民主要運動地點，於民國100年整建完成，周邊另有兒童遊戲設施及木平台等休閒設施,本校兒童遊樂設施已於105.8.24完成更新及改扇，符合CNS12642「公共兒童遊戲場設備」要求' WHERE code='DOR-TRK-NTP-006';
UPDATE explore_bosses SET access_note='本館歡迎社區民眾來運動，興建於 民國79年，96年翻新過。 無' WHERE code='DOR-TRK-NTP-007';
UPDATE explore_bosses SET access_note='土城國中田徑場，免費對外場地租借，每天開放；土城國中校網亦列校園開放地點含田徑場' WHERE code='DOR-TRK-NTP-008';
UPDATE explore_bosses SET access_note='土城國小田徑場附設籃球場，每天開放' WHERE code='DOR-TRK-NTP-009';
UPDATE explore_bosses SET access_note='廣福國小田徑場，免費對外場地租借，開放時間內隨到隨用' WHERE code='DOR-TRK-NTP-010';
UPDATE explore_bosses SET access_note='新北高工田徑場，開放對象無限制，免費對外場地租借，每天開放，平假日16:00~23:00' WHERE code='DOR-TRK-NTP-011';
UPDATE explore_bosses SET access_note='清水高中田徑場，免費對外場地租借，每天開放' WHERE code='DOR-TRK-NTP-012';
UPDATE explore_bosses SET access_note='戶外操場供學生上課使用，平常上課期間，假日開放給附近民眾運動休閒 無' WHERE code='DOR-TRK-NTP-013';
UPDATE explore_bosses SET access_note='丹鳳高中田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-014';
UPDATE explore_bosses SET access_note='本田徑場整建於83年6月，主要提供學生體育教學使用，課後亦提供民眾運動' WHERE code='DOR-TRK-NTP-015';
UPDATE explore_bosses SET access_note='昌隆國小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-016';
UPDATE explore_bosses SET access_note='本校田徑場為露天場地，除供上課教學用之外，亦於課後時間開放社區民眾運動使用' WHERE code='DOR-TRK-NTP-017';
UPDATE explore_bosses SET access_note='頭前國中田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-018';
UPDATE explore_bosses SET access_note='頭前國中風雨操場，免費對外場地租借' WHERE code='DOR-TRK-NTP-019';
UPDATE explore_bosses SET access_note='中山國中田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-020';
UPDATE explore_bosses SET access_note='實踐國小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-021';
UPDATE explore_bosses SET access_note='江翠國中田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-022';
UPDATE explore_bosses SET access_note='有田徑場一座，周圍有籃球場2座，兒童遊戲設施2座，適合學生及居民從事休閒活動' WHERE code='DOR-TRK-NTP-023';
UPDATE explore_bosses SET access_note='社區運動公園場地設施有兒童遊戲設施、體健設施、直排輪溜冰場、壘球場、草地槌球空間等' WHERE code='DOR-TRK-NTP-024';
UPDATE explore_bosses SET access_note='17年7月舉辦世大運競賽活動，歡迎民眾前往觀賽。活動期間不提供民眾健身活動，欲從事相關運動民眾，請轉往其他場地，謝謝您' WHERE code='DOR-TRK-NTP-025';
UPDATE explore_bosses SET access_note='本場館興建於民國103年9月，屬於複合式運動場，可供籃球、排球、躲避球等運動使用' WHERE code='DOR-TRK-NTP-026';
UPDATE explore_bosses SET access_note='要為田徑場第，場邊有戶外健身器材，場內有籃球場1.5座。平日開放時間為0530-0700，1630-1900，假日為0530-1830' WHERE code='DOR-TRK-NTP-027';
UPDATE explore_bosses SET access_note='武林國小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-028';
UPDATE explore_bosses SET access_note='有七道，並有兩座躲避球場，主要作為上課及運動會使用，課後亦會開放民眾運動' WHERE code='DOR-TRK-NTP-029';
UPDATE explore_bosses SET access_note='平日學生上課及體育活動主要場所。 課後為民眾休閒活動場所' WHERE code='DOR-TRK-NTP-030';
UPDATE explore_bosses SET access_note='啟用，操場內有PU跑道、籃球架3個，提供給校內師生使用，並於開放時間提供民眾來學校運動。 無' WHERE code='DOR-TRK-NTP-031';
UPDATE explore_bosses SET access_note='火車站旁及汐止交流道附近。 周邊設有田徑場、足球場等，是汐止居民休閒活動的最佳場所' WHERE code='DOR-TRK-NTP-032';
UPDATE explore_bosses SET access_note='青山國中小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-033';
UPDATE explore_bosses SET access_note='等多所學校，並有辭修公園及多條登山休閒步道，是師生教學活動及居民平時休閒運動的最佳場所' WHERE code='DOR-TRK-NTP-034';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-NTP-035';
UPDATE explore_bosses SET access_note='400M標準跑道，場內可供棒壘球、跳高、跳遠、鉛球等運動使用' WHERE code='DOR-TRK-NTP-036';
UPDATE explore_bosses SET access_note='位於信賢里6鄰信福路40號「信賢基督長老教會」旁，附近有信賢市民活動中心、信賢衛生室及信賢森林種子實小，為居民平時休閒運動場所' WHERE code='DOR-TRK-NTP-037';
UPDATE explore_bosses SET access_note='烏來國中小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-038';
UPDATE explore_bosses SET access_note='烏來運動場，免費對外場地租借' WHERE code='DOR-TRK-NTP-039';
UPDATE explore_bosses SET access_note='來里環山路山地部落烏來基督長老教會旁，附近有數家溫泉會館，為居民平時休閒運動的場所' WHERE code='DOR-TRK-NTP-040';
UPDATE explore_bosses SET access_note='福山國小田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-041';
UPDATE explore_bosses SET access_note='民國96年,位於吉慶國小內,周邊有兒童遊戲設施,是本校學生及社區居民運動的場所' WHERE code='DOR-TRK-NTP-042';
UPDATE explore_bosses SET access_note='田徑場興建於民國99年，場地內設有兩面標準籃球場，供全校教職員工及學生與社區居民運動休閒之用' WHERE code='DOR-TRK-NTP-043';
UPDATE explore_bosses SET access_note='本校運動場餘52年間完工 平時供學生上課 假日可提供一般民眾使用 田徑場為主 籃球場為輔' WHERE code='DOR-TRK-NTP-044';
UPDATE explore_bosses SET access_note='瑞芳國小田徑場，免費對外場地租借；用校園座標近似' WHERE code='DOR-TRK-NTP-045';
UPDATE explore_bosses SET access_note='瑞芳高工田徑場，免費對外場地租借' WHERE code='DOR-TRK-NTP-046';
UPDATE explore_bosses SET access_note='長160公尺跑道內有籃球場，平日上課期間僅對校內教職員及學生開放，校園開放時段(放學後及假日)，歡迎社區民眾運動健身，但請愛惜公物' WHERE code='DOR-TRK-NTP-047';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-KEE-001';
UPDATE explore_bosses SET access_note='本田徑場為PU跑道，提供附近居民絕佳室外運動場地，但因基隆多雨潮濕，跑道嚴重破損，雖然已定期維修，但仍無法維持最佳狀態' WHERE code='DOR-TRK-KEE-002';
UPDATE explore_bosses SET access_note='成功國小操場在民國100年重新整修，提供學生與附近居民良好的運動、休閒場所' WHERE code='DOR-TRK-TAO-001';
UPDATE explore_bosses SET access_note='開放時間：每日06:00-07:00、18:00-20:00 (由前門進出) 假日08:00-18:00 (由前門進出) 場地租借費：全日5000元，半日3000元 水電費：300元 婚喪喜慶筵席與營利活動不' WHERE code='DOR-TRK-TAO-002';
UPDATE explore_bosses SET access_note='本校田徑場有6個跑道，一圈為200公尺，內有2座躲避球場，提供學生及社區居民運動的好場所' WHERE code='DOR-TRK-TAO-003';
UPDATE explore_bosses SET access_note='地劃有二面躲避球場及架設8個籃框 每日17：00-19：00開放民眾利用' WHERE code='DOR-TRK-TAO-004';
UPDATE explore_bosses SET access_note='(館)即位於口字形建築中央，於77年大規模硬體翻修，場地中央可供球類運動使用，周圍為PU跑道可供田徑使用' WHERE code='DOR-TRK-TAO-005';
UPDATE explore_bosses SET access_note='）興建於民國99年，位於內海國小內，周邊另有兒童遊戲設施等，供教學及民眾使用' WHERE code='DOR-TRK-TAO-006';
UPDATE explore_bosses SET access_note='興建於民國80年,為設有籃球場及躲避球場的綜合性場地,提供社區民眾與學生使用' WHERE code='DOR-TRK-TAO-007';
UPDATE explore_bosses SET access_note='場共用。 本校田徑場於上課期間僅對校內教職員及學生開放，其餘對外開放時間為：上午6：00-7：00；下午4：00-6：00，若舉辦活動，需租借場地，此部分請洽詢本校總務處。 PS.原籃球場及簡易棒球場因設置新場館而廢除' WHERE code='DOR-TRK-TAO-008';
UPDATE explore_bosses SET access_note='鎮美華國小校內 主要用途為美華國小學生上課使用並於課餘時間提供社區民眾運動使用' WHERE code='DOR-TRK-TAO-009';
UPDATE explore_bosses SET access_note='學生體育課程使用外,每日4:00放學後及清晨7:00以前時間開放社區民眾運動,每年並舉辦ㄧ次校內暨社區聯合運動會,未曾舉辦跨區或校際賽事.' WHERE code='DOR-TRK-TAO-010';
UPDATE explore_bosses SET access_note='及平日上午05:30-08:00及下午16:00-20:30開放民眾使用' WHERE code='DOR-TRK-TAO-011';
UPDATE explore_bosses SET access_note='本場興建於民國94年，提供學生上課及課後民眾休閒運動使用' WHERE code='DOR-TRK-TAO-012';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TAO-013';
UPDATE explore_bosses SET access_note='球架，跑道外有單槓、小跳遠場、盪鞦韆及小型的遊樂設施，是假日村民及外來遊客休閒運動的好所在，平日則為本校師生進行體育活動及各項重要集會的場所' WHERE code='DOR-TRK-TAO-014';
UPDATE explore_bosses SET access_note='場所，位於校園內，主要有田徑場、籃球場、足球場及躲避球場，提供校內師生及社區民眾使用' WHERE code='DOR-TRK-TAO-015';
UPDATE explore_bosses SET access_note='學校操場，可供居民跑步、打籃球等活動使用' WHERE code='DOR-TRK-TAO-016';
UPDATE explore_bosses SET access_note='三類活動場地類型。除了供上課教學使用之外，並於學校訂定之校園開放時間供社區民眾使用，以提供本校教職員生及社區民眾從事運動的適合場地' WHERE code='DOR-TRK-TAO-017';
UPDATE explore_bosses SET access_note='本運動場為PU跑道，一圈為200公尺，假日是社區民眾運動散步的好地方' WHERE code='DOR-TRK-TAO-018';
UPDATE explore_bosses SET access_note='本田徑場興建於民國88年，開放時間週一到週五16:00-18:00，週六週日8:00-18:00。 無' WHERE code='DOR-TRK-TAO-019';
UPDATE explore_bosses SET access_note='境消毒外全年無休。田徑場102年整修，並於103年2月份重新開放，提供民眾舒適及優質之運動環境' WHERE code='DOR-TRK-HSZ-001';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-HSZ-002';
UPDATE explore_bosses SET access_note='於校園內東側，跑道材質PU，平日以學生上課為主，放學及假日則開放社區民眾使用' WHERE code='DOR-TRK-HSZ-003';
UPDATE explore_bosses SET access_note='本操場興建於民國55年，平日時段以教學與校隊訓練為主，假日開放一般民眾使用' WHERE code='DOR-TRK-HSZ-004';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-HSZ-005';
UPDATE explore_bosses SET access_note='本運動場興建於民國85年，周邊有四面籃球場，中間草皮場地可供足球比賽，壘球場使用' WHERE code='DOR-TRK-HSZ-006';
UPDATE explore_bosses SET access_note='香山綜合運動場為開放式場地，全年無休，運動設施繁多，可從事各項球類及田徑運動、舞蹈教室，周邊尚有簡易兒童遊樂設施，是民眾從事各項運動以及各單位、公司行號舉辦活動的最佳場所' WHERE code='DOR-TRK-HSZ-007';
UPDATE explore_bosses SET access_note='本場興建於民國84年，位於寶山國中內，平時開放給民眾是用，場內有足球場設施' WHERE code='DOR-TRK-HSQ-001';
UPDATE explore_bosses SET access_note='含網)、排球場(不含網)、籃球場、網球場(不含網)、徑賽跑道可供人使用' WHERE code='DOR-TRK-HSQ-002';
UPDATE explore_bosses SET access_note='興村的交界處，運動公園內設有溜冰場、籃球場、槌球場設施，為一開放式公園，附近居住人口密集，提供居民平日及假日休憩場所，使用效率高' WHERE code='DOR-TRK-HSQ-003';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-HSQ-004';
UPDATE explore_bosses SET access_note='本(運動)公園於103年4月11日開放啟用，除環形跑道外，亦有槌球場及戶外體健設施、涼亭等供民眾休閒使用。並設有停車格供前來運動民眾停車' WHERE code='DOR-TRK-HSQ-005';
UPDATE explore_bosses SET access_note='2月，隔年8月整修，供學生體育課程與課外活動使用，非上課時間開放民眾進行運動活動' WHERE code='DOR-TRK-HSQ-006';
UPDATE explore_bosses SET access_note='座排球場及三座籃球場。 做為本校體育教學使用，假日、放學後提供社區民眾運動休閒場地' WHERE code='DOR-TRK-HSQ-007';
UPDATE explore_bosses SET access_note='本校校訓敬業樂群之意，共設有17間可媲美五星級的住宿空間，除供國內外貴賓使用，亦可提供本校觀光、餐飲等科系實習。三至六樓設有136間套房式學生宿舍可容床位數528床，可提供海外內學子優良住宿空間，整體宿舍採用節能、舒適、智慧管理方式。 李右婷校長說明學校積極轉型、希望提供在地需求的人才，因此本日餐敘的精緻點心由海青班學生製作，實習旅館則由觀光系導覽解說，伴手禮則由生活系自製環保天然的檸檬洗碗精，就連背版的設計到架設都由學生會架設，...' WHERE code='DOR-TRK-HSQ-008';
UPDATE explore_bosses SET access_note='本場地建於民國75年,為三義鄉民主要運動所在.' WHERE code='DOR-TRK-MIA-001';
UPDATE explore_bosses SET access_note='平日學校上課自用,社區民眾假日開放使用.' WHERE code='DOR-TRK-MIA-002';
UPDATE explore_bosses SET access_note='教學使用，場內另有棒球／籃球場地。本場於學生放學後及假日，可供民眾休閒健身使用' WHERE code='DOR-TRK-MIA-003';
UPDATE explore_bosses SET access_note='本場所改善於民國92年,供一般民眾及學生跑步使用.' WHERE code='DOR-TRK-MIA-004';
UPDATE explore_bosses SET access_note='5年，位於栗林國小內，平日為學生上課、遊戲之用，課後及假日則供給社區民眾及遊客使用，周邊另有兒童遊戲設施' WHERE code='DOR-TRK-MIA-005';
UPDATE explore_bosses SET access_note='繕，位於大湖鄉華興國小內，周邊另有兒童遊戲設施及連鎖磚空地，可供運動休憩。 場地上有三種運動項目畫線：籃球場、躲避球場、羽球場' WHERE code='DOR-TRK-MIA-006';
UPDATE explore_bosses SET access_note='本田徑場興建於民國92年，此場內包含籃球場、足球場，亦可供躲避球場使用，周邊另有兒童遊戲設施。 無' WHERE code='DOR-TRK-MIA-007';
UPDATE explore_bosses SET access_note='本田徑場(內含四面籃球架)提供一般民眾或團體從事各種有益身心健康之休閒活動及社教文化活動為原則' WHERE code='DOR-TRK-MIA-008';
UPDATE explore_bosses SET access_note='田徑場興建於民國89年，位於苗栗縣後龍國中，本活動中心主要提供本校教學及集會活動使用，也提供一般民眾於非教學時間使用。本田徑場為250公尺，並設有鉛球及跳遠場地' WHERE code='DOR-TRK-MIA-009';
UPDATE explore_bosses SET access_note='200公尺6道PP跑道、躲避球場2面。主要為教學、課間活動、社區居民運動用' WHERE code='DOR-TRK-MIA-010';
UPDATE explore_bosses SET access_note='日及傍晚也常有民眾到校運動，操場周圍並有兒童遊具及體能器具可供民眾與師生使用' WHERE code='DOR-TRK-MIA-011';
UPDATE explore_bosses SET access_note='或縣內活動都是最佳場所，可舉辦大型體育活動及大眾化活動，平時開放免費讓廣大民眾從事各類休閒運動' WHERE code='DOR-TRK-MIA-012';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-MIA-013';
UPDATE explore_bosses SET access_note='提供學校教學及集合學生升降旗典禮及民眾於課後時使用,無其他硬體設施' WHERE code='DOR-TRK-MIA-014';
UPDATE explore_bosses SET access_note='P材質，平常提供田徑、壘球體育教學及第八節田徑校隊練習，課餘開放供民眾使用。另外週邊附設室外排球場1個、標準室外籃球場2個、簡易室外籃球場8個' WHERE code='DOR-TRK-MIA-016';
UPDATE explore_bosses SET access_note='興建約於民國80年，主要作為田徑場及籃球場使用，提供學校體育課程、休閒活動和社區民眾休憩使用' WHERE code='DOR-TRK-MIA-017';
UPDATE explore_bosses SET access_note='本運動場為標準的400公尺場地，風景宜人舒適，提供社區民眾休閒、健身、運動娛樂舒展活動筋骨用' WHERE code='DOR-TRK-MIA-018';
UPDATE explore_bosses SET access_note='本場地於97年4月整修完成,提供師生及社區民眾活動使用.' WHERE code='DOR-TRK-MIA-019';
UPDATE explore_bosses SET access_note='供全校師生上體育課及運動使用，放學後及假日開放社區民眾運動' WHERE code='DOR-TRK-MIA-020';
UPDATE explore_bosses SET access_note='U場地與籃球場，周邊兒童設施於100年完成更新與整建，校園提供村民於休憩時間進行運動與活動。 本場地 ..............' WHERE code='DOR-TRK-MIA-021';
UPDATE explore_bosses SET access_note='84年6月使用紅土操場內有2座籃球場供學生社區民眾使用 http://www.wljh.mlc.edu.tw/' WHERE code='DOR-TRK-MIA-022';
UPDATE explore_bosses SET access_note='本田徑場於民國94年興建完成,內兩個躲避球場,提供本校師生及社區民眾運動的好去處' WHERE code='DOR-TRK-MIA-023';
UPDATE explore_bosses SET access_note='本校田徑場興建於民國84年,目前可供田徑及籃球類使用' WHERE code='DOR-TRK-MIA-024';
UPDATE explore_bosses SET access_note='本場所為田徑場，是學校及社區聯合運動會場地' WHERE code='DOR-TRK-MIA-025';
UPDATE explore_bosses SET access_note='興建於民國84年，場內設有籃球場、排球場、網球場及田徑跑道，可供全校師生共同使用之體育活動設施' WHERE code='DOR-TRK-TXG-001';
UPDATE explore_bosses SET access_note='200公尺田徑場，課餘時間開放民眾使用。內含兩座籃球場、兩座排球場' WHERE code='DOR-TRK-TXG-002';
UPDATE explore_bosses SET access_note='本田徑場為200公尺的跑道，另外操場中間內有4個網球場，全天候開放提供教職員學生使用' WHERE code='DOR-TRK-TXG-003';
UPDATE explore_bosses SET access_note='本操場從創校以來啟用，提供民眾和本校師生使用，舉辦校慶及任何運動性活動' WHERE code='DOR-TRK-TXG-004';
UPDATE explore_bosses SET access_note='78年8月起用學校田徑場,供學校教學及社區民眾下班放學後運動' WHERE code='DOR-TRK-TXG-005';
UPDATE explore_bosses SET access_note='本場地為一般田徑場,有訂定開放時間,提供民眾休憩的場所 0' WHERE code='DOR-TRK-TXG-006';
UPDATE explore_bosses SET access_note='本校操場為本校學生上課時使用，五點後會開放給附近居民使用' WHERE code='DOR-TRK-TXG-007';
UPDATE explore_bosses SET access_note='本校田徑場為200公尺田徑場，平時為學童運動場合，放學後開放給社區民眾運動' WHERE code='DOR-TRK-TXG-008';
UPDATE explore_bosses SET access_note='另有兒童遊戲設施等休閒設施。 106年9月1日前圍捕照期間，對外開放' WHERE code='DOR-TRK-TXG-009';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TXG-010';
UPDATE explore_bosses SET access_note='本場興建於民國97年，位於瑞井里內，是附近居民運動好場所' WHERE code='DOR-TRK-TXG-011';
UPDATE explore_bosses SET access_note='場使用。 本校田徑場大部份時間教職員工及學生使用，課餘時間可供鄰近校區之民眾使用，但如需辦理活動租借場地需與本校管理單位洽詢' WHERE code='DOR-TRK-TXG-012';
UPDATE explore_bosses SET access_note='場地和1個鉛球場地，另有兒童遊戲器材等設施，平時課餘時間免費開放給一般民眾運動使用' WHERE code='DOR-TRK-TXG-013';
UPDATE explore_bosses SET access_note='本操場興建於民國83年，位於大華國中校園內，提供校內師生上課教學使用以及鄰近居民假日休閒散步使用。(200公尺跑道)' WHERE code='DOR-TRK-TXG-014';
UPDATE explore_bosses SET access_note='學生上課級運動並辦理校慶運動會及社區借用運動賽是使用' WHERE code='DOR-TRK-TXG-015';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TXG-016';
UPDATE explore_bosses SET access_note='提供師生上課用之場所及社區民眾假日休閒運動的空間 無' WHERE code='DOR-TRK-TXG-017';
UPDATE explore_bosses SET access_note='建於民國100年，除有200公尺跑道外，另有三座戶外籃球場可供民眾使用' WHERE code='DOR-TRK-TXG-018';
UPDATE explore_bosses SET access_note='大德國小內，周邊另有兒童遊戲設施、戶外體健設施等休閒設施。提供社區居民良好運動與休憩之場所。 2017年3月至5月底進行運動跑道整修工程。工程期間不提供民眾健身活動，欲從事相關運動民眾，請轉往其他場地，謝謝您' WHERE code='DOR-TRK-TXG-019';
UPDATE explore_bosses SET access_note='梧南國小教學用 97年9月整建峻工 供本校教學及社區及校內運動會使用' WHERE code='DOR-TRK-TXG-020';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TXG-021';
UPDATE explore_bosses SET access_note='場興建於民國81年，周邊另有兒童遊戲設施。平時在無學生時間可開放供附近民眾休憩及運動使用' WHERE code='DOR-TRK-TXG-022';
UPDATE explore_bosses SET access_note='，於73年編列200萬興建操場。本操場為標準200公尺操場，可供足球運動及多功能使用' WHERE code='DOR-TRK-TXG-023';
UPDATE explore_bosses SET access_note='本場興建於民國83年，位於西屯區內,提供社區居民假日運動' WHERE code='DOR-TRK-TXG-024';
UPDATE explore_bosses SET access_note='操場綠地2,334平方公尺 操場外圍約1,218平方公尺 可供棒球、壘球、足球、滾球場地運動 興建經費：本校成立時已設立，經費無法查知。 整建PU跑道經費：3,879,223元' WHERE code='DOR-TRK-TXG-025';
UPDATE explore_bosses SET access_note='本運動場建於民國83年，周邊另有重慶及成都公園，是居民運動休閒的好去處' WHERE code='DOR-TRK-TXG-026';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TXG-027';
UPDATE explore_bosses SET access_note='1.供體育課程使用 2.提供社區民眾課後使用 3.提供社區大學教學用' WHERE code='DOR-TRK-TXG-028';
UPDATE explore_bosses SET access_note='於校園內東側，跑道材質PU，平日以學生上課為主，放學及假日則開放社區民眾使用' WHERE code='DOR-TRK-TXG-029';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TXG-030';
UPDATE explore_bosses SET access_note='本操場專屬學生體育課上課用,可供籃球排球田徑手球訓練用,上學前放學後提供龍井區區民運動使用' WHERE code='DOR-TRK-TXG-031';
UPDATE explore_bosses SET access_note='本運動場可供民眾跑步及休閒運動使用，禁止打棒球' WHERE code='DOR-TRK-TXG-032';
UPDATE explore_bosses SET access_note='紅土球場，於97年12月經申請報府核准改建為PU跑道運動場，供學生、社區人士及一般民眾運動使用' WHERE code='DOR-TRK-CHA-001';
UPDATE explore_bosses SET access_note='本校運動場供本校教學及社區民眾休閒使用' WHERE code='DOR-TRK-CHA-002';
UPDATE explore_bosses SET access_note='地(有附設足球門) 周圍綠樹圍繞.不但是個良好學習場所，也是社區民眾休閒運動的好地方.' WHERE code='DOR-TRK-CHA-003';
UPDATE explore_bosses SET access_note='本校操場為學校上課跑步之用，學生放學後提供民眾或學生使用' WHERE code='DOR-TRK-CHA-004';
UPDATE explore_bosses SET access_note='本校田徑場於72年興建，於100年整修PU跑道，目前供全校師生、本校田徑隊、附近居民免費使用。於100年於操場中央整建四座籃球場，供體育課及附近民眾使用。每週一~週五17:05放學後，若本校田徑隊練習時，則以田徑隊練習優先，使用' WHERE code='DOR-TRK-CHA-005';
UPDATE explore_bosses SET access_note='本田徑場於92年1月整建供全校學生田徑運動使用，下午5點後供民眾運動用' WHERE code='DOR-TRK-CHA-006';
UPDATE explore_bosses SET access_note='設於埤頭國小內部，內部設有籃球場可供社區民眾運動休憩' WHERE code='DOR-TRK-CHA-007';
UPDATE explore_bosses SET access_note='運動場裡有pu跑道，免費提供給居民休閒使用， 場中有一個綜合球場，可以從事簡易的球類活動' WHERE code='DOR-TRK-CHA-008';
UPDATE explore_bosses SET access_note='本田徑場屬於開放空間，提供學生教育使用及社區一般民眾休憩之用' WHERE code='DOR-TRK-CHA-009';
UPDATE explore_bosses SET access_note='PU跑到全長近200公尺，共六個跑道，主要提供學校學生體育課，社區居民運動使用' WHERE code='DOR-TRK-CHA-010';
UPDATE explore_bosses SET access_note='一大早民眾常來操場運動,傍晚有放學留下的小朋友跑步,民眾運動,周邊有兒童遊戲設施。 無' WHERE code='DOR-TRK-CHA-011';
UPDATE explore_bosses SET access_note='有200M PU跑道、沙坑、鉛球場等田徑場，可供社區舉辦社區型運動會' WHERE code='DOR-TRK-CHA-012';
UPDATE explore_bosses SET access_note='增建工程」，新建看台壯觀美麗，成為本校進德校區新地標。本場地供體育教學、運動代表隊訓練、舉辦各項運動競賽及供師生、社區民眾多元化使用' WHERE code='DOR-TRK-CHA-013';
UPDATE explore_bosses SET access_note='公速，而將這塊山坡剷平，形成一塊平整的紅土操場，民國97年在社區各方奔走下，由縣府補助400多萬整建成現今的PC跑道，成為學生體育活動和民眾休閒的好去處' WHERE code='DOR-TRK-CHA-015';
UPDATE explore_bosses SET access_note='本場(館)興建於民國90年，位於學校內，提供學生上課用與社區民眾運動用' WHERE code='DOR-TRK-CHA-016';
UPDATE explore_bosses SET access_note='本運動場周邊另有兒童遊戲設施、戶外體健設施等休閒設施，全天候提供師生上課及社區民眾活動使用' WHERE code='DOR-TRK-CHA-017';
UPDATE explore_bosses SET access_note='98年將紅土跑道全面改建成PU跑道，提供師生更舒適的運動環境，非上課期間亦提供社區民眾使用' WHERE code='DOR-TRK-CHA-018';
UPDATE explore_bosses SET access_note='道設備為紅土結構，並於103年申請運動場整建為PU跑道，以提供莘莘學子及社區大眾優質活動場所使用' WHERE code='DOR-TRK-CHA-019';
UPDATE explore_bosses SET access_note='PU跑道興建於民國93年，田徑場地供學生與一般民眾跑步使用' WHERE code='DOR-TRK-CHA-020';
UPDATE explore_bosses SET access_note='田場內含一座籃球場，94年新建完成，平日為師生運動場地，假日供社區民眾使用' WHERE code='DOR-TRK-CHA-021';
UPDATE explore_bosses SET access_note='79年，位於田尾國小內，周邊另有兒童遊戲設施、戶外體健設施，供學校學生及一般民眾使用' WHERE code='DOR-TRK-CHA-022';
UPDATE explore_bosses SET access_note='育館、兒童遊樂設施、成人體健設施、綠色步道等等，每天吸引許多民眾到此運動健身，是鄉民最喜愛的運動場所' WHERE code='DOR-TRK-CHA-023';
UPDATE explore_bosses SET access_note='本校為於彰化縣福興鄉，是彰化市往鹿港的必經之地，學區為番婆社區，跑道長約為160公尺，附設太空漫步機、溜滑梯等設施，是社區民眾運動休閒的好去處。 無' WHERE code='DOR-TRK-CHA-024';
UPDATE explore_bosses SET access_note='本田徑場包含200公尺跑道一圈,中間為籃球場,主要提供學校師生運動教學與社區民眾運動之用' WHERE code='DOR-TRK-CHA-025';
UPDATE explore_bosses SET access_note='本校綜合田徑場肩負本校體育教學、競賽及選手培訓功用，課餘更提供社區居民運動休閒健身' WHERE code='DOR-TRK-CHA-026';
UPDATE explore_bosses SET access_note='本校PU跑道田徑場於民國101年修建完成，供本校師生及一般民眾到校跑步、打球運動用，周邊另有兒童遊戲設施' WHERE code='DOR-TRK-CHA-027';
UPDATE explore_bosses SET access_note='跑道分為六道,共200公尺 ,不曾公開對外比賽,師生及民眾使用.' WHERE code='DOR-TRK-CHA-028';
UPDATE explore_bosses SET access_note='遊戲設施、戶外體健設施等休閒設施。除辦理運動會各項競賽，平日供校內學童及社區民眾運動休閒使用' WHERE code='DOR-TRK-CHA-029';
UPDATE explore_bosses SET access_note='球場、風雨籃球場、景觀池、步道等戶外運動場地，體場館內更是提供多元化靜態休閒活動，讓民眾選擇，故本場館內外空間已達到充份規劃使用' WHERE code='DOR-TRK-CHA-030';
UPDATE explore_bosses SET access_note='本校運動場隨時提供社區民眾運動 921重建後所建置環型運動跑道' WHERE code='DOR-TRK-NAN-001';
UPDATE explore_bosses SET access_note='本場(館)興建於民國80年，環形跑道約150公尺，供學校師生、社區居民教學、運動使用' WHERE code='DOR-TRK-NAN-002';
UPDATE explore_bosses SET access_note='本運動場興建於民國82年，位於精英村(本社區)內，周邊四面環山，無任何休閒設施' WHERE code='DOR-TRK-NAN-003';
UPDATE explore_bosses SET access_note='本運動場供學生上課、選手訓練及課後民眾休閒運動使用，內有籃球場，目前因跑道整建尚' WHERE code='DOR-TRK-NAN-004';
UPDATE explore_bosses SET access_note='育課之足球場，壘球場，田徑場，木球場及飛盤場，課餘時間，免費開放社區民眾使用' WHERE code='DOR-TRK-NAN-006';
UPDATE explore_bosses SET access_note='本場地興建於82年，可供校外人士放學期間或假日到校實施運動，週邊有籃球場、單槓等設施' WHERE code='DOR-TRK-NAN-007';
UPDATE explore_bosses SET access_note='體育教學用操場，跑道及籃球場，及辦理社區運動會' WHERE code='DOR-TRK-NAN-008';
UPDATE explore_bosses SET access_note='本運動場建於操場邊,是學生上課民眾運動的休閒好所在' WHERE code='DOR-TRK-NAN-009';
UPDATE explore_bosses SET access_note='本運動場興建於92年，內為草皮，外有六道PU跑道，供師生上課及社區民眾運動用' WHERE code='DOR-TRK-NAN-010';
UPDATE explore_bosses SET access_note='本校田徑場可供小型運動會及園遊會場地使用' WHERE code='DOR-TRK-NAN-011';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-NAN-012';
UPDATE explore_bosses SET access_note='本校運動場包括田徑場1座、籃球場1座、網球場1座。提供學生上課及社區民眾課後與假日運動休憩之場地' WHERE code='DOR-TRK-NAN-013';
UPDATE explore_bosses SET access_note='本場興建於民國77年2月，位於日月潭邊德化社區內，周邊另有兒童遊樂設施等休閒設施' WHERE code='DOR-TRK-NAN-014';
UPDATE explore_bosses SET access_note='道，因經費關係，只撲設4個跑道，現在，本校運動場內圈為草地，供學童踢球及遊樂場所，外圍跑道為4道跑道，供學童上課及社區民眾運動跑步健走，再外圍預定申請撲設草皮維護環境' WHERE code='DOR-TRK-NAN-015';
UPDATE explore_bosses SET access_note='本場地為傳統式紅土運動場，內設籃球場，提供民眾下班級假日休閒運動之場域' WHERE code='DOR-TRK-NAN-016';
UPDATE explore_bosses SET access_note='民國44年建造，101年興建PU跑道，周邊另有兒童遊戲設施可供民眾休閒用' WHERE code='DOR-TRK-YUN-001';
UPDATE explore_bosses SET access_note='等，周邊另有兒童遊戲器材，操場為典型紅土跑道，平日放學時間可供社區民眾使用。 無' WHERE code='DOR-TRK-YUN-002';
UPDATE explore_bosses SET access_note='本校操場PU跑道於101年完工使用，操場內草皮可供足球場使用，周邊另有兒童遊戲設施、戶外體健設施等休閒設施' WHERE code='DOR-TRK-YUN-003';
UPDATE explore_bosses SET access_note='本場所供元長鄉元長國小學生及附近民眾運動使用' WHERE code='DOR-TRK-YUN-004';
UPDATE explore_bosses SET access_note='本球場提供本校學生上課使用，課後提供社區休閒活動用' WHERE code='DOR-TRK-YUN-005';
UPDATE explore_bosses SET access_note='PU材質場地，供本校學生上體育課及社團使用外，平日清晨及傍晚開放給社區人士健身運動' WHERE code='DOR-TRK-YUN-006';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-YUN-007';
UPDATE explore_bosses SET access_note='本運動場位於校園內，供學生上課使用及社區人士休閒運動用' WHERE code='DOR-TRK-YUN-008';
UPDATE explore_bosses SET access_note='民國83年12月，周邊另有兒童遊戲設施及綜合球場，平日上課提供教學使用，假日提供社區大眾運動休閒使用' WHERE code='DOR-TRK-YUN-009';
UPDATE explore_bosses SET access_note='取獲得教育部補助，於民國102年4月完成pu跑道，造福學生與社區民眾，運動休閒好去處' WHERE code='DOR-TRK-YUN-010';
UPDATE explore_bosses SET access_note='提供學生活動場所,下班後社區人員的休閒場地' WHERE code='DOR-TRK-YUN-011';
UPDATE explore_bosses SET access_note='本場興建於民國84年，可提供學生上課時使用，並可提供社區民眾運動休閒等功能。周邊另有籃球場，均可提供社區民眾使用' WHERE code='DOR-TRK-YUN-012';
UPDATE explore_bosses SET access_note='本場所於民國83年修建,位於校園內,提供民眾運動休閒活動.' WHERE code='DOR-TRK-YUN-013';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-YUN-014';
UPDATE explore_bosses SET access_note='本場興建於民國101年，位於陽明國小內，可提供戶外學生及社區民眾體健設施等休閒設施' WHERE code='DOR-TRK-YUN-015';
UPDATE explore_bosses SET access_note='本校操場位於市中心區，是周遭社區居民休閒的好地方' WHERE code='DOR-TRK-YUN-016';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-YUN-017';
UPDATE explore_bosses SET access_note='本場(館)興建於民國65年，提供地方社區人士使用周邊綠地設施、戶外體健設施等休閒設施。 無' WHERE code='DOR-TRK-YUN-018';
UPDATE explore_bosses SET access_note='國小運動用場所平日供學生上體育課.周邊有pu跑道運場動.可供慢跑.民眾運動' WHERE code='DOR-TRK-YUN-019';
UPDATE explore_bosses SET access_note='本田徑場一~日均對外開放，若遇平常上課日，則以校內學生使用為主' WHERE code='DOR-TRK-YUN-020';
UPDATE explore_bosses SET access_note='擲鉛球場、噴水設備...等，99年5月再完成PU跑道整建，提供教學及社區民眾運動之用' WHERE code='DOR-TRK-YUN-021';
UPDATE explore_bosses SET access_note='本PU跑道位於臺西國小內,旁有籃球場,很多學生和民眾都前來使用' WHERE code='DOR-TRK-YUN-022';
UPDATE explore_bosses SET access_note='本校運動場周長約150公尺 跑道是紅磚土 內植草皮 可供學生踢球 打球使用' WHERE code='DOR-TRK-YUN-023';
UPDATE explore_bosses SET access_note='本操場興建於民國49年，位於校園內後方，提供社區居民及學生健身運動用' WHERE code='DOR-TRK-YUN-024';
UPDATE explore_bosses SET access_note='為一簡易學生上課用或附近居民平日休閒及運動之場所' WHERE code='DOR-TRK-YUN-025';
UPDATE explore_bosses SET access_note='本校操場跑道200公尺，平日為學生、民眾運動場所，操場中全為綠地，平日定期修剪草皮，並作為球類運動或遊戲場所用' WHERE code='DOR-TRK-YUN-026';
UPDATE explore_bosses SET access_note='上課日上課用，假日提供社區民眾運動休閒用' WHERE code='DOR-TRK-YUN-027';
UPDATE explore_bosses SET access_note='舍遷建，於是99年規劃新建操場，100年4月完工，作為學校於社區民眾使用' WHERE code='DOR-TRK-YUN-028';
UPDATE explore_bosses SET access_note='陀禪寺，左側為八掌溪堤防高地。現今彌陀路已改道連接忠義橋。 開放時間：一般時間：04:00~22:00、夏季：04:00~22:00、冬季：05:00~22:00 觀眾席：15,000 席。 400公尺PU跑道' WHERE code='DOR-TRK-CYI-001';
UPDATE explore_bosses SET access_note='國88年興建教學大樓時一併興建而成，平日非上課時段及例假日均開放民眾使用' WHERE code='DOR-TRK-CYI-002';
UPDATE explore_bosses SET access_note='嘉義市育人國小田徑場興建於民國89年 平日使用，假日則對外開放' WHERE code='DOR-TRK-CYI-003';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-CYQ-001';
UPDATE explore_bosses SET access_note='本場地提供校內師生體育課及課餘時間和假日時社區人士使用' WHERE code='DOR-TRK-CYQ-003';
UPDATE explore_bosses SET access_note='本校操場及戶外籃球場為周圍社區學生及社區人士主要運動場所，共3座籃球場' WHERE code='DOR-TRK-CYQ-004';
UPDATE explore_bosses SET access_note='水泥場地，為籃球場，週圍圍環型pu跑道，平時上課使用，課餘則開放社區民眾運動休憩用。 暫無' WHERE code='DOR-TRK-CYQ-005';
UPDATE explore_bosses SET access_note='本田徑場於102年重新修繕.提供全校師生運動使用.課餘時間則開放奢區民眾運動休閒使用' WHERE code='DOR-TRK-CYQ-006';
UPDATE explore_bosses SET access_note='月前啟用之場館，總運動面積為3218平方公尺，假日時，偶有民眾進入場內運動' WHERE code='DOR-TRK-CYQ-007';
UPDATE explore_bosses SET access_note='會，周邊另有兒童遊戲設施，且積極綠美化，是旅客駐足之處，也是社區民眾運動場所' WHERE code='DOR-TRK-CYQ-008';
UPDATE explore_bosses SET access_note='國85年於舊有的操場上，鋪上PU材質的跑道，至今為本校學生與社區家長共同使用與維護的田徑場地' WHERE code='DOR-TRK-CYQ-009';
UPDATE explore_bosses SET access_note='操場整建於民國81年，為pu跑道設施，提供學生體育課及民眾運動' WHERE code='DOR-TRK-CYQ-010';
UPDATE explore_bosses SET access_note='本校pu跑道修建於民國93年12月,環繞於本校操場,提供本校師生上課及社區居民運動之場所,周邊另有設置兒童遊戲設施.' WHERE code='DOR-TRK-CYQ-011';
UPDATE explore_bosses SET access_note='跑道 1座籃球場 1座排球場 為發展全民體育，增進國民健康 供(1) 本鄉籍民眾（含社團）(2) 本鄉各級學校(3) 本鄉各級行政機關(4) 經申請核准之鄉外團體 使用 請依阿里山鄉立體育場運動設施設備管理規約申請使用' WHERE code='DOR-TRK-CYQ-012';
UPDATE explore_bosses SET access_note='本校田徑場完工於80年，主要堤供全校師生體育教學及舉辦社區運動會使用 無' WHERE code='DOR-TRK-TNN-001';
UPDATE explore_bosses SET access_note='場及兒童遊戲器材設施。 假日下午4點以前本校常有球隊練習，請民眾在運動時盡量在外側跑道以免發生危險' WHERE code='DOR-TRK-TNN-002';
UPDATE explore_bosses SET access_note='本場(館)興建於民國85年8月，上課期間使用，下課期間可供附近民眾使用' WHERE code='DOR-TRK-TNN-003';
UPDATE explore_bosses SET access_note='側，臨近本校籃球場與活動中心．非常適合喜歡運動、慢跑、健走之民眾使用' WHERE code='DOR-TRK-TNN-004';
UPDATE explore_bosses SET access_note='平時提供學生活動、遊憩以及上課使用，社區民眾遊憩運動，操場旁設置幼兒園遊樂器材，增加活動設施' WHERE code='DOR-TRK-TNN-005';
UPDATE explore_bosses SET access_note='使用之運動場地，平時做為學生體育課時運動、教學場地，假日則提供錦湖社區的民眾進行球類運動之場所。運動會時亦作為運動競技與趣味競賽之場地。在推動交通安全教育方面，本球場亦為單車考照的場地' WHERE code='DOR-TRK-TNN-006';
UPDATE explore_bosses SET access_note='路及新孝路交接路口，具有300公尺PU跑道，中央設有足球門以供足球運動使用，平時上課時間供學生上課專用，其餘時間供社區民眾運動' WHERE code='DOR-TRK-TNN-007';
UPDATE explore_bosses SET access_note='於民國78年，位於大成路與興華路交叉口，周邊另有體適能設施，供社區民眾使用' WHERE code='DOR-TRK-TNN-009';
UPDATE explore_bosses SET access_note='本運動場興建於民國87年，位於學校內,提供師生及社區使用. 無' WHERE code='DOR-TRK-TNN-010';
UPDATE explore_bosses SET access_note='本運動場修繕於民國100年，提供本校師生及社區愛好運動人士做為休閒及運動的場所' WHERE code='DOR-TRK-TNN-011';
UPDATE explore_bosses SET access_note='本校網球場共有3面，為上課及社團使用時間外平時供社區居民使用' WHERE code='DOR-TRK-TNN-012';
UPDATE explore_bosses SET access_note='重新鋪設;目前又有多處被樹破壞,跑道隆起,造成師生上課活動及社區民眾運動時有安全虞慮' WHERE code='DOR-TRK-TNN-013';
UPDATE explore_bosses SET access_note='本操場興建於民國94年，可提供學生與社區居民運動場域，並於周邊另有兒童遊戲設施、戶外體健設施等休閒設施' WHERE code='DOR-TRK-TNN-014';
UPDATE explore_bosses SET access_note='場地跑道長度為200公尺，共有七道跑道，採取PU跑道設置，提供民眾休閒跑步運動的場地' WHERE code='DOR-TRK-TNN-015';
UPDATE explore_bosses SET access_note='完成改善整建做為學校教學與學生活動使用，非上班時間與例假日提供一班民眾使用，修養強健體魄' WHERE code='DOR-TRK-TNN-016';
UPDATE explore_bosses SET access_note='日為本校師生上課活動之場地，放學後(16:45)及例假日亦提供一般民眾使用' WHERE code='DOR-TRK-TNN-017';
UPDATE explore_bosses SET access_note='修完成，除外圍跑道，內設有躲避球場2面，周圍尚有兒童遊戲器材可供學童使用' WHERE code='DOR-TRK-TNN-018';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TNN-019';
UPDATE explore_bosses SET access_note='崇明國中運動場,為崇明國中師生升旗及上課教學使用場地,平常也供附近民眾使用.場所包掛籃球場,網球場級排球場' WHERE code='DOR-TRK-TNN-020';
UPDATE explore_bosses SET access_note='本場位於復興國小內，提供全校師生上體育課 各類運動 舉辦運動會等 周邊另有兒童遊戲設施、戶外體健設施等休閒設施。附近居民下課後也常利用本場地運動' WHERE code='DOR-TRK-TNN-021';
UPDATE explore_bosses SET access_note='臺南市106年高智爾球對抗賽，歡迎民眾前往觀賽。活動期間不提供民眾健身活動，欲從事相關運動民眾，請轉往其他場地，謝謝您' WHERE code='DOR-TRK-TNN-022';
UPDATE explore_bosses SET access_note='本操場完成於民國101年，位於東原國小內，平日供教學用，其餘時間提供給社區民眾使用． 無' WHERE code='DOR-TRK-TNN-023';
UPDATE explore_bosses SET access_note='98年，位於學校西側，周邊另有兒童遊戲設施及多功能球場等，提供本校學童優質上課環境及社區居民戶外運動、休閒休憩的好去處' WHERE code='DOR-TRK-TNN-024';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-TNN-025';
UPDATE explore_bosses SET access_note='87年8月完工，主要作為學生上課與學生下課活動場地，其他時間社區民眾近來運動健身' WHERE code='DOR-TRK-TNN-026';
UPDATE explore_bosses SET access_note='跑道供學童及社區民眾運動使用興建於民國89年' WHERE code='DOR-TRK-TNN-027';
UPDATE explore_bosses SET access_note='0年，使用。 每日5:00~7:00、16:30~22:00開放民眾運動使用' WHERE code='DOR-TRK-TNN-028';
UPDATE explore_bosses SET access_note='民國87年，位於麻豆區培文國小，平日作為教學用，放學或假日時開放社區民眾使用；週圍設有兒童遊戲設施' WHERE code='DOR-TRK-TNN-029';
UPDATE explore_bosses SET access_note='017年4月８日為校慶運動會，歡迎民眾前往觀賽。活動期間不提供民眾健身活動，欲從事相關運動民眾，請轉往其他場地，謝謝您' WHERE code='DOR-TRK-KHH-001';
UPDATE explore_bosses SET access_note='本校田徑場有六個跑道是200公尺跑道,提供師生及社區居民活動使用' WHERE code='DOR-TRK-KHH-002';
UPDATE explore_bosses SET access_note='道，場地設有一跳遠沙坑，於上課期間提供課程及學生使用，課後則開放一般民眾使用' WHERE code='DOR-TRK-KHH-003';
UPDATE explore_bosses SET access_note='9年因重建校舍而設置，周邊有風雨球場及兒童遊戲區 紅土運動場開放民眾假日使用' WHERE code='DOR-TRK-KHH-004';
UPDATE explore_bosses SET access_note='目前運動場以足球隊、田徑隊訓練及一般體育課上課為主，於則提供民眾運動使用' WHERE code='DOR-TRK-KHH-005';
UPDATE explore_bosses SET access_note='，周邊另有兒童遊戲設施、籃球場、足球場等休閒設施。 於放學後開放運動場提供附近居民使用' WHERE code='DOR-TRK-KHH-006';
UPDATE explore_bosses SET access_note='本運動場興建於民國83年8月，周邊另有兒童遊戲設施，提供給本校學生上課運動，和社區人士休閒運動之用' WHERE code='DOR-TRK-KHH-007';
UPDATE explore_bosses SET access_note='為本校體育教學及活動使用並於放學時間為社區民眾運動用' WHERE code='DOR-TRK-KHH-008';
UPDATE explore_bosses SET access_note='習場二個、手球場一座，平常主要作為學生上可使用，放學後則做為社區民眾的休閒場所' WHERE code='DOR-TRK-KHH-009';
UPDATE explore_bosses SET access_note='00公尺。為本校體育課、運動會及大型集會場所，亦為放學後一般民眾運動遊憩場所' WHERE code='DOR-TRK-KHH-010';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-KHH-011';
UPDATE explore_bosses SET access_note='本場興建於民國98年，平日學童放學後供社區民眾休閒運動用' WHERE code='DOR-TRK-KHH-012';
UPDATE explore_bosses SET access_note='有田徑場一面,籃球場7面,網球場3面,攀岩場1座,平常有附近民眾來運動' WHERE code='DOR-TRK-KHH-013';
UPDATE explore_bosses SET access_note='平日供教師體育教學及田徑賽使用,也兼作樂樂棒球場,並開放給一般民眾' WHERE code='DOR-TRK-KHH-014';
UPDATE explore_bosses SET access_note='本場(館)興建於民國96年，位於舊城國小內，平日放學後及假日供民眾運動使用' WHERE code='DOR-TRK-KHH-015';
UPDATE explore_bosses SET access_note='本田徑場供學校教學使用並開放社區民眾運動' WHERE code='DOR-TRK-KHH-016';
UPDATE explore_bosses SET access_note='體育場位於旗山區華中街上，鄰近旗山國小，常可在傍晚時看到當地民眾前來體育場運動' WHERE code='DOR-TRK-KHH-017';
UPDATE explore_bosses SET access_note='遊戲設施，除本校學生上體育課及校慶運動會外，於非上班日亦可提供社區居民使用' WHERE code='DOR-TRK-KHH-019';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-KHH-020';
UPDATE explore_bosses SET access_note='跑道為人工跑道，場地對外開放給一般民眾運動' WHERE code='DOR-TRK-KHH-021';
UPDATE explore_bosses SET access_note='公司斥資3000萬元建造的400公尺pu田徑場，週邊有觀察林可供休憩:並有戶外體健運動設施' WHERE code='DOR-TRK-KHH-022';
UPDATE explore_bosses SET access_note='本場(館)興建於民國67年，操場供學生體育課使用，放學後開放社區民眾運動' WHERE code='DOR-TRK-KHH-023';
UPDATE explore_bosses SET access_note='本校田徑場可供足球運動使用，設有司令台，及觀眾休息區' WHERE code='DOR-TRK-KHH-024';
UPDATE explore_bosses SET access_note='PU操場，平日非上課期間提供社區民眾健身運動使用。 www.lsp.ks.edu.tw' WHERE code='DOR-TRK-KHH-025';
UPDATE explore_bosses SET access_note='本場建於民國81年，主供師生進行教學活動使用，課後時間，開放社區民眾使用' WHERE code='DOR-TRK-KHH-026';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-KHH-027';
UPDATE explore_bosses SET access_note='本運動場興建於民國80年，位於五權國小校園內，供學校教學用，放學或假日供社區人士運動休閒' WHERE code='DOR-TRK-KHH-028';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-KHH-029';
UPDATE explore_bosses SET access_note='約興建於民國75年，位於萬山里左下方，周邊另有綜合球場設施，可供戶外體健設施等休閒活動' WHERE code='DOR-TRK-KHH-030';
UPDATE explore_bosses SET access_note='，位於路竹高中校區內，平常為體育課或體育班練習場地，亦為附近民眾早上及下午運動的空間之一，附近有路竹公園等休憩場所' WHERE code='DOR-TRK-KHH-031';
UPDATE explore_bosses SET access_note='本校操場跑道是pu跑道四週植有榕樹環繞綠蔭成排民眾下午運動好去處' WHERE code='DOR-TRK-KHH-032';
UPDATE explore_bosses SET access_note='本場地整建於民國99年，位於文山高中內，300公尺全天候空隙式跑道' WHERE code='DOR-TRK-KHH-033';
UPDATE explore_bosses SET access_note='本田徑場興建於民國73年，提供學校師生及鄰近居民運動休閒使用' WHERE code='DOR-TRK-KHH-034';
UPDATE explore_bosses SET access_note='250公尺橢圓形運動場提供學校學生上體育課及附近民眾非影響上課時段運動' WHERE code='DOR-TRK-KHH-035';
UPDATE explore_bosses SET access_note='人制甲、乙組足球錦標賽及各項田徑活動辦理主場地，帶動鳳山地區居民的運動風氣' WHERE code='DOR-TRK-KHH-036';
UPDATE explore_bosses SET access_note='本校田徑場提供民眾課後即假日休閒運動之場所，恕棒壘球之場地租借' WHERE code='DOR-TRK-KHH-037';
UPDATE explore_bosses SET access_note='本校田徑場興建於民國82年，非上課時段開放社區民眾' WHERE code='DOR-TRK-KHH-038';
UPDATE explore_bosses SET access_note='操場供足球木球等及社區民眾運動跑步休閒使用' WHERE code='DOR-TRK-PIF-001';
UPDATE explore_bosses SET access_note='師生校園路跑、田徑代表隊組訓、體能檢測外，亦是學生足球運動、社區居民健身與休閒的場地。同時本校設有田徑場夜間照明系統，讓本校田徑場開放時段之彈性大大的提高。 司令台包含有本校休閒運動保健系系學會辦公室、學生會辦公室、田徑場辦公室1間、專業教室3間(運動技能證照輔導、運動健康管理及休閒服務專業證照)、教師研究室、社團辦公室、運動器材室' WHERE code='DOR-TRK-PIF-002';
UPDATE explore_bosses SET access_note='本場地興建於民國86年，在學校內供學生上課及課後、假日民眾運動使用' WHERE code='DOR-TRK-PIF-003';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-PIF-004';
UPDATE explore_bosses SET access_note='兒童遊戲設施 一面兒童籃球場、戶外體健設施等休閒設施。主要提供本校師生上課及社區民眾休閒運動用' WHERE code='DOR-TRK-PIF-005';
UPDATE explore_bosses SET access_note='至民國57年啟用至今,為標準400m紅土跑道,中間為天然草皮可供足球場使用' WHERE code='DOR-TRK-PIF-006';
UPDATE explore_bosses SET access_note='本場館改建於民國96年，位於鶴聲國小內屬於師生體育教學及社區民眾休閒運動的好場所' WHERE code='DOR-TRK-PIF-008';
UPDATE explore_bosses SET access_note='本場館興建於民國92年8月，主為學生體育教學使用，亦提供社區民眾運動之場所' WHERE code='DOR-TRK-PIF-009';
UPDATE explore_bosses SET access_note='運動場周邊另有排球場、籃球場、足球場及體能訓練場 寒暑假除外開放時間上午5:00-7:30，下午17:00-22:00' WHERE code='DOR-TRK-PIF-010';
UPDATE explore_bosses SET access_note='操場跑道，可供跑步使用。操場中央可供適合運動使用' WHERE code='DOR-TRK-PIF-011';
UPDATE explore_bosses SET access_note='崎峰國小田徑場於83年整修，含操場、司令台及150M跑道，提供民眾運動場所' WHERE code='DOR-TRK-PIF-012';
UPDATE explore_bosses SET access_note='學校操場-供學生上課 放學後及假日供社區民眾運動' WHERE code='DOR-TRK-PIF-013';
UPDATE explore_bosses SET access_note='年前早已建置完成，位於本校範圍內，周邊另有兒童遊戲設施，亦提供村民假日運動活動使用' WHERE code='DOR-TRK-PIF-014';
UPDATE explore_bosses SET access_note='本場所興建於民國88年,位於屏東縣潮和國小,提供學校師生及社區民眾運動' WHERE code='DOR-TRK-PIF-015';
UPDATE explore_bosses SET access_note='辦理各項運動競賽與提供社區民眾休閒運動86年正式啟用 無舉辦賽事' WHERE code='DOR-TRK-PIF-016';
UPDATE explore_bosses SET access_note='周邊為社區的道路，鄰近社區公園。 （二） 操場多功能用途，提供社區民眾休閒及安全運動場所，促進社區運動風氣。 （三） 學校結合社區特色，大力推動體育活動，定期與社區合作 辦理各項體育活動 （四） 學校與社區合作，推展全民運動，培養強健體魄的國民' WHERE code='DOR-TRK-PIF-017';
UPDATE explore_bosses SET access_note='補助600萬元，改建為PU跑道，大大增加實用性，同時大大提昇鄉民使用率，深受居民與遊客好評' WHERE code='DOR-TRK-PIF-018';
UPDATE explore_bosses SET access_note='86興建校舍同時啟用94年曾整建新pp跑道平時開放社區使用' WHERE code='DOR-TRK-PIF-019';
UPDATE explore_bosses SET access_note='供本校師生體育課並於放學後社區民眾運動使用' WHERE code='DOR-TRK-PIF-020';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-PIF-021';
UPDATE explore_bosses SET access_note='廣興國小操場是村民休閒的好地方' WHERE code='DOR-TRK-PIF-022';
UPDATE explore_bosses SET access_note='本場地為學校教學用設施 ，除教學使用外，亦開放社區民眾於課餘時間使用' WHERE code='DOR-TRK-PIF-023';
UPDATE explore_bosses SET access_note='，平時以鄉內各級學校各項運動教學、棒球訓練之主要場地，更可提供民眾晨昏間休閒運動場所' WHERE code='DOR-TRK-ILA-001';
UPDATE explore_bosses SET access_note='林國小校內，周邊另有兒童遊戲設施、戶外體健設施等休閒設施，是社區內唯一運動場所' WHERE code='DOR-TRK-ILA-002';
UPDATE explore_bosses SET access_note='，於92年、94年學校新建校舍時有小幅整修過，主要作為學生及社區家長運動使用。 106年4月1日、4月2日辦理百週年校慶及餐會' WHERE code='DOR-TRK-ILA-003';
UPDATE explore_bosses SET access_note='學校操場約為150公尺，提供學生上課及社區民眾休憩使用' WHERE code='DOR-TRK-ILA-004';
UPDATE explore_bosses SET access_note='外田徑場興建於民國96年，位於校園西北側靠近建蘭南路旁，為提供本校師生教學運動及社區居民運動場地' WHERE code='DOR-TRK-ILA-005';
UPDATE explore_bosses SET access_note='場、鐵餅場、跳遠場及籃球場。上午7點前及下午5:10後，免費開放民眾使用' WHERE code='DOR-TRK-ILA-006';
UPDATE explore_bosses SET access_note='球3對3比賽、躲避球比賽等，並有6道跑道及4座籃球架，為附近居民運動散步最佳場所' WHERE code='DOR-TRK-ILA-007';
UPDATE explore_bosses SET access_note='01年，正式啟用於民國102年，位於本校校園東側門旁，場地採開放式空間，有屋頂遮蔽風雨，適合各類運動' WHERE code='DOR-TRK-ILA-008';
UPDATE explore_bosses SET access_note='周圍紅土跑道約150米，8線跑道，供學生體育課程使用，平日有開放供社區民眾活動' WHERE code='DOR-TRK-ILA-009';
UPDATE explore_bosses SET access_note='民國80年，位於學校內，並於98年爭取pu跑道設施，內有草皮可供足球、樂樂棒球等運動使用' WHERE code='DOR-TRK-ILA-010';
UPDATE explore_bosses SET access_note='本校田徑場地修建於民國93年提供社區民眾戶外體健使用及本校師生上課使用' WHERE code='DOR-TRK-ILA-011';
UPDATE explore_bosses SET access_note='本場地為多功能田徑場，可供樂樂棒,直排輪使用，但無照明設備' WHERE code='DOR-TRK-ILA-012';
UPDATE explore_bosses SET access_note='本校運動場設有一座17公尺?，28公尺長的風雨籃球場，可提供學生上課與課後作為社區民眾運動與各項球類活動使用。 另環形活動場提供學生活動使用，課後亦可提供社區民眾活動使用。 另設有一座70公尺長直線跑道，提供學生活動使用，課後亦可提供社區民眾活動使用' WHERE code='DOR-TRK-ILA-013';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-ILA-014';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-ILA-015';
UPDATE explore_bosses SET access_note='本場位於校園內，平日清晨06:30前與下午放學17:30後開放與社區居民共用，因靠海且近太魯閣，所以也常有廠商租借' WHERE code='DOR-TRK-HUA-001';
UPDATE explore_bosses SET access_note='本場(館)興建於民國71年4月啟用，使用紅土鋪設而成，提供兒童及社區人士運動使用' WHERE code='DOR-TRK-HUA-002';
UPDATE explore_bosses SET access_note='長良國小操場位於長良國小校內，跑道一圈為140公尺，可供田徑運動。操場中央草皮，有足球門設施，平時為學生進行各項體育活動所用' WHERE code='DOR-TRK-HUA-003';
UPDATE explore_bosses SET access_note='本運動場興建於民國37年，位於鶴岡國小內，提供本校學生體育課上課活動以及社區民眾假日休閒之用' WHERE code='DOR-TRK-HUA-004';
UPDATE explore_bosses SET access_note='1處遊樂區。從103年一月起，每天下午3點多，有越來越多的社區民眾，主動來慢跑。歡迎全民一起來運動，一起來走操場' WHERE code='DOR-TRK-HUA-005';
UPDATE explore_bosses SET access_note='本校操場建於民國45年，操場中央為籃球場，兩側為草地，為社區部落年輕人的運動場地' WHERE code='DOR-TRK-HUA-006';
UPDATE explore_bosses SET access_note='除供平常體育教學、學生朝會、村校聯合運動會與鄉運使用，六、日開放社區民眾蒞臨本校健身與運動' WHERE code='DOR-TRK-HUA-008';
UPDATE explore_bosses SET access_note='位於長橋國小內，為校用場地，放學後供社區民眾使用' WHERE code='DOR-TRK-HUA-009';
UPDATE explore_bosses SET access_note='本操場除為師生體育教學活動使用外，更是社區民眾假日休閒運動活動場地' WHERE code='DOR-TRK-TTT-001';
UPDATE explore_bosses SET access_note='200公尺操場一座，於80年8月完工，跑道可供跑步，操場可供小型7人制足球，足壘球、樂樂棒球使用' WHERE code='DOR-TRK-TTT-002';
UPDATE explore_bosses SET access_note='本運動場地含籃球長及排球場地是社區民眾青年休閒最佳場所' WHERE code='DOR-TRK-TTT-003';
UPDATE explore_bosses SET access_note='附近有卑南文化公園,周邊的設施有籃球場.排球場等設施,鈞都是對外開放且不收任何相關費用,田徑場從未辦理過大型的賽事,只辦理校內運動會,田徑場有400公尺是用紅土鋪設的跑道,周邊的籃球場有4面,有一個排球場地,田徑場中間也可以當作足球場地時用.' WHERE code='DOR-TRK-TTT-004';
UPDATE explore_bosses SET access_note='本校田徑場除提供教學使用之外，四周設有兒童遊樂器材區，亦提供一般民眾假日休閒活動之用。 無' WHERE code='DOR-TRK-TTT-005';
UPDATE explore_bosses SET access_note='於100年底落成之PU塑膠跑道,學生上課活動用,課餘時間供民眾運動休閒用,田徑場旁有綜合球場一座,溜冰曲棍球一座' WHERE code='DOR-TRK-TTT-006';
UPDATE explore_bosses SET access_note='本運動場屬於椰油國小，為學校運動場，下午五點至七點開放民眾運動' WHERE code='DOR-TRK-TTT-007';
UPDATE explore_bosses SET access_note='本場興建於民國84年，平時供教師進行體育課程教學，放學後及假日供社區民眾運動使用' WHERE code='DOR-TRK-TTT-008';
UPDATE explore_bosses SET access_note='本運動場位於樟原國小內，上課日供學生教學使用，其餘時間全天候開放' WHERE code='DOR-TRK-TTT-009';
UPDATE explore_bosses SET access_note='在的樣貌,中間為草皮適合進行足球與棒壘球運動.外圍紅土跑道為社區居民最愛的散步場所. 周邊有籃球場與遊戲器材適合全家老少到校運動健身.' WHERE code='DOR-TRK-TTT-010';
UPDATE explore_bosses SET access_note='館興建於民國67年,位於電光國小校園內.平日除上課使用外並提供社區民眾等免費使用.' WHERE code='DOR-TRK-TTT-011';
UPDATE explore_bosses SET access_note='本校操場主要為國小及幼兒園使用,另於上課時間外提供民眾運動空間' WHERE code='DOR-TRK-PEN-001';
UPDATE explore_bosses SET access_note='本校為小型學校，操場供學校師生與社區民眾使用' WHERE code='DOR-TRK-PEN-002';
UPDATE explore_bosses SET access_note='（週一至週五）８時－16時為學校使用時間，清晨、傍晚及例假日可供眾使用，本場地無夜間照明設備' WHERE code='DOR-TRK-PEN-003';
UPDATE explore_bosses SET access_note='提供學校學生體育課及田徑練習、社區民眾休閒運動使用' WHERE code='DOR-TRK-PEN-005';
UPDATE explore_bosses SET access_note='本場興建於101年，位於上岐村內，周邊另有跑道、籃球場等可供居民使用' WHERE code='DOR-TRK-KIN-001';
UPDATE explore_bosses SET access_note='視野遼闊、空氣清新及微風不時輕拂，令人深感身心舒適，是鄰近居民休閒運動之最佳場所' WHERE code='DOR-TRK-KIN-002';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-LIE-001';
UPDATE explore_bosses SET access_note='公有／公園／體育場型田徑設施；實際開放時段需依 iPlay 或現場公告複核' WHERE code='DOR-TRK-LIE-002';
UPDATE explore_bosses SET access_note='本運動場提供地區民眾及部隊官兵從事各項運動使用，場地設施有田徑運動場、兒童遊樂場' WHERE code='DOR-TRK-LIE-003';

INSERT INTO schema_migrations (version) VALUES ('069') ON CONFLICT DO NOTHING;