-- Migration 082: 自主訓練 P1 —— 配速等級表 + 課表庫(system seed)
CREATE TABLE IF NOT EXISTS pace_levels (
  id INT PRIMARY KEY, label TEXT NOT NULL, paces JSONB NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS workout_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT UNIQUE NOT NULL, name TEXT NOT NULL,
  category TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', segments JSONB NOT NULL,
  sort_order INT NOT NULL DEFAULT 0, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());

INSERT INTO pace_levels (id,label,paces) VALUES (1,'輕鬆 7:57-8:33','{"easy": {"fast": 477, "slow": 513}, "marathon": {"fast": 426, "slow": 446}, "threshold": {"fast": 402, "slow": 420}, "interval": {"fast": 373, "slow": 389}, "rep": {"fast": 353, "slow": 369}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (2,'輕鬆 7:17-7:53','{"easy": {"fast": 437, "slow": 473}, "marathon": {"fast": 390, "slow": 410}, "threshold": {"fast": 369, "slow": 387}, "interval": {"fast": 342, "slow": 358}, "rep": {"fast": 324, "slow": 340}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (3,'輕鬆 6:42-7:18','{"easy": {"fast": 402, "slow": 438}, "marathon": {"fast": 360, "slow": 380}, "threshold": {"fast": 340, "slow": 358}, "interval": {"fast": 315, "slow": 331}, "rep": {"fast": 299, "slow": 315}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (4,'輕鬆 6:12-6:48','{"easy": {"fast": 372, "slow": 408}, "marathon": {"fast": 333, "slow": 353}, "threshold": {"fast": 315, "slow": 333}, "interval": {"fast": 292, "slow": 308}, "rep": {"fast": 277, "slow": 293}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (5,'輕鬆 5:42-6:18','{"easy": {"fast": 342, "slow": 378}, "marathon": {"fast": 307, "slow": 327}, "threshold": {"fast": 290, "slow": 308}, "interval": {"fast": 269, "slow": 285}, "rep": {"fast": 255, "slow": 271}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (6,'輕鬆 5:15-5:51','{"easy": {"fast": 315, "slow": 351}, "marathon": {"fast": 283, "slow": 303}, "threshold": {"fast": 267, "slow": 285}, "interval": {"fast": 248, "slow": 264}, "rep": {"fast": 235, "slow": 251}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (7,'輕鬆 4:48-5:24','{"easy": {"fast": 288, "slow": 324}, "marathon": {"fast": 259, "slow": 279}, "threshold": {"fast": 245, "slow": 263}, "interval": {"fast": 228, "slow": 244}, "rep": {"fast": 215, "slow": 231}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (8,'輕鬆 4:24-5:00','{"easy": {"fast": 264, "slow": 300}, "marathon": {"fast": 238, "slow": 258}, "threshold": {"fast": 225, "slow": 243}, "interval": {"fast": 209, "slow": 225}, "rep": {"fast": 198, "slow": 214}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;
INSERT INTO pace_levels (id,label,paces) VALUES (9,'輕鬆 4:02-4:38','{"easy": {"fast": 242, "slow": 278}, "marathon": {"fast": 219, "slow": 239}, "threshold": {"fast": 207, "slow": 225}, "interval": {"fast": 192, "slow": 208}, "rep": {"fast": 182, "slow": 198}}'::jsonb) ON CONFLICT (id) DO UPDATE SET label=EXCLUDED.label, paces=EXCLUDED.paces;

INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('recovery','恢復跑','recovery','極輕鬆、促進恢復，全程輕鬆配速。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "恢復跑", "effort": "easy", "target_type": "distance", "target": 4000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,1) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('easy','輕鬆跑','easy','有氧基礎，輕鬆對話配速。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "輕鬆跑", "effort": "easy", "target_type": "distance", "target": 6000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,2) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('lsd','LSD 長距離','lsd','長距離慢跑，建立耐力基礎。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑", "effort": "easy", "target_type": "distance", "target": 16000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,3) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('tempo','節奏跑','tempo','馬拉松配速持續跑，練節奏與效率。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "節奏(馬拉松配速)", "effort": "marathon", "target_type": "distance", "target": 8000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,4) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('threshold','乳酸閾值跑','threshold','閾值配速持續 20 分鐘，提升乳酸耐受。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "閾值持續 20 分", "effort": "threshold", "target_type": "time", "target": 1200}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,5) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('progression','漸進跑','progression','由輕鬆漸進到閾值，尾段加速。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "輕鬆", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "馬拉松配速", "effort": "marathon", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "閾值", "effort": "threshold", "target_type": "distance", "target": 2000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,6) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_400','間歇 400×8','interval','VO2max 短間歇，400m×8。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "400m 間歇", "effort": "interval", "target_type": "distance", "target": 400, "reps": 8, "rest_s": 90}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,7) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_800','間歇 800×5','interval','VO2max 間歇，800m×5。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "800m 間歇", "effort": "interval", "target_type": "distance", "target": 800, "reps": 5, "rest_s": 150}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,8) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_1000','間歇 1000×5','interval','VO2max 間歇，1000m×5。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "1000m 間歇", "effort": "interval", "target_type": "distance", "target": 1000, "reps": 5, "rest_s": 180}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,9) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_1200','間歇 1200×4','interval','VO2max 間歇，1200m×4。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "1200m 間歇", "effort": "interval", "target_type": "distance", "target": 1200, "reps": 4, "rest_s": 180}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,10) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_1600','間歇 1600×4','interval','較長間歇，1600m×4。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "1600m 間歇", "effort": "interval", "target_type": "distance", "target": 1600, "reps": 4, "rest_s": 150}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,11) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('int_2000','間歇 2000×3','interval','長間歇，2000m×3。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "2000m 間歇", "effort": "interval", "target_type": "distance", "target": 2000, "reps": 3, "rest_s": 180}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,12) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('fartlek','法特萊克變速跑','fartlek','快慢交替變速跑，60 秒快 / 60 秒緩 ×10。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "變速快段", "effort": "interval", "target_type": "time", "target": 60, "reps": 10, "rest_s": 60}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,13) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('pyramid','金字塔訓練','pyramid','400→800→1200→1600→1200→800→400，組間恢復。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "400m", "effort": "interval", "target_type": "distance", "target": 400}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 150}, {"kind": "work", "label": "800m", "effort": "interval", "target_type": "distance", "target": 800}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 150}, {"kind": "work", "label": "1200m", "effort": "interval", "target_type": "distance", "target": 1200}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 180}, {"kind": "work", "label": "1600m", "effort": "interval", "target_type": "distance", "target": 1600}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 180}, {"kind": "work", "label": "1200m", "effort": "interval", "target_type": "distance", "target": 1200}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 150}, {"kind": "work", "label": "800m", "effort": "interval", "target_type": "distance", "target": 800}, {"kind": "recovery", "label": "組間恢復", "effort": "easy", "target_type": "time", "target": 150}, {"kind": "work", "label": "400m", "effort": "interval", "target_type": "distance", "target": 400}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,14) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('norwegian','挪威 4×4','norwegian','4 分鐘高強度 ×4，組間 3 分鐘恢復。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "4 分鐘高強度", "effort": "interval", "target_type": "time", "target": 240, "reps": 4, "rest_s": 180}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,15) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('yasso','亞索 800','yasso','800m×10（馬拉松預測課表），組間等時慢跑。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "800m", "effort": "interval", "target_type": "distance", "target": 800, "reps": 10, "rest_s": 180}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,16) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order) VALUES ('rep_200','重複跑 200×10','rep','短快重複跑，練跑步經濟性，200m×10。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 2000}, {"kind": "work", "label": "200m 重複", "effort": "rep", "target_type": "distance", "target": 200, "reps": 10, "rest_s": 120}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,17) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description, segments=EXCLUDED.segments, sort_order=EXCLUDED.sort_order;

INSERT INTO app_settings (key, value) VALUES
  ('training_entry_state', 'whitelist'),
  ('training_entry_whitelist', 'sogobaga@gmail.com')
ON CONFLICT (key) DO NOTHING;

INSERT INTO schema_migrations (version) VALUES ('082') ON CONFLICT DO NOTHING;
