-- Migration 084: 自主訓練 P3 —— 訓練計畫(課表組,最多3) + 每日可多份課表 + 產生器用距離變體課表

-- 1) workout_templates 加 library_visible：距離變體不進「課表庫」清單，只給產生器排 + 前端解析用
ALTER TABLE workout_templates ADD COLUMN IF NOT EXISTS library_visible BOOLEAN NOT NULL DEFAULT TRUE;

-- 2) training_plans：一鍵產生的訓練計畫(每帳號最多 3，後端把關)
CREATE TABLE IF NOT EXISTS training_plans (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL,
  name          TEXT NOT NULL,
  race_date     DATE,
  race_distance TEXT,                 -- 5k|10k|half|full|''
  weeks         INT  NOT NULL DEFAULT 0,
  days_per_week INT  NOT NULL DEFAULT 0,
  pace_level    INT  NOT NULL DEFAULT 5,
  start_date    DATE NOT NULL,
  end_date      DATE NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_training_plans_user ON training_plans(user_id, created_at);

-- 3) user_training_schedule 改「一天可多份」：新增 id 主鍵 + plan_id(NULL=手動排；有值=某計畫，計畫刪除連帶刪)
ALTER TABLE user_training_schedule ADD COLUMN IF NOT EXISTS id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE user_training_schedule ADD COLUMN IF NOT EXISTS plan_id UUID REFERENCES training_plans(id) ON DELETE CASCADE;
ALTER TABLE user_training_schedule DROP CONSTRAINT IF EXISTS user_training_schedule_pkey;
ALTER TABLE user_training_schedule ADD PRIMARY KEY (id);

-- 4) 產生器用的距離變體課表(LSD/輕鬆各長度；library_visible=FALSE 不進課表庫清單)
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_6','LSD 6K 長距離','lsd','長距離慢跑主課 6 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 6K", "effort": "easy", "target_type": "distance", "target": 6000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,100,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_8','LSD 8K 長距離','lsd','長距離慢跑主課 8 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 8K", "effort": "easy", "target_type": "distance", "target": 8000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,101,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_10','LSD 10K 長距離','lsd','長距離慢跑主課 10 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 10K", "effort": "easy", "target_type": "distance", "target": 10000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,102,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_12','LSD 12K 長距離','lsd','長距離慢跑主課 12 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 12K", "effort": "easy", "target_type": "distance", "target": 12000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,103,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_14','LSD 14K 長距離','lsd','長距離慢跑主課 14 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 14K", "effort": "easy", "target_type": "distance", "target": 14000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,104,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_18','LSD 18K 長距離','lsd','長距離慢跑主課 18 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 18K", "effort": "easy", "target_type": "distance", "target": 18000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,105,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_20','LSD 20K 長距離','lsd','長距離慢跑主課 20 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 20K", "effort": "easy", "target_type": "distance", "target": 20000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,106,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_22','LSD 22K 長距離','lsd','長距離慢跑主課 22 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 22K", "effort": "easy", "target_type": "distance", "target": 22000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,107,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_24','LSD 24K 長距離','lsd','長距離慢跑主課 24 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 24K", "effort": "easy", "target_type": "distance", "target": 24000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,108,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_28','LSD 28K 長距離','lsd','長距離慢跑主課 28 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 28K", "effort": "easy", "target_type": "distance", "target": 28000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,109,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('lsd_32','LSD 32K 長距離','lsd','長距離慢跑主課 32 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "長距離慢跑 32K", "effort": "easy", "target_type": "distance", "target": 32000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,110,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('easy_4','輕鬆跑 4K','easy','輕鬆跑主課 4 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "輕鬆跑 4K", "effort": "easy", "target_type": "distance", "target": 4000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,111,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('easy_8','輕鬆跑 8K','easy','輕鬆跑主課 8 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "輕鬆跑 8K", "effort": "easy", "target_type": "distance", "target": 8000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,112,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;
INSERT INTO workout_templates (code,name,category,description,segments,sort_order,library_visible) VALUES ('easy_10','輕鬆跑 10K','easy','輕鬆跑主課 10 公里（產生器用）。','[{"kind": "warmup", "label": "熱身", "effort": "easy", "target_type": "distance", "target": 1000}, {"kind": "work", "label": "輕鬆跑 10K", "effort": "easy", "target_type": "distance", "target": 10000}, {"kind": "cooldown", "label": "恢復緩和", "effort": "easy", "target_type": "distance", "target": 1000}]'::jsonb,113,FALSE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,segments=EXCLUDED.segments,sort_order=EXCLUDED.sort_order,library_visible=FALSE;

INSERT INTO schema_migrations (version) VALUES ('084') ON CONFLICT DO NOTHING;
