-- 183_rpg_weapons_elements.sql
-- DORPG P7：武器系統＋怪物體型／屬性實裝（契約見
-- scratchpad/dorpg_p7/{CONTRACT.md,WIRE.md}）。本檔只建表／加索引；18 種武器類型＋390 件武器的
-- seed 由另一個 Workflow 產生，貼進下方兩對標記之間（刻意放在兩張表都建好之後，seed 才有表可插）。
--
-- ⚠️ 使用者手動套用到 Neon，不得自行套用；全部 CREATE TABLE IF NOT EXISTS，seed 一律
-- ON CONFLICT (id) DO NOTHING，可安全重複執行。依規範（db-before-code-push.md）等使用者確認已
-- 套用才能 push 依賴這些新表的程式碼——content_repo.go 對「表不存在」(42P01) 有 isMissingRelation
-- 優雅降級成 503，但這是全新表，不像 180 那批「既有表加欄位」有 42703 風險。
--
-- 怪物體型（大/中/小）與屬性（金/木/水/火/土/光/闇）欄位本輪不需要新增：rpg_monsters.attribute/
-- size 從 migration 176 就已存在（見 internal/rpg/content.go 檔頭「攻擊屬性 A 對怪物屬性 M」相關
-- 註解），過去只當純顯示文字；本檔起 internal/rpg/elements.go 的 ElementMultiplier() 真的讀它們
-- 進戰鬥公式，資料庫結構完全不用動。

-- ---------------------------------------------------------------------------
-- 1) rpg_weapon_types：18 種武器類型（六職業 × 三種，CONTRACT §2）。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS rpg_weapon_types (
  id                TEXT PRIMARY KEY,   -- lk_sword/lk_dual/lk_rapier/ar_longbow/ar_shortbow/ar_crossbow/
                                         -- mg_staff/mg_rod/mg_book/cl_staff/cl_book/cl_chain/
                                         -- mc_hammer/mc_mallet/mc_club/hk_greatsword/hk_spear/hk_axe
  job_id            TEXT NOT NULL REFERENCES rpg_jobs(id),
  name              TEXT NOT NULL,                     -- 單手劍/雙劍/細劍/長弓/…
  visual            TEXT NOT NULL DEFAULT 'sword',      -- sword|staff|bow|greatsword（既有四套 FX）
  elemental_capable BOOLEAN NOT NULL DEFAULT FALSE,     -- 這個類型是否另設一組七屬性版本（lk_sword/ar_shortbow/hk_spear=true）
  description       TEXT NOT NULL DEFAULT '',
  traits            JSONB NOT NULL DEFAULT '{}',        -- 型別層固定特性，純供顯示/設計依據，引擎不直接消費
  sort_order        INT NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 2) rpg_weapons：每個類型 10 級（有屬性版的類型另 10 級 × 7 屬性）。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS rpg_weapons (
  id            TEXT PRIMARY KEY,               -- <type>_t<tier> 或 <type>_t<tier>_<element>
  type_id       TEXT NOT NULL REFERENCES rpg_weapon_types(id),
  tier          INT NOT NULL CHECK (tier BETWEEN 1 AND 10),
  name          TEXT NOT NULL,
  rarity        TEXT NOT NULL DEFAULT 'common', -- common(t1-3)|rare(t4-6)|epic(t7-9)|legendary(t10)
  level_req     INT NOT NULL DEFAULT 1,         -- tier→1/10/20/30/40/50/60/70/80/90
  element       TEXT NOT NULL DEFAULT 'neutral', -- neutral 或七屬性英文代碼（metal/wood/water/fire/earth/light/dark）
  profile       JSONB NOT NULL DEFAULT '{}',    -- WeaponProfile，見 internal/rpg/weapons.go；缺欄位＝中性值
  description   TEXT NOT NULL DEFAULT '',
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rpg_weapons_type_tier ON rpg_weapons(type_id, tier);

-- >>> WEAPONS SEED (generated) >>>
-- DORPG P7：rpg_weapon_types (18) + rpg_weapons (390)
-- 產生自 scratchpad/dorpg_p7/weapons_all.json（已通過 validate_weapons.py）

INSERT INTO rpg_weapon_types (id, job_id, name, visual, elemental_capable, description, traits, sort_order)
VALUES
  ('lk_sword', 'light_knight', '單手劍', 'sword', TRUE, '攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', '{"positioning":"物理攻擊力","style":"均衡輸出","elemental_capable":true,"special":"屬性版額外提供魔法攻擊力加成（matk 由 4 隨等級成長至 40）"}'::jsonb, 1),
  ('lk_dual', 'light_knight', '雙劍', 'sword', FALSE, '雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', '{"positioning":"物理攻擊力","style":"二刀流","hits":2,"hit_mul":0.6,"special":"總傷害期望值約為單段攻擊的 120%，但雙段各自獨立判定 miss／暴擊，變異度較高"}'::jsonb, 2),
  ('lk_rapier', 'light_knight', '細劍', 'sword', FALSE, '劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', '{"positioning":"物理攻擊力","style":"攻速型","interval_pct_by_rarity":{"common":-6,"rare":-10,"epic":-14,"legendary":-20},"size_bonus":{"small":5},"special":"稀有度越高攻擊間隔縮短越多，對小型怪物 +5% 傷害"}'::jsonb, 3),
  ('ar_longbow', 'archer', '長弓', 'bow', FALSE, '蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', '{"positioning":"物理攻擊力","style":"重擊型","interval_pct":20,"crit_dmg_pct_range":[5,15],"size_bonus":{"large":5},"special":"攻擊間隔拉長換取高爆擊傷害，對大型怪物 +5% 傷害"}'::jsonb, 4),
  ('ar_shortbow', 'archer', '短弓', 'bow', TRUE, '輕巧好操作、出手極快，並附加迴避率加成。', '{"positioning":"物理攻擊力","style":"速射型","interval_pct":-10,"flee_bonus_range":[3,12],"elemental_capable":true,"special":"出手極快、附加迴避率加成"}'::jsonb, 5),
  ('ar_crossbow', 'archer', '弩', 'bow', FALSE, '扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', '{"positioning":"物理攻擊力","style":"極速型","interval_pct":-25,"crit_dmg_pct_range":[8,20],"special":"全弓種最短攻擊間隔，換取更高爆擊傷害"}'::jsonb, 6),
  ('mg_staff', 'mage', '杖', 'staff', FALSE, '魔法師專用權杖，內建節拍器般的訊號迴路，額外增幅智力與魔力上限，是續航型法系武器的基本款。', '{"role":"續航系法杖，主攻資源與屬性成長","primary_stat":"matk","matk_coefficient":1.0,"growth":{"int_bonus":[2,12],"mp_pct_low_high":[5,20]},"flavor_note":"杖身鑲嵌訊號石，越高階越能穩定放大智力與魔力儲備。"}'::jsonb, 1),
  ('mg_rod', 'mage', '棍', 'staff', FALSE, '魔法師專用短棍，導入城市電網過載的能量迴路，直接放大魔法攻擊力輸出。', '{"role":"輸出系法棍，主攻魔法攻擊力百分比成長","primary_stat":"matk","matk_coefficient":1.0,"growth":{"matk_pct_low_high":[5,20]},"flavor_note":"棍身導電材質隨等級提升，魔攻加成越發顯著。"}'::jsonb, 2),
  ('mg_book', 'mage', '書', 'staff', FALSE, '記錄城市熱島效應觀測資料的法術手冊，魔攻略遜於杖棍，但能穩定強化魔法技能效果。', '{"role":"技能強化型法書，犧牲部分魔攻換取技能效果加成","primary_stat":"matk","matk_coefficient":0.85,"growth":{"magic_skill_pct_fixed":5},"flavor_note":"書頁夾滿觀測筆記，翻閱間讓每個法術系數再往上推一點。"}'::jsonb, 3),
  ('cl_staff', 'cleric', '杖', 'staff', FALSE, '聖職者專用權杖，如隨身急救箱般延伸，額外增加智力與魔力上限，供長時間支援隊友使用。', '{"role":"續航系聖杖，主攻資源與屬性成長","primary_stat":"matk","matk_coefficient":1.0,"growth":{"int_bonus":[2,12],"mp_pct_low_high":[5,20]},"flavor_note":"杖頭纏繞如繃帶的織帶，越高階越能撐住更長的治療節奏。"}'::jsonb, 1),
  ('cl_book', 'cleric', '書', 'staff', FALSE, '記載補給站陣線佈署要領的隨身手冊，魔攻略遜於杖鍊，但能穩定強化魔法技能效果。', '{"role":"技能強化型聖書，犧牲部分魔攻換取技能效果加成","primary_stat":"matk","matk_coefficient":0.85,"growth":{"magic_skill_pct_fixed":5},"flavor_note":"書頁邊角寫滿補給站佈點筆記，翻開就能讓治療與增益更扎實一分。"}'::jsonb, 2),
  ('cl_chain', 'cleric', '鍊', 'staff', FALSE, '由運動貼紮術延伸出的護具鍊，強化魔法抗性並提升魔法防禦，是防護型聖職者的首選。', '{"role":"防護系聖鍊，主攻屬性減免與魔防成長","primary_stat":"matk","matk_coefficient":1.0,"growth":{"element_resist_pct_low_high":[5,25],"mdef_pct_low_high":[5,15]},"flavor_note":"鍊環間穿著護具貼布，能把屬性傷害的衝擊層層卸掉。"}'::jsonb, 3),
  ('mc_hammer', 'merchant', '錘', 'sword', FALSE, '商人秤重用的實心秤錘，掄起來格外沉手，大幅提升爆擊傷害，對大體型的對手特別有效。', '{"role":"爆擊系商用錘，主攻爆擊傷害成長","primary_stat":"atk","atk_coefficient":1.0,"growth":{"crit_dmg_pct_low_high":[5,20]},"size_bonus":{"large":5},"flavor_note":"秤錘越重，砸中要害時的傷害翻倍效果也越明顯。"}'::jsonb, 1),
  ('mc_mallet', 'merchant', '槌', 'sword', FALSE, '夜市叫賣時敲擊招牌用的木槌，敲得越響、力道越足，物理攻擊力額外提升，對大體型的對手特別有效。', '{"role":"輸出系商用槌，主攻物理攻擊力百分比成長","primary_stat":"atk","atk_coefficient":1.0,"growth":{"atk_pct_low_high":[5,15]},"size_bonus":{"large":5},"flavor_note":"槌頭包覆的皮革隨等級升級，捶擊力道跟著水漲船高。"}'::jsonb, 2),
  ('mc_club', 'merchant', '棒', 'sword', FALSE, '顧攤蹲點時用來撐場面的木棒，扎實好握，額外提升物理防禦力，對大體型的對手特別有效。', '{"role":"防護系商用棒，主攻物理防禦力百分比成長","primary_stat":"atk","atk_coefficient":1.0,"growth":{"def_pct_low_high":[5,15]},"size_bonus":{"large":5},"flavor_note":"棒身刻滿顧攤多年的防身心得，扛得住的攻勢也越來越多。"}'::jsonb, 3),
  ('hk_greatsword', 'heavy_knight', '巨劍', 'greatsword', FALSE, '揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', '{"positioning":"物理攻擊力","style":"蓄力型","charge_time_mul":1.5,"charge_dmg_mul_range":[1.6,2.0],"size_bonus":{"large":5},"special":"蓄力時間拉長為 1.5 倍，蓄力後傷害大幅提升，對大型怪物 +5% 傷害"}'::jsonb, 7),
  ('hk_spear', 'heavy_knight', '槍', 'greatsword', TRUE, '槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', '{"positioning":"物理攻擊力","style":"連擊型","hits":2,"hit_mul":0.5,"crit_pct_range":[3,10],"crit_dmg_pct_range":[5,15],"extra_hit_chance_pct_range":[10,30],"elemental_capable":true,"special":"普攻固定兩段各 50% 傷害，並有機率追加第三段（10%→30%）"}'::jsonb, 8),
  ('hk_axe', 'heavy_knight', '斧', 'greatsword', FALSE, '掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', '{"positioning":"物理攻擊力","style":"範圍型","interval_pct":25,"splash_pct":40,"size_bonus":{"large":5},"special":"攻擊間隔變長，對主目標左右相鄰怪物造成 40% 濺射傷害，對大型怪物 +5% 傷害"}'::jsonb, 9)
ON CONFLICT (id) DO UPDATE SET
  job_id = EXCLUDED.job_id,
  name = EXCLUDED.name,
  visual = EXCLUDED.visual,
  elemental_capable = EXCLUDED.elemental_capable,
  description = EXCLUDED.description,
  traits = EXCLUDED.traits,
  sort_order = EXCLUDED.sort_order;

INSERT INTO rpg_weapons (id, type_id, tier, name, rarity, level_req, element, profile, description, is_active, sort_order)
VALUES
  ('lk_sword_t1', 'lk_sword', 1, '社區慢跑劍', 'common', 1, 'neutral', '{"atk":7,"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 100),
  ('lk_sword_t1_metal', 'lk_sword', 1, '社區慢跑劍‧鋼', 'common', 1, 'metal', '{"atk":7,"element":"metal","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 101),
  ('lk_sword_t1_wood', 'lk_sword', 1, '社區慢跑劍‧森', 'common', 1, 'wood', '{"atk":7,"element":"wood","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 102),
  ('lk_sword_t1_water', 'lk_sword', 1, '社區慢跑劍‧霜', 'common', 1, 'water', '{"atk":7,"element":"water","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 103),
  ('lk_sword_t1_fire', 'lk_sword', 1, '社區慢跑劍‧焰', 'common', 1, 'fire', '{"atk":7,"element":"fire","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 104),
  ('lk_sword_t1_earth', 'lk_sword', 1, '社區慢跑劍‧岩', 'common', 1, 'earth', '{"atk":7,"element":"earth","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 105),
  ('lk_sword_t1_light', 'lk_sword', 1, '社區慢跑劍‧曜', 'common', 1, 'light', '{"atk":7,"element":"light","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 106),
  ('lk_sword_t1_dark', 'lk_sword', 1, '社區慢跑劍‧影', 'common', 1, 'dark', '{"atk":7,"element":"dark","matk":4}'::jsonb, '社區晨跑團的入門配備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 107),
  ('lk_sword_t2', 'lk_sword', 2, '河濱晨跑劍', 'common', 10, 'neutral', '{"atk":16,"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 200),
  ('lk_sword_t2_metal', 'lk_sword', 2, '河濱晨跑劍‧鋼', 'common', 10, 'metal', '{"atk":16,"element":"metal","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 201),
  ('lk_sword_t2_wood', 'lk_sword', 2, '河濱晨跑劍‧森', 'common', 10, 'wood', '{"atk":16,"element":"wood","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 202),
  ('lk_sword_t2_water', 'lk_sword', 2, '河濱晨跑劍‧霜', 'common', 10, 'water', '{"atk":16,"element":"water","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 203),
  ('lk_sword_t2_fire', 'lk_sword', 2, '河濱晨跑劍‧焰', 'common', 10, 'fire', '{"atk":16,"element":"fire","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 204),
  ('lk_sword_t2_earth', 'lk_sword', 2, '河濱晨跑劍‧岩', 'common', 10, 'earth', '{"atk":16,"element":"earth","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 205),
  ('lk_sword_t2_light', 'lk_sword', 2, '河濱晨跑劍‧曜', 'common', 10, 'light', '{"atk":16,"element":"light","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 206),
  ('lk_sword_t2_dark', 'lk_sword', 2, '河濱晨跑劍‧影', 'common', 10, 'dark', '{"atk":16,"element":"dark","matk":8}'::jsonb, '河濱步道晨練老手愛用，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 207),
  ('lk_sword_t3', 'lk_sword', 3, '街角路跑劍', 'common', 20, 'neutral', '{"atk":24,"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 300),
  ('lk_sword_t3_metal', 'lk_sword', 3, '街角路跑劍‧鋼', 'common', 20, 'metal', '{"atk":24,"element":"metal","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 301),
  ('lk_sword_t3_wood', 'lk_sword', 3, '街角路跑劍‧森', 'common', 20, 'wood', '{"atk":24,"element":"wood","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 302),
  ('lk_sword_t3_water', 'lk_sword', 3, '街角路跑劍‧霜', 'common', 20, 'water', '{"atk":24,"element":"water","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 303),
  ('lk_sword_t3_fire', 'lk_sword', 3, '街角路跑劍‧焰', 'common', 20, 'fire', '{"atk":24,"element":"fire","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 304),
  ('lk_sword_t3_earth', 'lk_sword', 3, '街角路跑劍‧岩', 'common', 20, 'earth', '{"atk":24,"element":"earth","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 305),
  ('lk_sword_t3_light', 'lk_sword', 3, '街角路跑劍‧曜', 'common', 20, 'light', '{"atk":24,"element":"light","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 306),
  ('lk_sword_t3_dark', 'lk_sword', 3, '街角路跑劍‧影', 'common', 20, 'dark', '{"atk":24,"element":"dark","matk":12}'::jsonb, '假日路跑賽事的常勝夥伴，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 307),
  ('lk_sword_t4', 'lk_sword', 4, '夜騎巡邏劍', 'rare', 30, 'neutral', '{"atk":32,"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 400),
  ('lk_sword_t4_metal', 'lk_sword', 4, '夜騎巡邏劍‧鋼', 'rare', 30, 'metal', '{"atk":32,"element":"metal","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 401),
  ('lk_sword_t4_wood', 'lk_sword', 4, '夜騎巡邏劍‧森', 'rare', 30, 'wood', '{"atk":32,"element":"wood","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 402),
  ('lk_sword_t4_water', 'lk_sword', 4, '夜騎巡邏劍‧霜', 'rare', 30, 'water', '{"atk":32,"element":"water","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 403),
  ('lk_sword_t4_fire', 'lk_sword', 4, '夜騎巡邏劍‧焰', 'rare', 30, 'fire', '{"atk":32,"element":"fire","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 404),
  ('lk_sword_t4_earth', 'lk_sword', 4, '夜騎巡邏劍‧岩', 'rare', 30, 'earth', '{"atk":32,"element":"earth","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 405),
  ('lk_sword_t4_light', 'lk_sword', 4, '夜騎巡邏劍‧曜', 'rare', 30, 'light', '{"atk":32,"element":"light","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 406),
  ('lk_sword_t4_dark', 'lk_sword', 4, '夜騎巡邏劍‧影', 'rare', 30, 'dark', '{"atk":32,"element":"dark","matk":16}'::jsonb, '夜跑俱樂部指定強化款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 407),
  ('lk_sword_t5', 'lk_sword', 5, '半馬競速劍', 'rare', 40, 'neutral', '{"atk":44,"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 500),
  ('lk_sword_t5_metal', 'lk_sword', 5, '半馬競速劍‧鋼', 'rare', 40, 'metal', '{"atk":44,"element":"metal","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 501),
  ('lk_sword_t5_wood', 'lk_sword', 5, '半馬競速劍‧森', 'rare', 40, 'wood', '{"atk":44,"element":"wood","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 502),
  ('lk_sword_t5_water', 'lk_sword', 5, '半馬競速劍‧霜', 'rare', 40, 'water', '{"atk":44,"element":"water","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 503),
  ('lk_sword_t5_fire', 'lk_sword', 5, '半馬競速劍‧焰', 'rare', 40, 'fire', '{"atk":44,"element":"fire","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 504),
  ('lk_sword_t5_earth', 'lk_sword', 5, '半馬競速劍‧岩', 'rare', 40, 'earth', '{"atk":44,"element":"earth","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 505),
  ('lk_sword_t5_light', 'lk_sword', 5, '半馬競速劍‧曜', 'rare', 40, 'light', '{"atk":44,"element":"light","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 506),
  ('lk_sword_t5_dark', 'lk_sword', 5, '半馬競速劍‧影', 'rare', 40, 'dark', '{"atk":44,"element":"dark","matk":20}'::jsonb, '半程馬拉松選手信賴之選，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 507),
  ('lk_sword_t6', 'lk_sword', 6, '全馬破風劍', 'rare', 50, 'neutral', '{"atk":50,"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 600),
  ('lk_sword_t6_metal', 'lk_sword', 6, '全馬破風劍‧鋼', 'rare', 50, 'metal', '{"atk":50,"element":"metal","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 601),
  ('lk_sword_t6_wood', 'lk_sword', 6, '全馬破風劍‧森', 'rare', 50, 'wood', '{"atk":50,"element":"wood","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 602),
  ('lk_sword_t6_water', 'lk_sword', 6, '全馬破風劍‧霜', 'rare', 50, 'water', '{"atk":50,"element":"water","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 603),
  ('lk_sword_t6_fire', 'lk_sword', 6, '全馬破風劍‧焰', 'rare', 50, 'fire', '{"atk":50,"element":"fire","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 604),
  ('lk_sword_t6_earth', 'lk_sword', 6, '全馬破風劍‧岩', 'rare', 50, 'earth', '{"atk":50,"element":"earth","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 605),
  ('lk_sword_t6_light', 'lk_sword', 6, '全馬破風劍‧曜', 'rare', 50, 'light', '{"atk":50,"element":"light","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 606),
  ('lk_sword_t6_dark', 'lk_sword', 6, '全馬破風劍‧影', 'rare', 50, 'dark', '{"atk":50,"element":"dark","matk":24}'::jsonb, '全程馬拉松賽場的主力裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 607),
  ('lk_sword_t7', 'lk_sword', 7, '城市先鋒劍', 'epic', 60, 'neutral', '{"atk":64,"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 700),
  ('lk_sword_t7_metal', 'lk_sword', 7, '城市先鋒劍‧鋼', 'epic', 60, 'metal', '{"atk":64,"element":"metal","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 701),
  ('lk_sword_t7_wood', 'lk_sword', 7, '城市先鋒劍‧森', 'epic', 60, 'wood', '{"atk":64,"element":"wood","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 702),
  ('lk_sword_t7_water', 'lk_sword', 7, '城市先鋒劍‧霜', 'epic', 60, 'water', '{"atk":64,"element":"water","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 703),
  ('lk_sword_t7_fire', 'lk_sword', 7, '城市先鋒劍‧焰', 'epic', 60, 'fire', '{"atk":64,"element":"fire","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 704),
  ('lk_sword_t7_earth', 'lk_sword', 7, '城市先鋒劍‧岩', 'epic', 60, 'earth', '{"atk":64,"element":"earth","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 705),
  ('lk_sword_t7_light', 'lk_sword', 7, '城市先鋒劍‧曜', 'epic', 60, 'light', '{"atk":64,"element":"light","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 706),
  ('lk_sword_t7_dark', 'lk_sword', 7, '城市先鋒劍‧影', 'epic', 60, 'dark', '{"atk":64,"element":"dark","matk":28}'::jsonb, '城市巡迴賽冠軍愛用款，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 707),
  ('lk_sword_t8', 'lk_sword', 8, '極限配速劍', 'epic', 70, 'neutral', '{"atk":72,"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 800),
  ('lk_sword_t8_metal', 'lk_sword', 8, '極限配速劍‧鋼', 'epic', 70, 'metal', '{"atk":72,"element":"metal","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 801),
  ('lk_sword_t8_wood', 'lk_sword', 8, '極限配速劍‧森', 'epic', 70, 'wood', '{"atk":72,"element":"wood","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 802),
  ('lk_sword_t8_water', 'lk_sword', 8, '極限配速劍‧霜', 'epic', 70, 'water', '{"atk":72,"element":"water","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 803),
  ('lk_sword_t8_fire', 'lk_sword', 8, '極限配速劍‧焰', 'epic', 70, 'fire', '{"atk":72,"element":"fire","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 804),
  ('lk_sword_t8_earth', 'lk_sword', 8, '極限配速劍‧岩', 'epic', 70, 'earth', '{"atk":72,"element":"earth","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 805),
  ('lk_sword_t8_light', 'lk_sword', 8, '極限配速劍‧曜', 'epic', 70, 'light', '{"atk":72,"element":"light","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 806),
  ('lk_sword_t8_dark', 'lk_sword', 8, '極限配速劍‧影', 'epic', 70, 'dark', '{"atk":72,"element":"dark","matk":32}'::jsonb, '極限配速挑戰者專屬，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 807),
  ('lk_sword_t9', 'lk_sword', 9, '巡迴賽御劍', 'epic', 80, 'neutral', '{"atk":87,"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 900),
  ('lk_sword_t9_metal', 'lk_sword', 9, '巡迴賽御劍‧鋼', 'epic', 80, 'metal', '{"atk":87,"element":"metal","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 901),
  ('lk_sword_t9_wood', 'lk_sword', 9, '巡迴賽御劍‧森', 'epic', 80, 'wood', '{"atk":87,"element":"wood","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 902),
  ('lk_sword_t9_water', 'lk_sword', 9, '巡迴賽御劍‧霜', 'epic', 80, 'water', '{"atk":87,"element":"water","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 903),
  ('lk_sword_t9_fire', 'lk_sword', 9, '巡迴賽御劍‧焰', 'epic', 80, 'fire', '{"atk":87,"element":"fire","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 904),
  ('lk_sword_t9_earth', 'lk_sword', 9, '巡迴賽御劍‧岩', 'epic', 80, 'earth', '{"atk":87,"element":"earth","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 905),
  ('lk_sword_t9_light', 'lk_sword', 9, '巡迴賽御劍‧曜', 'epic', 80, 'light', '{"atk":87,"element":"light","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 906),
  ('lk_sword_t9_dark', 'lk_sword', 9, '巡迴賽御劍‧影', 'epic', 80, 'dark', '{"atk":87,"element":"dark","matk":36}'::jsonb, '全國巡迴賽事的頂尖裝備，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 907),
  ('lk_sword_t10', 'lk_sword', 10, '無盡里程劍', 'legendary', 90, 'neutral', '{"atk":94,"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力。', TRUE, 1000),
  ('lk_sword_t10_metal', 'lk_sword', 10, '無盡里程劍‧鋼', 'legendary', 90, 'metal', '{"atk":94,"element":"metal","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1001),
  ('lk_sword_t10_wood', 'lk_sword', 10, '無盡里程劍‧森', 'legendary', 90, 'wood', '{"atk":94,"element":"wood","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1002),
  ('lk_sword_t10_water', 'lk_sword', 10, '無盡里程劍‧霜', 'legendary', 90, 'water', '{"atk":94,"element":"water","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1003),
  ('lk_sword_t10_fire', 'lk_sword', 10, '無盡里程劍‧焰', 'legendary', 90, 'fire', '{"atk":94,"element":"fire","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1004),
  ('lk_sword_t10_earth', 'lk_sword', 10, '無盡里程劍‧岩', 'legendary', 90, 'earth', '{"atk":94,"element":"earth","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1005),
  ('lk_sword_t10_light', 'lk_sword', 10, '無盡里程劍‧曜', 'legendary', 90, 'light', '{"atk":94,"element":"light","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1006),
  ('lk_sword_t10_dark', 'lk_sword', 10, '無盡里程劍‧影', 'legendary', 90, 'dark', '{"atk":94,"element":"dark","matk":40}'::jsonb, '傳說等級，只在最終賽場現身，攻守均衡的單手劍，部分稀有版本可額外提升魔法攻擊力，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1007),
  ('lk_dual_t1', 'lk_dual', 1, '雙格晨跑劍', 'common', 1, 'neutral', '{"atk":7,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 100),
  ('lk_dual_t2', 'lk_dual', 2, '雙軌河濱劍', 'common', 10, 'neutral', '{"atk":16,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 200),
  ('lk_dual_t3', 'lk_dual', 3, '交叉路跑劍', 'common', 20, 'neutral', '{"atk":24,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 300),
  ('lk_dual_t4', 'lk_dual', 4, '雙鋒夜巡劍', 'rare', 30, 'neutral', '{"atk":32,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 400),
  ('lk_dual_t5', 'lk_dual', 5, '雙速半馬劍', 'rare', 40, 'neutral', '{"atk":44,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 500),
  ('lk_dual_t6', 'lk_dual', 6, '雙擊全馬劍', 'rare', 50, 'neutral', '{"atk":50,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 600),
  ('lk_dual_t7', 'lk_dual', 7, '連斬先鋒劍', 'epic', 60, 'neutral', '{"atk":64,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 700),
  ('lk_dual_t8', 'lk_dual', 8, '雙影破風劍', 'epic', 70, 'neutral', '{"atk":72,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 800),
  ('lk_dual_t9', 'lk_dual', 9, '雙姿巡迴劍', 'epic', 80, 'neutral', '{"atk":87,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 900),
  ('lk_dual_t10', 'lk_dual', 10, '二刀流傳說劍', 'legendary', 90, 'neutral', '{"atk":94,"hits":2,"hit_mul":0.6,"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，雙劍在手化身二刀流，攻擊拆為兩段但每段威力僅有六成。', TRUE, 1000),
  ('lk_rapier_t1', 'lk_rapier', 1, '輕巧晨跑劍', 'common', 1, 'neutral', '{"atk":6,"interval_pct":-6,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 100),
  ('lk_rapier_t2', 'lk_rapier', 2, '疾刺河濱劍', 'common', 10, 'neutral', '{"atk":14,"interval_pct":-6,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 200),
  ('lk_rapier_t3', 'lk_rapier', 3, '迅捷路跑劍', 'common', 20, 'neutral', '{"atk":22,"interval_pct":-6,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 300),
  ('lk_rapier_t4', 'lk_rapier', 4, '銳影夜巡劍', 'rare', 30, 'neutral', '{"atk":29,"interval_pct":-10,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 400),
  ('lk_rapier_t5', 'lk_rapier', 5, '速影半馬劍', 'rare', 40, 'neutral', '{"atk":40,"interval_pct":-10,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 500),
  ('lk_rapier_t6', 'lk_rapier', 6, '疾風全馬劍', 'rare', 50, 'neutral', '{"atk":45,"interval_pct":-10,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 600),
  ('lk_rapier_t7', 'lk_rapier', 7, '影速先鋒劍', 'epic', 60, 'neutral', '{"atk":58,"interval_pct":-14,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 700),
  ('lk_rapier_t8', 'lk_rapier', 8, '極速破風劍', 'epic', 70, 'neutral', '{"atk":65,"interval_pct":-14,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 800),
  ('lk_rapier_t9', 'lk_rapier', 9, '瞬刺巡迴劍', 'epic', 80, 'neutral', '{"atk":78,"interval_pct":-14,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 900),
  ('lk_rapier_t10', 'lk_rapier', 10, '極限節奏劍', 'legendary', 90, 'neutral', '{"atk":85,"interval_pct":-20,"size_bonus":{"small":5,"medium":0,"large":0},"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，劍身輕薄利於快速出招，稀有度越高攻擊間隔縮短越多，對小型目標更有效。', TRUE, 1000),
  ('ar_longbow_t1', 'ar_longbow', 1, '社區練習弓', 'common', 1, 'neutral', '{"atk":9,"interval_pct":20,"crit_dmg_pct":5,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 100),
  ('ar_longbow_t2', 'ar_longbow', 2, '河濱瞄準弓', 'common', 10, 'neutral', '{"atk":20,"interval_pct":20,"crit_dmg_pct":6,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 200),
  ('ar_longbow_t3', 'ar_longbow', 3, '路跑蓄力弓', 'common', 20, 'neutral', '{"atk":30,"interval_pct":20,"crit_dmg_pct":7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 300),
  ('ar_longbow_t4', 'ar_longbow', 4, '夜巡狙擊弓', 'rare', 30, 'neutral', '{"atk":40,"interval_pct":20,"crit_dmg_pct":8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 400),
  ('ar_longbow_t5', 'ar_longbow', 5, '半馬強弓', 'rare', 40, 'neutral', '{"atk":55,"interval_pct":20,"crit_dmg_pct":9,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 500),
  ('ar_longbow_t6', 'ar_longbow', 6, '全馬重弓', 'rare', 50, 'neutral', '{"atk":63,"interval_pct":20,"crit_dmg_pct":11,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 600),
  ('ar_longbow_t7', 'ar_longbow', 7, '先鋒巨弓', 'epic', 60, 'neutral', '{"atk":80,"interval_pct":20,"crit_dmg_pct":12,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 700),
  ('ar_longbow_t8', 'ar_longbow', 8, '破風長弓', 'epic', 70, 'neutral', '{"atk":90,"interval_pct":20,"crit_dmg_pct":13,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 800),
  ('ar_longbow_t9', 'ar_longbow', 9, '巡迴獵弓', 'epic', 80, 'neutral', '{"atk":109,"interval_pct":20,"crit_dmg_pct":14,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 900),
  ('ar_longbow_t10', 'ar_longbow', 10, '傳說射程弓', 'legendary', 90, 'neutral', '{"atk":118,"interval_pct":20,"crit_dmg_pct":15,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，蓄力拉滿弓弦、攻擊間隔拉長但箭勁十足，並顯著提升爆擊傷害，克制大型目標。', TRUE, 1000),
  ('ar_shortbow_t1', 'ar_shortbow', 1, '社區速射弓', 'common', 1, 'neutral', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 100),
  ('ar_shortbow_t1_metal', 'ar_shortbow', 1, '社區速射弓‧鋼', 'common', 1, 'metal', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"metal"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 101),
  ('ar_shortbow_t1_wood', 'ar_shortbow', 1, '社區速射弓‧森', 'common', 1, 'wood', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"wood"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 102),
  ('ar_shortbow_t1_water', 'ar_shortbow', 1, '社區速射弓‧霜', 'common', 1, 'water', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"water"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 103),
  ('ar_shortbow_t1_fire', 'ar_shortbow', 1, '社區速射弓‧焰', 'common', 1, 'fire', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"fire"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 104),
  ('ar_shortbow_t1_earth', 'ar_shortbow', 1, '社區速射弓‧岩', 'common', 1, 'earth', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"earth"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 105),
  ('ar_shortbow_t1_light', 'ar_shortbow', 1, '社區速射弓‧曜', 'common', 1, 'light', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"light"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 106),
  ('ar_shortbow_t1_dark', 'ar_shortbow', 1, '社區速射弓‧影', 'common', 1, 'dark', '{"atk":7,"interval_pct":-10,"flee_bonus":3,"element":"dark"}'::jsonb, '社區晨跑團的入門配備，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 107),
  ('ar_shortbow_t2', 'ar_shortbow', 2, '河濱輕巧弓', 'common', 10, 'neutral', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 200),
  ('ar_shortbow_t2_metal', 'ar_shortbow', 2, '河濱輕巧弓‧鋼', 'common', 10, 'metal', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"metal"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 201),
  ('ar_shortbow_t2_wood', 'ar_shortbow', 2, '河濱輕巧弓‧森', 'common', 10, 'wood', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"wood"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 202),
  ('ar_shortbow_t2_water', 'ar_shortbow', 2, '河濱輕巧弓‧霜', 'common', 10, 'water', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"water"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 203),
  ('ar_shortbow_t2_fire', 'ar_shortbow', 2, '河濱輕巧弓‧焰', 'common', 10, 'fire', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"fire"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 204),
  ('ar_shortbow_t2_earth', 'ar_shortbow', 2, '河濱輕巧弓‧岩', 'common', 10, 'earth', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"earth"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 205),
  ('ar_shortbow_t2_light', 'ar_shortbow', 2, '河濱輕巧弓‧曜', 'common', 10, 'light', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"light"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 206),
  ('ar_shortbow_t2_dark', 'ar_shortbow', 2, '河濱輕巧弓‧影', 'common', 10, 'dark', '{"atk":16,"interval_pct":-10,"flee_bonus":4,"element":"dark"}'::jsonb, '河濱步道晨練老手愛用，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 207),
  ('ar_shortbow_t3', 'ar_shortbow', 3, '路跑靈巧弓', 'common', 20, 'neutral', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 300),
  ('ar_shortbow_t3_metal', 'ar_shortbow', 3, '路跑靈巧弓‧鋼', 'common', 20, 'metal', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"metal"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 301),
  ('ar_shortbow_t3_wood', 'ar_shortbow', 3, '路跑靈巧弓‧森', 'common', 20, 'wood', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"wood"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 302),
  ('ar_shortbow_t3_water', 'ar_shortbow', 3, '路跑靈巧弓‧霜', 'common', 20, 'water', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"water"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 303),
  ('ar_shortbow_t3_fire', 'ar_shortbow', 3, '路跑靈巧弓‧焰', 'common', 20, 'fire', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"fire"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 304),
  ('ar_shortbow_t3_earth', 'ar_shortbow', 3, '路跑靈巧弓‧岩', 'common', 20, 'earth', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"earth"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 305),
  ('ar_shortbow_t3_light', 'ar_shortbow', 3, '路跑靈巧弓‧曜', 'common', 20, 'light', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"light"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 306),
  ('ar_shortbow_t3_dark', 'ar_shortbow', 3, '路跑靈巧弓‧影', 'common', 20, 'dark', '{"atk":24,"interval_pct":-10,"flee_bonus":5,"element":"dark"}'::jsonb, '假日路跑賽事的常勝夥伴，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 307),
  ('ar_shortbow_t4', 'ar_shortbow', 4, '夜巡疾影弓', 'rare', 30, 'neutral', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 400),
  ('ar_shortbow_t4_metal', 'ar_shortbow', 4, '夜巡疾影弓‧鋼', 'rare', 30, 'metal', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"metal"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 401),
  ('ar_shortbow_t4_wood', 'ar_shortbow', 4, '夜巡疾影弓‧森', 'rare', 30, 'wood', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"wood"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 402),
  ('ar_shortbow_t4_water', 'ar_shortbow', 4, '夜巡疾影弓‧霜', 'rare', 30, 'water', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"water"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 403),
  ('ar_shortbow_t4_fire', 'ar_shortbow', 4, '夜巡疾影弓‧焰', 'rare', 30, 'fire', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"fire"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 404),
  ('ar_shortbow_t4_earth', 'ar_shortbow', 4, '夜巡疾影弓‧岩', 'rare', 30, 'earth', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"earth"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 405),
  ('ar_shortbow_t4_light', 'ar_shortbow', 4, '夜巡疾影弓‧曜', 'rare', 30, 'light', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"light"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 406),
  ('ar_shortbow_t4_dark', 'ar_shortbow', 4, '夜巡疾影弓‧影', 'rare', 30, 'dark', '{"atk":32,"interval_pct":-10,"flee_bonus":6,"element":"dark"}'::jsonb, '夜跑俱樂部指定強化款，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 407),
  ('ar_shortbow_t5', 'ar_shortbow', 5, '半馬迴身弓', 'rare', 40, 'neutral', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 500),
  ('ar_shortbow_t5_metal', 'ar_shortbow', 5, '半馬迴身弓‧鋼', 'rare', 40, 'metal', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"metal"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 501),
  ('ar_shortbow_t5_wood', 'ar_shortbow', 5, '半馬迴身弓‧森', 'rare', 40, 'wood', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"wood"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 502),
  ('ar_shortbow_t5_water', 'ar_shortbow', 5, '半馬迴身弓‧霜', 'rare', 40, 'water', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"water"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 503),
  ('ar_shortbow_t5_fire', 'ar_shortbow', 5, '半馬迴身弓‧焰', 'rare', 40, 'fire', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"fire"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 504),
  ('ar_shortbow_t5_earth', 'ar_shortbow', 5, '半馬迴身弓‧岩', 'rare', 40, 'earth', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"earth"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 505),
  ('ar_shortbow_t5_light', 'ar_shortbow', 5, '半馬迴身弓‧曜', 'rare', 40, 'light', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"light"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 506),
  ('ar_shortbow_t5_dark', 'ar_shortbow', 5, '半馬迴身弓‧影', 'rare', 40, 'dark', '{"atk":44,"interval_pct":-10,"flee_bonus":7,"element":"dark"}'::jsonb, '半程馬拉松選手信賴之選，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 507),
  ('ar_shortbow_t6', 'ar_shortbow', 6, '全馬遊擊弓', 'rare', 50, 'neutral', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 600),
  ('ar_shortbow_t6_metal', 'ar_shortbow', 6, '全馬遊擊弓‧鋼', 'rare', 50, 'metal', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"metal"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 601),
  ('ar_shortbow_t6_wood', 'ar_shortbow', 6, '全馬遊擊弓‧森', 'rare', 50, 'wood', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"wood"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 602),
  ('ar_shortbow_t6_water', 'ar_shortbow', 6, '全馬遊擊弓‧霜', 'rare', 50, 'water', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"water"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 603),
  ('ar_shortbow_t6_fire', 'ar_shortbow', 6, '全馬遊擊弓‧焰', 'rare', 50, 'fire', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"fire"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 604),
  ('ar_shortbow_t6_earth', 'ar_shortbow', 6, '全馬遊擊弓‧岩', 'rare', 50, 'earth', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"earth"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 605),
  ('ar_shortbow_t6_light', 'ar_shortbow', 6, '全馬遊擊弓‧曜', 'rare', 50, 'light', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"light"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 606),
  ('ar_shortbow_t6_dark', 'ar_shortbow', 6, '全馬遊擊弓‧影', 'rare', 50, 'dark', '{"atk":50,"interval_pct":-10,"flee_bonus":8,"element":"dark"}'::jsonb, '全程馬拉松賽場的主力裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 607),
  ('ar_shortbow_t7', 'ar_shortbow', 7, '先鋒穿梭弓', 'epic', 60, 'neutral', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 700),
  ('ar_shortbow_t7_metal', 'ar_shortbow', 7, '先鋒穿梭弓‧鋼', 'epic', 60, 'metal', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"metal"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 701),
  ('ar_shortbow_t7_wood', 'ar_shortbow', 7, '先鋒穿梭弓‧森', 'epic', 60, 'wood', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"wood"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 702),
  ('ar_shortbow_t7_water', 'ar_shortbow', 7, '先鋒穿梭弓‧霜', 'epic', 60, 'water', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"water"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 703),
  ('ar_shortbow_t7_fire', 'ar_shortbow', 7, '先鋒穿梭弓‧焰', 'epic', 60, 'fire', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"fire"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 704),
  ('ar_shortbow_t7_earth', 'ar_shortbow', 7, '先鋒穿梭弓‧岩', 'epic', 60, 'earth', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"earth"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 705),
  ('ar_shortbow_t7_light', 'ar_shortbow', 7, '先鋒穿梭弓‧曜', 'epic', 60, 'light', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"light"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 706),
  ('ar_shortbow_t7_dark', 'ar_shortbow', 7, '先鋒穿梭弓‧影', 'epic', 60, 'dark', '{"atk":64,"interval_pct":-10,"flee_bonus":9,"element":"dark"}'::jsonb, '城市巡迴賽冠軍愛用款，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 707),
  ('ar_shortbow_t8', 'ar_shortbow', 8, '破風閃避弓', 'epic', 70, 'neutral', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 800),
  ('ar_shortbow_t8_metal', 'ar_shortbow', 8, '破風閃避弓‧鋼', 'epic', 70, 'metal', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"metal"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 801),
  ('ar_shortbow_t8_wood', 'ar_shortbow', 8, '破風閃避弓‧森', 'epic', 70, 'wood', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"wood"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 802),
  ('ar_shortbow_t8_water', 'ar_shortbow', 8, '破風閃避弓‧霜', 'epic', 70, 'water', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"water"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 803),
  ('ar_shortbow_t8_fire', 'ar_shortbow', 8, '破風閃避弓‧焰', 'epic', 70, 'fire', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"fire"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 804),
  ('ar_shortbow_t8_earth', 'ar_shortbow', 8, '破風閃避弓‧岩', 'epic', 70, 'earth', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"earth"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 805),
  ('ar_shortbow_t8_light', 'ar_shortbow', 8, '破風閃避弓‧曜', 'epic', 70, 'light', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"light"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 806),
  ('ar_shortbow_t8_dark', 'ar_shortbow', 8, '破風閃避弓‧影', 'epic', 70, 'dark', '{"atk":72,"interval_pct":-10,"flee_bonus":10,"element":"dark"}'::jsonb, '極限配速挑戰者專屬，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 807),
  ('ar_shortbow_t9', 'ar_shortbow', 9, '巡迴獵影弓', 'epic', 80, 'neutral', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 900),
  ('ar_shortbow_t9_metal', 'ar_shortbow', 9, '巡迴獵影弓‧鋼', 'epic', 80, 'metal', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"metal"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 901),
  ('ar_shortbow_t9_wood', 'ar_shortbow', 9, '巡迴獵影弓‧森', 'epic', 80, 'wood', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"wood"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 902),
  ('ar_shortbow_t9_water', 'ar_shortbow', 9, '巡迴獵影弓‧霜', 'epic', 80, 'water', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"water"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 903),
  ('ar_shortbow_t9_fire', 'ar_shortbow', 9, '巡迴獵影弓‧焰', 'epic', 80, 'fire', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"fire"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 904),
  ('ar_shortbow_t9_earth', 'ar_shortbow', 9, '巡迴獵影弓‧岩', 'epic', 80, 'earth', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"earth"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 905),
  ('ar_shortbow_t9_light', 'ar_shortbow', 9, '巡迴獵影弓‧曜', 'epic', 80, 'light', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"light"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 906),
  ('ar_shortbow_t9_dark', 'ar_shortbow', 9, '巡迴獵影弓‧影', 'epic', 80, 'dark', '{"atk":87,"interval_pct":-10,"flee_bonus":11,"element":"dark"}'::jsonb, '全國巡迴賽事的頂尖裝備，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 907),
  ('ar_shortbow_t10', 'ar_shortbow', 10, '極速殘影弓', 'legendary', 90, 'neutral', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成。', TRUE, 1000),
  ('ar_shortbow_t10_metal', 'ar_shortbow', 10, '極速殘影弓‧鋼', 'legendary', 90, 'metal', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"metal"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1001),
  ('ar_shortbow_t10_wood', 'ar_shortbow', 10, '極速殘影弓‧森', 'legendary', 90, 'wood', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"wood"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1002),
  ('ar_shortbow_t10_water', 'ar_shortbow', 10, '極速殘影弓‧霜', 'legendary', 90, 'water', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"water"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1003),
  ('ar_shortbow_t10_fire', 'ar_shortbow', 10, '極速殘影弓‧焰', 'legendary', 90, 'fire', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"fire"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1004),
  ('ar_shortbow_t10_earth', 'ar_shortbow', 10, '極速殘影弓‧岩', 'legendary', 90, 'earth', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"earth"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1005),
  ('ar_shortbow_t10_light', 'ar_shortbow', 10, '極速殘影弓‧曜', 'legendary', 90, 'light', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"light"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1006),
  ('ar_shortbow_t10_dark', 'ar_shortbow', 10, '極速殘影弓‧影', 'legendary', 90, 'dark', '{"atk":94,"interval_pct":-10,"flee_bonus":12,"element":"dark"}'::jsonb, '傳說等級，只在最終賽場現身，輕巧好操作、出手極快，並附加迴避率加成，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1007),
  ('ar_crossbow_t1', 'ar_crossbow', 1, '社區連弩', 'common', 1, 'neutral', '{"atk":6,"interval_pct":-25,"crit_dmg_pct":8,"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 100),
  ('ar_crossbow_t2', 'ar_crossbow', 2, '河濱速發弩', 'common', 10, 'neutral', '{"atk":13,"interval_pct":-25,"crit_dmg_pct":9,"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 200),
  ('ar_crossbow_t3', 'ar_crossbow', 3, '路跑瞬發弩', 'common', 20, 'neutral', '{"atk":19,"interval_pct":-25,"crit_dmg_pct":11,"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 300),
  ('ar_crossbow_t4', 'ar_crossbow', 4, '夜巡連射弩', 'rare', 30, 'neutral', '{"atk":26,"interval_pct":-25,"crit_dmg_pct":12,"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 400),
  ('ar_crossbow_t5', 'ar_crossbow', 5, '半馬急速弩', 'rare', 40, 'neutral', '{"atk":35,"interval_pct":-25,"crit_dmg_pct":13,"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 500),
  ('ar_crossbow_t6', 'ar_crossbow', 6, '全馬爆發弩', 'rare', 50, 'neutral', '{"atk":40,"interval_pct":-25,"crit_dmg_pct":15,"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 600),
  ('ar_crossbow_t7', 'ar_crossbow', 7, '先鋒精準弩', 'epic', 60, 'neutral', '{"atk":51,"interval_pct":-25,"crit_dmg_pct":16,"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 700),
  ('ar_crossbow_t8', 'ar_crossbow', 8, '破風致命弩', 'epic', 70, 'neutral', '{"atk":58,"interval_pct":-25,"crit_dmg_pct":17,"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 800),
  ('ar_crossbow_t9', 'ar_crossbow', 9, '巡迴獵殺弩', 'epic', 80, 'neutral', '{"atk":70,"interval_pct":-25,"crit_dmg_pct":19,"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 900),
  ('ar_crossbow_t10', 'ar_crossbow', 10, '終極瞬殺弩', 'legendary', 90, 'neutral', '{"atk":75,"interval_pct":-25,"crit_dmg_pct":20,"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，扣下扳機瞬間擊發、攻擊間隔全弓種最短，弩箭爆擊格外致命。', TRUE, 1000),
  ('mg_staff_t1', 'mg_staff', 1, '晨跑訊號杖', 'common', 1, 'neutral', '{"atk":3,"matk":7,"int_bonus":2,"mp_pct":5,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.1以上可裝備，魔攻基礎值約7，INT+2、MP上限+5%。', TRUE, 100),
  ('mg_staff_t2', 'mg_staff', 2, '巷口訊號杖', 'common', 10, 'neutral', '{"atk":6,"matk":18,"int_bonus":3,"mp_pct":7,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.10以上可裝備，魔攻基礎值約18，INT+3、MP上限+7%。', TRUE, 200),
  ('mg_staff_t3', 'mg_staff', 3, '河濱訊號杖', 'common', 20, 'neutral', '{"atk":10,"matk":29,"int_bonus":4,"mp_pct":8,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.20以上可裝備，魔攻基礎值約29，INT+4、MP上限+8%。', TRUE, 300),
  ('mg_staff_t4', 'mg_staff', 4, '街區訊號杖', 'rare', 30, 'neutral', '{"atk":13,"matk":38,"int_bonus":5,"mp_pct":10,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.30以上可裝備，魔攻基礎值約38，INT+5、MP上限+10%。', TRUE, 400),
  ('mg_staff_t5', 'mg_staff', 5, '夜市訊號杖', 'rare', 40, 'neutral', '{"atk":18,"matk":51,"int_bonus":6,"mp_pct":12,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.40以上可裝備，魔攻基礎值約51，INT+6、MP上限+12%。', TRUE, 500),
  ('mg_staff_t6', 'mg_staff', 6, '城市訊號杖', 'rare', 50, 'neutral', '{"atk":20,"matk":60,"int_bonus":8,"mp_pct":13,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.50以上可裝備，魔攻基礎值約60，INT+8、MP上限+13%。', TRUE, 600),
  ('mg_staff_t7', 'mg_staff', 7, '山徑訊號杖', 'epic', 60, 'neutral', '{"atk":26,"matk":75,"int_bonus":9,"mp_pct":15,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.60以上可裝備，魔攻基礎值約75，INT+9、MP上限+15%。', TRUE, 700),
  ('mg_staff_t8', 'mg_staff', 8, '夜景訊號杖', 'epic', 70, 'neutral', '{"atk":29,"matk":85,"int_bonus":10,"mp_pct":17,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.70以上可裝備，魔攻基礎值約85，INT+10、MP上限+17%。', TRUE, 800),
  ('mg_staff_t9', 'mg_staff', 9, '天際線訊號杖', 'epic', 80, 'neutral', '{"atk":35,"matk":103,"int_bonus":11,"mp_pct":18,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.80以上可裝備，魔攻基礎值約103，INT+11、MP上限+18%。', TRUE, 900),
  ('mg_staff_t10', 'mg_staff', 10, '巔峰訊號杖', 'legendary', 90, 'neutral', '{"atk":38,"matk":112,"int_bonus":12,"mp_pct":20,"element":"neutral"}'::jsonb, '傳說等級的杖，Lv.90以上可裝備，魔攻基礎值約112，INT+12、MP上限+20%。', TRUE, 1000),
  ('mg_rod_t1', 'mg_rod', 1, '晨跑電網棍', 'common', 1, 'neutral', '{"atk":3,"matk":7,"matk_pct":5,"element":"neutral"}'::jsonb, '入門等級的棍，Lv.1以上可裝備，魔攻基礎值約7，魔法攻擊力額外+5%。', TRUE, 100),
  ('mg_rod_t2', 'mg_rod', 2, '巷口電網棍', 'common', 10, 'neutral', '{"atk":6,"matk":18,"matk_pct":7,"element":"neutral"}'::jsonb, '入門等級的棍，Lv.10以上可裝備，魔攻基礎值約18，魔法攻擊力額外+7%。', TRUE, 200),
  ('mg_rod_t3', 'mg_rod', 3, '河濱電網棍', 'common', 20, 'neutral', '{"atk":10,"matk":29,"matk_pct":8,"element":"neutral"}'::jsonb, '入門等級的棍，Lv.20以上可裝備，魔攻基礎值約29，魔法攻擊力額外+8%。', TRUE, 300),
  ('mg_rod_t4', 'mg_rod', 4, '街區電網棍', 'rare', 30, 'neutral', '{"atk":13,"matk":38,"matk_pct":10,"element":"neutral"}'::jsonb, '進階等級的棍，Lv.30以上可裝備，魔攻基礎值約38，魔法攻擊力額外+10%。', TRUE, 400),
  ('mg_rod_t5', 'mg_rod', 5, '夜市電網棍', 'rare', 40, 'neutral', '{"atk":18,"matk":51,"matk_pct":12,"element":"neutral"}'::jsonb, '進階等級的棍，Lv.40以上可裝備，魔攻基礎值約51，魔法攻擊力額外+12%。', TRUE, 500),
  ('mg_rod_t6', 'mg_rod', 6, '城市電網棍', 'rare', 50, 'neutral', '{"atk":20,"matk":60,"matk_pct":13,"element":"neutral"}'::jsonb, '進階等級的棍，Lv.50以上可裝備，魔攻基礎值約60，魔法攻擊力額外+13%。', TRUE, 600),
  ('mg_rod_t7', 'mg_rod', 7, '山徑電網棍', 'epic', 60, 'neutral', '{"atk":26,"matk":75,"matk_pct":15,"element":"neutral"}'::jsonb, '精良等級的棍，Lv.60以上可裝備，魔攻基礎值約75，魔法攻擊力額外+15%。', TRUE, 700),
  ('mg_rod_t8', 'mg_rod', 8, '夜景電網棍', 'epic', 70, 'neutral', '{"atk":29,"matk":85,"matk_pct":17,"element":"neutral"}'::jsonb, '精良等級的棍，Lv.70以上可裝備，魔攻基礎值約85，魔法攻擊力額外+17%。', TRUE, 800),
  ('mg_rod_t9', 'mg_rod', 9, '天際線電網棍', 'epic', 80, 'neutral', '{"atk":35,"matk":103,"matk_pct":18,"element":"neutral"}'::jsonb, '精良等級的棍，Lv.80以上可裝備，魔攻基礎值約103，魔法攻擊力額外+18%。', TRUE, 900),
  ('mg_rod_t10', 'mg_rod', 10, '巔峰電網棍', 'legendary', 90, 'neutral', '{"atk":38,"matk":112,"matk_pct":20,"element":"neutral"}'::jsonb, '傳說等級的棍，Lv.90以上可裝備，魔攻基礎值約112，魔法攻擊力額外+20%。', TRUE, 1000),
  ('mg_book_t1', 'mg_book', 1, '晨跑熱島手冊', 'common', 1, 'neutral', '{"atk":3,"matk":6,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.1以上可裝備，魔攻基礎值約6，魔法技能效果+5%。', TRUE, 100),
  ('mg_book_t2', 'mg_book', 2, '巷口熱島手冊', 'common', 10, 'neutral', '{"atk":6,"matk":15,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.10以上可裝備，魔攻基礎值約15，魔法技能效果+5%。', TRUE, 200),
  ('mg_book_t3', 'mg_book', 3, '河濱熱島手冊', 'common', 20, 'neutral', '{"atk":10,"matk":25,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.20以上可裝備，魔攻基礎值約25，魔法技能效果+5%。', TRUE, 300),
  ('mg_book_t4', 'mg_book', 4, '街區熱島手冊', 'rare', 30, 'neutral', '{"atk":13,"matk":32,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.30以上可裝備，魔攻基礎值約32，魔法技能效果+5%。', TRUE, 400),
  ('mg_book_t5', 'mg_book', 5, '夜市熱島手冊', 'rare', 40, 'neutral', '{"atk":18,"matk":43,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.40以上可裝備，魔攻基礎值約43，魔法技能效果+5%。', TRUE, 500),
  ('mg_book_t6', 'mg_book', 6, '城市熱島手冊', 'rare', 50, 'neutral', '{"atk":20,"matk":51,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.50以上可裝備，魔攻基礎值約51，魔法技能效果+5%。', TRUE, 600),
  ('mg_book_t7', 'mg_book', 7, '山徑熱島手冊', 'epic', 60, 'neutral', '{"atk":26,"matk":64,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.60以上可裝備，魔攻基礎值約64，魔法技能效果+5%。', TRUE, 700),
  ('mg_book_t8', 'mg_book', 8, '夜景熱島手冊', 'epic', 70, 'neutral', '{"atk":29,"matk":72,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.70以上可裝備，魔攻基礎值約72，魔法技能效果+5%。', TRUE, 800),
  ('mg_book_t9', 'mg_book', 9, '天際線熱島手冊', 'epic', 80, 'neutral', '{"atk":35,"matk":88,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.80以上可裝備，魔攻基礎值約88，魔法技能效果+5%。', TRUE, 900),
  ('mg_book_t10', 'mg_book', 10, '巔峰熱島手冊', 'legendary', 90, 'neutral', '{"atk":38,"matk":95,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '傳說等級的書，Lv.90以上可裝備，魔攻基礎值約95，魔法技能效果+5%。', TRUE, 1000),
  ('cl_staff_t1', 'cl_staff', 1, '晨跑包紮杖', 'common', 1, 'neutral', '{"atk":3,"matk":7,"int_bonus":2,"mp_pct":5,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.1以上可裝備，魔攻基礎值約7，INT+2、MP上限+5%。', TRUE, 100),
  ('cl_staff_t2', 'cl_staff', 2, '巷口包紮杖', 'common', 10, 'neutral', '{"atk":6,"matk":18,"int_bonus":3,"mp_pct":7,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.10以上可裝備，魔攻基礎值約18，INT+3、MP上限+7%。', TRUE, 200),
  ('cl_staff_t3', 'cl_staff', 3, '河濱包紮杖', 'common', 20, 'neutral', '{"atk":10,"matk":29,"int_bonus":4,"mp_pct":8,"element":"neutral"}'::jsonb, '入門等級的杖，Lv.20以上可裝備，魔攻基礎值約29，INT+4、MP上限+8%。', TRUE, 300),
  ('cl_staff_t4', 'cl_staff', 4, '街區包紮杖', 'rare', 30, 'neutral', '{"atk":13,"matk":38,"int_bonus":5,"mp_pct":10,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.30以上可裝備，魔攻基礎值約38，INT+5、MP上限+10%。', TRUE, 400),
  ('cl_staff_t5', 'cl_staff', 5, '夜市包紮杖', 'rare', 40, 'neutral', '{"atk":18,"matk":51,"int_bonus":6,"mp_pct":12,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.40以上可裝備，魔攻基礎值約51，INT+6、MP上限+12%。', TRUE, 500),
  ('cl_staff_t6', 'cl_staff', 6, '城市包紮杖', 'rare', 50, 'neutral', '{"atk":20,"matk":60,"int_bonus":8,"mp_pct":13,"element":"neutral"}'::jsonb, '進階等級的杖，Lv.50以上可裝備，魔攻基礎值約60，INT+8、MP上限+13%。', TRUE, 600),
  ('cl_staff_t7', 'cl_staff', 7, '山徑包紮杖', 'epic', 60, 'neutral', '{"atk":26,"matk":75,"int_bonus":9,"mp_pct":15,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.60以上可裝備，魔攻基礎值約75，INT+9、MP上限+15%。', TRUE, 700),
  ('cl_staff_t8', 'cl_staff', 8, '夜景包紮杖', 'epic', 70, 'neutral', '{"atk":29,"matk":85,"int_bonus":10,"mp_pct":17,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.70以上可裝備，魔攻基礎值約85，INT+10、MP上限+17%。', TRUE, 800),
  ('cl_staff_t9', 'cl_staff', 9, '天際線包紮杖', 'epic', 80, 'neutral', '{"atk":35,"matk":103,"int_bonus":11,"mp_pct":18,"element":"neutral"}'::jsonb, '精良等級的杖，Lv.80以上可裝備，魔攻基礎值約103，INT+11、MP上限+18%。', TRUE, 900),
  ('cl_staff_t10', 'cl_staff', 10, '巔峰包紮杖', 'legendary', 90, 'neutral', '{"atk":38,"matk":112,"int_bonus":12,"mp_pct":20,"element":"neutral"}'::jsonb, '傳說等級的杖，Lv.90以上可裝備，魔攻基礎值約112，INT+12、MP上限+20%。', TRUE, 1000),
  ('cl_book_t1', 'cl_book', 1, '晨跑補給手冊', 'common', 1, 'neutral', '{"atk":3,"matk":6,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.1以上可裝備，魔攻基礎值約6，魔法技能效果+5%。', TRUE, 100),
  ('cl_book_t2', 'cl_book', 2, '巷口補給手冊', 'common', 10, 'neutral', '{"atk":6,"matk":15,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.10以上可裝備，魔攻基礎值約15，魔法技能效果+5%。', TRUE, 200),
  ('cl_book_t3', 'cl_book', 3, '河濱補給手冊', 'common', 20, 'neutral', '{"atk":10,"matk":25,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '入門等級的書，Lv.20以上可裝備，魔攻基礎值約25，魔法技能效果+5%。', TRUE, 300),
  ('cl_book_t4', 'cl_book', 4, '街區補給手冊', 'rare', 30, 'neutral', '{"atk":13,"matk":32,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.30以上可裝備，魔攻基礎值約32，魔法技能效果+5%。', TRUE, 400),
  ('cl_book_t5', 'cl_book', 5, '夜市補給手冊', 'rare', 40, 'neutral', '{"atk":18,"matk":43,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.40以上可裝備，魔攻基礎值約43，魔法技能效果+5%。', TRUE, 500),
  ('cl_book_t6', 'cl_book', 6, '城市補給手冊', 'rare', 50, 'neutral', '{"atk":20,"matk":51,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '進階等級的書，Lv.50以上可裝備，魔攻基礎值約51，魔法技能效果+5%。', TRUE, 600),
  ('cl_book_t7', 'cl_book', 7, '山徑補給手冊', 'epic', 60, 'neutral', '{"atk":26,"matk":64,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.60以上可裝備，魔攻基礎值約64，魔法技能效果+5%。', TRUE, 700),
  ('cl_book_t8', 'cl_book', 8, '夜景補給手冊', 'epic', 70, 'neutral', '{"atk":29,"matk":72,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.70以上可裝備，魔攻基礎值約72，魔法技能效果+5%。', TRUE, 800),
  ('cl_book_t9', 'cl_book', 9, '天際線補給手冊', 'epic', 80, 'neutral', '{"atk":35,"matk":88,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '精良等級的書，Lv.80以上可裝備，魔攻基礎值約88，魔法技能效果+5%。', TRUE, 900),
  ('cl_book_t10', 'cl_book', 10, '巔峰補給手冊', 'legendary', 90, 'neutral', '{"atk":38,"matk":95,"magic_skill_pct":5,"element":"neutral"}'::jsonb, '傳說等級的書，Lv.90以上可裝備，魔攻基礎值約95，魔法技能效果+5%。', TRUE, 1000),
  ('cl_chain_t1', 'cl_chain', 1, '晨跑護具鍊', 'common', 1, 'neutral', '{"atk":3,"matk":7,"element_resist_pct":5,"mdef_pct":5,"element":"neutral"}'::jsonb, '入門等級的鍊，Lv.1以上可裝備，魔攻基礎值約7，魔法抗性+5%、魔防+5%。', TRUE, 100),
  ('cl_chain_t2', 'cl_chain', 2, '巷口護具鍊', 'common', 10, 'neutral', '{"atk":6,"matk":18,"element_resist_pct":7,"mdef_pct":6,"element":"neutral"}'::jsonb, '入門等級的鍊，Lv.10以上可裝備，魔攻基礎值約18，魔法抗性+7%、魔防+6%。', TRUE, 200),
  ('cl_chain_t3', 'cl_chain', 3, '河濱護具鍊', 'common', 20, 'neutral', '{"atk":10,"matk":29,"element_resist_pct":9,"mdef_pct":7,"element":"neutral"}'::jsonb, '入門等級的鍊，Lv.20以上可裝備，魔攻基礎值約29，魔法抗性+9%、魔防+7%。', TRUE, 300),
  ('cl_chain_t4', 'cl_chain', 4, '街區護具鍊', 'rare', 30, 'neutral', '{"atk":13,"matk":38,"element_resist_pct":12,"mdef_pct":8,"element":"neutral"}'::jsonb, '進階等級的鍊，Lv.30以上可裝備，魔攻基礎值約38，魔法抗性+12%、魔防+8%。', TRUE, 400),
  ('cl_chain_t5', 'cl_chain', 5, '夜市護具鍊', 'rare', 40, 'neutral', '{"atk":18,"matk":51,"element_resist_pct":14,"mdef_pct":9,"element":"neutral"}'::jsonb, '進階等級的鍊，Lv.40以上可裝備，魔攻基礎值約51，魔法抗性+14%、魔防+9%。', TRUE, 500),
  ('cl_chain_t6', 'cl_chain', 6, '城市護具鍊', 'rare', 50, 'neutral', '{"atk":20,"matk":60,"element_resist_pct":16,"mdef_pct":11,"element":"neutral"}'::jsonb, '進階等級的鍊，Lv.50以上可裝備，魔攻基礎值約60，魔法抗性+16%、魔防+11%。', TRUE, 600),
  ('cl_chain_t7', 'cl_chain', 7, '山徑護具鍊', 'epic', 60, 'neutral', '{"atk":26,"matk":75,"element_resist_pct":18,"mdef_pct":12,"element":"neutral"}'::jsonb, '精良等級的鍊，Lv.60以上可裝備，魔攻基礎值約75，魔法抗性+18%、魔防+12%。', TRUE, 700),
  ('cl_chain_t8', 'cl_chain', 8, '夜景護具鍊', 'epic', 70, 'neutral', '{"atk":29,"matk":85,"element_resist_pct":21,"mdef_pct":13,"element":"neutral"}'::jsonb, '精良等級的鍊，Lv.70以上可裝備，魔攻基礎值約85，魔法抗性+21%、魔防+13%。', TRUE, 800),
  ('cl_chain_t9', 'cl_chain', 9, '天際線護具鍊', 'epic', 80, 'neutral', '{"atk":35,"matk":103,"element_resist_pct":23,"mdef_pct":14,"element":"neutral"}'::jsonb, '精良等級的鍊，Lv.80以上可裝備，魔攻基礎值約103，魔法抗性+23%、魔防+14%。', TRUE, 900),
  ('cl_chain_t10', 'cl_chain', 10, '巔峰護具鍊', 'legendary', 90, 'neutral', '{"atk":38,"matk":112,"element_resist_pct":25,"mdef_pct":15,"element":"neutral"}'::jsonb, '傳說等級的鍊，Lv.90以上可裝備，魔攻基礎值約112，魔法抗性+25%、魔防+15%。', TRUE, 1000),
  ('mc_hammer_t1', 'mc_hammer', 1, '晨跑秤錘', 'common', 1, 'neutral', '{"atk":7,"crit_dmg_pct":5,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的錘，Lv.1以上可裝備，物攻基礎值約7，爆擊傷害+5%（對大體型額外+5%傷害）。', TRUE, 100),
  ('mc_hammer_t2', 'mc_hammer', 2, '巷口秤錘', 'common', 10, 'neutral', '{"atk":16,"crit_dmg_pct":7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的錘，Lv.10以上可裝備，物攻基礎值約16，爆擊傷害+7%（對大體型額外+5%傷害）。', TRUE, 200),
  ('mc_hammer_t3', 'mc_hammer', 3, '河濱秤錘', 'common', 20, 'neutral', '{"atk":24,"crit_dmg_pct":8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的錘，Lv.20以上可裝備，物攻基礎值約24，爆擊傷害+8%（對大體型額外+5%傷害）。', TRUE, 300),
  ('mc_hammer_t4', 'mc_hammer', 4, '街區秤錘', 'rare', 30, 'neutral', '{"atk":32,"crit_dmg_pct":10,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的錘，Lv.30以上可裝備，物攻基礎值約32，爆擊傷害+10%（對大體型額外+5%傷害）。', TRUE, 400),
  ('mc_hammer_t5', 'mc_hammer', 5, '夜市秤錘', 'rare', 40, 'neutral', '{"atk":44,"crit_dmg_pct":12,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的錘，Lv.40以上可裝備，物攻基礎值約44，爆擊傷害+12%（對大體型額外+5%傷害）。', TRUE, 500),
  ('mc_hammer_t6', 'mc_hammer', 6, '城市秤錘', 'rare', 50, 'neutral', '{"atk":50,"crit_dmg_pct":13,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的錘，Lv.50以上可裝備，物攻基礎值約50，爆擊傷害+13%（對大體型額外+5%傷害）。', TRUE, 600),
  ('mc_hammer_t7', 'mc_hammer', 7, '山徑秤錘', 'epic', 60, 'neutral', '{"atk":64,"crit_dmg_pct":15,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的錘，Lv.60以上可裝備，物攻基礎值約64，爆擊傷害+15%（對大體型額外+5%傷害）。', TRUE, 700),
  ('mc_hammer_t8', 'mc_hammer', 8, '夜景秤錘', 'epic', 70, 'neutral', '{"atk":72,"crit_dmg_pct":17,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的錘，Lv.70以上可裝備，物攻基礎值約72，爆擊傷害+17%（對大體型額外+5%傷害）。', TRUE, 800),
  ('mc_hammer_t9', 'mc_hammer', 9, '天際線秤錘', 'epic', 80, 'neutral', '{"atk":87,"crit_dmg_pct":18,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的錘，Lv.80以上可裝備，物攻基礎值約87，爆擊傷害+18%（對大體型額外+5%傷害）。', TRUE, 900),
  ('mc_hammer_t10', 'mc_hammer', 10, '巔峰秤錘', 'legendary', 90, 'neutral', '{"atk":94,"crit_dmg_pct":20,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級的錘，Lv.90以上可裝備，物攻基礎值約94，爆擊傷害+20%（對大體型額外+5%傷害）。', TRUE, 1000),
  ('mc_mallet_t1', 'mc_mallet', 1, '晨跑叫賣槌', 'common', 1, 'neutral', '{"atk":7,"atk_pct":5,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的槌，Lv.1以上可裝備，物攻基礎值約7，物理攻擊力額外+5%（對大體型額外+5%傷害）。', TRUE, 100),
  ('mc_mallet_t2', 'mc_mallet', 2, '巷口叫賣槌', 'common', 10, 'neutral', '{"atk":16,"atk_pct":6,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的槌，Lv.10以上可裝備，物攻基礎值約16，物理攻擊力額外+6%（對大體型額外+5%傷害）。', TRUE, 200),
  ('mc_mallet_t3', 'mc_mallet', 3, '河濱叫賣槌', 'common', 20, 'neutral', '{"atk":24,"atk_pct":7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的槌，Lv.20以上可裝備，物攻基礎值約24，物理攻擊力額外+7%（對大體型額外+5%傷害）。', TRUE, 300),
  ('mc_mallet_t4', 'mc_mallet', 4, '街區叫賣槌', 'rare', 30, 'neutral', '{"atk":32,"atk_pct":8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的槌，Lv.30以上可裝備，物攻基礎值約32，物理攻擊力額外+8%（對大體型額外+5%傷害）。', TRUE, 400),
  ('mc_mallet_t5', 'mc_mallet', 5, '夜市叫賣槌', 'rare', 40, 'neutral', '{"atk":44,"atk_pct":9,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的槌，Lv.40以上可裝備，物攻基礎值約44，物理攻擊力額外+9%（對大體型額外+5%傷害）。', TRUE, 500),
  ('mc_mallet_t6', 'mc_mallet', 6, '城市叫賣槌', 'rare', 50, 'neutral', '{"atk":50,"atk_pct":11,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的槌，Lv.50以上可裝備，物攻基礎值約50，物理攻擊力額外+11%（對大體型額外+5%傷害）。', TRUE, 600),
  ('mc_mallet_t7', 'mc_mallet', 7, '山徑叫賣槌', 'epic', 60, 'neutral', '{"atk":64,"atk_pct":12,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的槌，Lv.60以上可裝備，物攻基礎值約64，物理攻擊力額外+12%（對大體型額外+5%傷害）。', TRUE, 700),
  ('mc_mallet_t8', 'mc_mallet', 8, '夜景叫賣槌', 'epic', 70, 'neutral', '{"atk":72,"atk_pct":13,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的槌，Lv.70以上可裝備，物攻基礎值約72，物理攻擊力額外+13%（對大體型額外+5%傷害）。', TRUE, 800),
  ('mc_mallet_t9', 'mc_mallet', 9, '天際線叫賣槌', 'epic', 80, 'neutral', '{"atk":87,"atk_pct":14,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的槌，Lv.80以上可裝備，物攻基礎值約87，物理攻擊力額外+14%（對大體型額外+5%傷害）。', TRUE, 900),
  ('mc_mallet_t10', 'mc_mallet', 10, '巔峰叫賣槌', 'legendary', 90, 'neutral', '{"atk":94,"atk_pct":15,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級的槌，Lv.90以上可裝備，物攻基礎值約94，物理攻擊力額外+15%（對大體型額外+5%傷害）。', TRUE, 1000),
  ('mc_club_t1', 'mc_club', 1, '晨跑顧攤棒', 'common', 1, 'neutral', '{"atk":7,"def_pct":5,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的棒，Lv.1以上可裝備，物攻基礎值約7，物理防禦力額外+5%（對大體型額外+5%傷害）。', TRUE, 100),
  ('mc_club_t2', 'mc_club', 2, '巷口顧攤棒', 'common', 10, 'neutral', '{"atk":16,"def_pct":6,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的棒，Lv.10以上可裝備，物攻基礎值約16，物理防禦力額外+6%（對大體型額外+5%傷害）。', TRUE, 200),
  ('mc_club_t3', 'mc_club', 3, '河濱顧攤棒', 'common', 20, 'neutral', '{"atk":24,"def_pct":7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '入門等級的棒，Lv.20以上可裝備，物攻基礎值約24，物理防禦力額外+7%（對大體型額外+5%傷害）。', TRUE, 300),
  ('mc_club_t4', 'mc_club', 4, '街區顧攤棒', 'rare', 30, 'neutral', '{"atk":32,"def_pct":8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的棒，Lv.30以上可裝備，物攻基礎值約32，物理防禦力額外+8%（對大體型額外+5%傷害）。', TRUE, 400),
  ('mc_club_t5', 'mc_club', 5, '夜市顧攤棒', 'rare', 40, 'neutral', '{"atk":44,"def_pct":9,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的棒，Lv.40以上可裝備，物攻基礎值約44，物理防禦力額外+9%（對大體型額外+5%傷害）。', TRUE, 500),
  ('mc_club_t6', 'mc_club', 6, '城市顧攤棒', 'rare', 50, 'neutral', '{"atk":50,"def_pct":11,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '進階等級的棒，Lv.50以上可裝備，物攻基礎值約50，物理防禦力額外+11%（對大體型額外+5%傷害）。', TRUE, 600),
  ('mc_club_t7', 'mc_club', 7, '山徑顧攤棒', 'epic', 60, 'neutral', '{"atk":64,"def_pct":12,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的棒，Lv.60以上可裝備，物攻基礎值約64，物理防禦力額外+12%（對大體型額外+5%傷害）。', TRUE, 700),
  ('mc_club_t8', 'mc_club', 8, '夜景顧攤棒', 'epic', 70, 'neutral', '{"atk":72,"def_pct":13,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的棒，Lv.70以上可裝備，物攻基礎值約72，物理防禦力額外+13%（對大體型額外+5%傷害）。', TRUE, 800),
  ('mc_club_t9', 'mc_club', 9, '天際線顧攤棒', 'epic', 80, 'neutral', '{"atk":87,"def_pct":14,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '精良等級的棒，Lv.80以上可裝備，物攻基礎值約87，物理防禦力額外+14%（對大體型額外+5%傷害）。', TRUE, 900),
  ('mc_club_t10', 'mc_club', 10, '巔峰顧攤棒', 'legendary', 90, 'neutral', '{"atk":94,"def_pct":15,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級的棒，Lv.90以上可裝備，物攻基礎值約94，物理防禦力額外+15%（對大體型額外+5%傷害）。', TRUE, 1000),
  ('hk_greatsword_t1', 'hk_greatsword', 1, '社區重劍', 'common', 1, 'neutral', '{"atk":8,"charge_time_mul":1.5,"charge_dmg_mul":1.6,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 100),
  ('hk_greatsword_t2', 'hk_greatsword', 2, '河濱蓄力劍', 'common', 10, 'neutral', '{"atk":18,"charge_time_mul":1.5,"charge_dmg_mul":1.6,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 200),
  ('hk_greatsword_t3', 'hk_greatsword', 3, '路跑巨刃劍', 'common', 20, 'neutral', '{"atk":28,"charge_time_mul":1.5,"charge_dmg_mul":1.7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 300),
  ('hk_greatsword_t4', 'hk_greatsword', 4, '夜巡沉重劍', 'rare', 30, 'neutral', '{"atk":37,"charge_time_mul":1.5,"charge_dmg_mul":1.7,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 400),
  ('hk_greatsword_t5', 'hk_greatsword', 5, '半馬破陣劍', 'rare', 40, 'neutral', '{"atk":51,"charge_time_mul":1.5,"charge_dmg_mul":1.8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 500),
  ('hk_greatsword_t6', 'hk_greatsword', 6, '全馬碎地劍', 'rare', 50, 'neutral', '{"atk":57,"charge_time_mul":1.5,"charge_dmg_mul":1.8,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 600),
  ('hk_greatsword_t7', 'hk_greatsword', 7, '先鋒毀滅劍', 'epic', 60, 'neutral', '{"atk":74,"charge_time_mul":1.5,"charge_dmg_mul":1.9,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 700),
  ('hk_greatsword_t8', 'hk_greatsword', 8, '破風崩城劍', 'epic', 70, 'neutral', '{"atk":83,"charge_time_mul":1.5,"charge_dmg_mul":1.9,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 800),
  ('hk_greatsword_t9', 'hk_greatsword', 9, '巡迴戰神劍', 'epic', 80, 'neutral', '{"atk":100,"charge_time_mul":1.5,"charge_dmg_mul":2.0,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 900),
  ('hk_greatsword_t10', 'hk_greatsword', 10, '傳說終焉巨劍', 'legendary', 90, 'neutral', '{"atk":108,"charge_time_mul":1.5,"charge_dmg_mul":2.0,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，揮動前需蓄力，一旦劈下傷害倍增，尤其克制大型目標。', TRUE, 1000),
  ('hk_spear_t1', 'hk_spear', 1, '社區突刺槍', 'common', 1, 'neutral', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 100),
  ('hk_spear_t1_metal', 'hk_spear', 1, '社區突刺槍‧鋼', 'common', 1, 'metal', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"metal"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 101),
  ('hk_spear_t1_wood', 'hk_spear', 1, '社區突刺槍‧森', 'common', 1, 'wood', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"wood"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 102),
  ('hk_spear_t1_water', 'hk_spear', 1, '社區突刺槍‧霜', 'common', 1, 'water', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"water"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 103),
  ('hk_spear_t1_fire', 'hk_spear', 1, '社區突刺槍‧焰', 'common', 1, 'fire', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"fire"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 104),
  ('hk_spear_t1_earth', 'hk_spear', 1, '社區突刺槍‧岩', 'common', 1, 'earth', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"earth"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 105),
  ('hk_spear_t1_light', 'hk_spear', 1, '社區突刺槍‧曜', 'common', 1, 'light', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"light"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 106),
  ('hk_spear_t1_dark', 'hk_spear', 1, '社區突刺槍‧影', 'common', 1, 'dark', '{"atk":7,"hits":2,"hit_mul":0.5,"crit_pct":3,"crit_dmg_pct":5,"extra_hit_chance_pct":10,"element":"dark"}'::jsonb, '社區晨跑團的入門配備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 107),
  ('hk_spear_t2', 'hk_spear', 2, '河濱連擊槍', 'common', 10, 'neutral', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 200),
  ('hk_spear_t2_metal', 'hk_spear', 2, '河濱連擊槍‧鋼', 'common', 10, 'metal', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"metal"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 201),
  ('hk_spear_t2_wood', 'hk_spear', 2, '河濱連擊槍‧森', 'common', 10, 'wood', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"wood"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 202),
  ('hk_spear_t2_water', 'hk_spear', 2, '河濱連擊槍‧霜', 'common', 10, 'water', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"water"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 203),
  ('hk_spear_t2_fire', 'hk_spear', 2, '河濱連擊槍‧焰', 'common', 10, 'fire', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"fire"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 204),
  ('hk_spear_t2_earth', 'hk_spear', 2, '河濱連擊槍‧岩', 'common', 10, 'earth', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"earth"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 205),
  ('hk_spear_t2_light', 'hk_spear', 2, '河濱連擊槍‧曜', 'common', 10, 'light', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"light"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 206),
  ('hk_spear_t2_dark', 'hk_spear', 2, '河濱連擊槍‧影', 'common', 10, 'dark', '{"atk":16,"hits":2,"hit_mul":0.5,"crit_pct":4,"crit_dmg_pct":6,"extra_hit_chance_pct":12,"element":"dark"}'::jsonb, '河濱步道晨練老手愛用，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 207),
  ('hk_spear_t3', 'hk_spear', 3, '路跑穿透槍', 'common', 20, 'neutral', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 300),
  ('hk_spear_t3_metal', 'hk_spear', 3, '路跑穿透槍‧鋼', 'common', 20, 'metal', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"metal"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 301),
  ('hk_spear_t3_wood', 'hk_spear', 3, '路跑穿透槍‧森', 'common', 20, 'wood', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"wood"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 302),
  ('hk_spear_t3_water', 'hk_spear', 3, '路跑穿透槍‧霜', 'common', 20, 'water', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"water"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 303),
  ('hk_spear_t3_fire', 'hk_spear', 3, '路跑穿透槍‧焰', 'common', 20, 'fire', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"fire"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 304),
  ('hk_spear_t3_earth', 'hk_spear', 3, '路跑穿透槍‧岩', 'common', 20, 'earth', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"earth"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 305),
  ('hk_spear_t3_light', 'hk_spear', 3, '路跑穿透槍‧曜', 'common', 20, 'light', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"light"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 306),
  ('hk_spear_t3_dark', 'hk_spear', 3, '路跑穿透槍‧影', 'common', 20, 'dark', '{"atk":24,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":7,"extra_hit_chance_pct":14,"element":"dark"}'::jsonb, '假日路跑賽事的常勝夥伴，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 307),
  ('hk_spear_t4', 'hk_spear', 4, '夜巡疾刺槍', 'rare', 30, 'neutral', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 400),
  ('hk_spear_t4_metal', 'hk_spear', 4, '夜巡疾刺槍‧鋼', 'rare', 30, 'metal', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"metal"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 401),
  ('hk_spear_t4_wood', 'hk_spear', 4, '夜巡疾刺槍‧森', 'rare', 30, 'wood', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"wood"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 402),
  ('hk_spear_t4_water', 'hk_spear', 4, '夜巡疾刺槍‧霜', 'rare', 30, 'water', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"water"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 403),
  ('hk_spear_t4_fire', 'hk_spear', 4, '夜巡疾刺槍‧焰', 'rare', 30, 'fire', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"fire"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 404),
  ('hk_spear_t4_earth', 'hk_spear', 4, '夜巡疾刺槍‧岩', 'rare', 30, 'earth', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"earth"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 405),
  ('hk_spear_t4_light', 'hk_spear', 4, '夜巡疾刺槍‧曜', 'rare', 30, 'light', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"light"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 406),
  ('hk_spear_t4_dark', 'hk_spear', 4, '夜巡疾刺槍‧影', 'rare', 30, 'dark', '{"atk":32,"hits":2,"hit_mul":0.5,"crit_pct":5,"crit_dmg_pct":8,"extra_hit_chance_pct":17,"element":"dark"}'::jsonb, '夜跑俱樂部指定強化款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 407),
  ('hk_spear_t5', 'hk_spear', 5, '半馬連環槍', 'rare', 40, 'neutral', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 500),
  ('hk_spear_t5_metal', 'hk_spear', 5, '半馬連環槍‧鋼', 'rare', 40, 'metal', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"metal"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 501),
  ('hk_spear_t5_wood', 'hk_spear', 5, '半馬連環槍‧森', 'rare', 40, 'wood', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"wood"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 502),
  ('hk_spear_t5_water', 'hk_spear', 5, '半馬連環槍‧霜', 'rare', 40, 'water', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"water"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 503),
  ('hk_spear_t5_fire', 'hk_spear', 5, '半馬連環槍‧焰', 'rare', 40, 'fire', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"fire"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 504),
  ('hk_spear_t5_earth', 'hk_spear', 5, '半馬連環槍‧岩', 'rare', 40, 'earth', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"earth"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 505),
  ('hk_spear_t5_light', 'hk_spear', 5, '半馬連環槍‧曜', 'rare', 40, 'light', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"light"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 506),
  ('hk_spear_t5_dark', 'hk_spear', 5, '半馬連環槍‧影', 'rare', 40, 'dark', '{"atk":44,"hits":2,"hit_mul":0.5,"crit_pct":6,"crit_dmg_pct":9,"extra_hit_chance_pct":19,"element":"dark"}'::jsonb, '半程馬拉松選手信賴之選，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 507),
  ('hk_spear_t6', 'hk_spear', 6, '全馬破甲槍', 'rare', 50, 'neutral', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 600),
  ('hk_spear_t6_metal', 'hk_spear', 6, '全馬破甲槍‧鋼', 'rare', 50, 'metal', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"metal"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 601),
  ('hk_spear_t6_wood', 'hk_spear', 6, '全馬破甲槍‧森', 'rare', 50, 'wood', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"wood"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 602),
  ('hk_spear_t6_water', 'hk_spear', 6, '全馬破甲槍‧霜', 'rare', 50, 'water', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"water"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 603),
  ('hk_spear_t6_fire', 'hk_spear', 6, '全馬破甲槍‧焰', 'rare', 50, 'fire', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"fire"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 604),
  ('hk_spear_t6_earth', 'hk_spear', 6, '全馬破甲槍‧岩', 'rare', 50, 'earth', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"earth"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 605),
  ('hk_spear_t6_light', 'hk_spear', 6, '全馬破甲槍‧曜', 'rare', 50, 'light', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"light"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 606),
  ('hk_spear_t6_dark', 'hk_spear', 6, '全馬破甲槍‧影', 'rare', 50, 'dark', '{"atk":50,"hits":2,"hit_mul":0.5,"crit_pct":7,"crit_dmg_pct":11,"extra_hit_chance_pct":21,"element":"dark"}'::jsonb, '全程馬拉松賽場的主力裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 607),
  ('hk_spear_t7', 'hk_spear', 7, '先鋒三段槍', 'epic', 60, 'neutral', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 700),
  ('hk_spear_t7_metal', 'hk_spear', 7, '先鋒三段槍‧鋼', 'epic', 60, 'metal', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"metal"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 701),
  ('hk_spear_t7_wood', 'hk_spear', 7, '先鋒三段槍‧森', 'epic', 60, 'wood', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"wood"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 702),
  ('hk_spear_t7_water', 'hk_spear', 7, '先鋒三段槍‧霜', 'epic', 60, 'water', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"water"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 703),
  ('hk_spear_t7_fire', 'hk_spear', 7, '先鋒三段槍‧焰', 'epic', 60, 'fire', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"fire"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 704),
  ('hk_spear_t7_earth', 'hk_spear', 7, '先鋒三段槍‧岩', 'epic', 60, 'earth', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"earth"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 705),
  ('hk_spear_t7_light', 'hk_spear', 7, '先鋒三段槍‧曜', 'epic', 60, 'light', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"light"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 706),
  ('hk_spear_t7_dark', 'hk_spear', 7, '先鋒三段槍‧影', 'epic', 60, 'dark', '{"atk":64,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":12,"extra_hit_chance_pct":23,"element":"dark"}'::jsonb, '城市巡迴賽冠軍愛用款，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 707),
  ('hk_spear_t8', 'hk_spear', 8, '破風貫穿槍', 'epic', 70, 'neutral', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 800),
  ('hk_spear_t8_metal', 'hk_spear', 8, '破風貫穿槍‧鋼', 'epic', 70, 'metal', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"metal"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 801),
  ('hk_spear_t8_wood', 'hk_spear', 8, '破風貫穿槍‧森', 'epic', 70, 'wood', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"wood"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 802),
  ('hk_spear_t8_water', 'hk_spear', 8, '破風貫穿槍‧霜', 'epic', 70, 'water', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"water"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 803),
  ('hk_spear_t8_fire', 'hk_spear', 8, '破風貫穿槍‧焰', 'epic', 70, 'fire', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"fire"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 804),
  ('hk_spear_t8_earth', 'hk_spear', 8, '破風貫穿槍‧岩', 'epic', 70, 'earth', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"earth"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 805),
  ('hk_spear_t8_light', 'hk_spear', 8, '破風貫穿槍‧曜', 'epic', 70, 'light', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"light"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 806),
  ('hk_spear_t8_dark', 'hk_spear', 8, '破風貫穿槍‧影', 'epic', 70, 'dark', '{"atk":72,"hits":2,"hit_mul":0.5,"crit_pct":8,"crit_dmg_pct":13,"extra_hit_chance_pct":26,"element":"dark"}'::jsonb, '極限配速挑戰者專屬，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 807),
  ('hk_spear_t9', 'hk_spear', 9, '巡迴戰陣槍', 'epic', 80, 'neutral', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 900),
  ('hk_spear_t9_metal', 'hk_spear', 9, '巡迴戰陣槍‧鋼', 'epic', 80, 'metal', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"metal"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 901),
  ('hk_spear_t9_wood', 'hk_spear', 9, '巡迴戰陣槍‧森', 'epic', 80, 'wood', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"wood"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 902),
  ('hk_spear_t9_water', 'hk_spear', 9, '巡迴戰陣槍‧霜', 'epic', 80, 'water', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"water"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 903),
  ('hk_spear_t9_fire', 'hk_spear', 9, '巡迴戰陣槍‧焰', 'epic', 80, 'fire', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"fire"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 904),
  ('hk_spear_t9_earth', 'hk_spear', 9, '巡迴戰陣槍‧岩', 'epic', 80, 'earth', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"earth"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 905),
  ('hk_spear_t9_light', 'hk_spear', 9, '巡迴戰陣槍‧曜', 'epic', 80, 'light', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"light"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 906),
  ('hk_spear_t9_dark', 'hk_spear', 9, '巡迴戰陣槍‧影', 'epic', 80, 'dark', '{"atk":87,"hits":2,"hit_mul":0.5,"crit_pct":9,"crit_dmg_pct":14,"extra_hit_chance_pct":28,"element":"dark"}'::jsonb, '全國巡迴賽事的頂尖裝備，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 907),
  ('hk_spear_t10', 'hk_spear', 10, '傳說龍牙槍', 'legendary', 90, 'neutral', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊。', TRUE, 1000),
  ('hk_spear_t10_metal', 'hk_spear', 10, '傳說龍牙槍‧鋼', 'legendary', 90, 'metal', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"metal"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合金屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1001),
  ('hk_spear_t10_wood', 'hk_spear', 10, '傳說龍牙槍‧森', 'legendary', 90, 'wood', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"wood"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合木屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1002),
  ('hk_spear_t10_water', 'hk_spear', 10, '傳說龍牙槍‧霜', 'legendary', 90, 'water', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"water"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合水屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1003),
  ('hk_spear_t10_fire', 'hk_spear', 10, '傳說龍牙槍‧焰', 'legendary', 90, 'fire', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"fire"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合火屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1004),
  ('hk_spear_t10_earth', 'hk_spear', 10, '傳說龍牙槍‧岩', 'legendary', 90, 'earth', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"earth"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合土屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1005),
  ('hk_spear_t10_light', 'hk_spear', 10, '傳說龍牙槍‧曜', 'legendary', 90, 'light', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"light"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合光屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1006),
  ('hk_spear_t10_dark', 'hk_spear', 10, '傳說龍牙槍‧影', 'legendary', 90, 'dark', '{"atk":94,"hits":2,"hit_mul":0.5,"crit_pct":10,"crit_dmg_pct":15,"extra_hit_chance_pct":30,"element":"dark"}'::jsonb, '傳說等級，只在最終賽場現身，槍尖連刺兩段、威力各半，卻大幅提升爆擊率與爆擊傷害，偶有第三段追擊，並融合闇屬性之力，可對相剋的敵人造成加成傷害。', TRUE, 1007),
  ('hk_axe_t1', 'hk_axe', 1, '社區劈砍斧', 'common', 1, 'neutral', '{"atk":8,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '社區晨跑團的入門配備，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 100),
  ('hk_axe_t2', 'hk_axe', 2, '河濱重擊斧', 'common', 10, 'neutral', '{"atk":18,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '河濱步道晨練老手愛用，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 200),
  ('hk_axe_t3', 'hk_axe', 3, '路跑旋風斧', 'common', 20, 'neutral', '{"atk":26,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '假日路跑賽事的常勝夥伴，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 300),
  ('hk_axe_t4', 'hk_axe', 4, '夜巡碎裂斧', 'rare', 30, 'neutral', '{"atk":35,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '夜跑俱樂部指定強化款，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 400),
  ('hk_axe_t5', 'hk_axe', 5, '半馬橫掃斧', 'rare', 40, 'neutral', '{"atk":48,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '半程馬拉松選手信賴之選，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 500),
  ('hk_axe_t6', 'hk_axe', 6, '全馬破陣斧', 'rare', 50, 'neutral', '{"atk":55,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全程馬拉松賽場的主力裝備，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 600),
  ('hk_axe_t7', 'hk_axe', 7, '先鋒獵殺斧', 'epic', 60, 'neutral', '{"atk":70,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '城市巡迴賽冠軍愛用款，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 700),
  ('hk_axe_t8', 'hk_axe', 8, '破風毀滅斧', 'epic', 70, 'neutral', '{"atk":79,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '極限配速挑戰者專屬，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 800),
  ('hk_axe_t9', 'hk_axe', 9, '巡迴屠戮斧', 'epic', 80, 'neutral', '{"atk":96,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '全國巡迴賽事的頂尖裝備，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 900),
  ('hk_axe_t10', 'hk_axe', 10, '傳說滅世巨斧', 'legendary', 90, 'neutral', '{"atk":103,"interval_pct":25,"splash_pct":40,"size_bonus":{"small":0,"medium":0,"large":5},"element":"neutral"}'::jsonb, '傳說等級，只在最終賽場現身，掄動間隔較長，卻能橫掃左右鄰近目標，對大型目標傷害更高。', TRUE, 1000)
ON CONFLICT (id) DO UPDATE SET
  type_id = EXCLUDED.type_id,
  tier = EXCLUDED.tier,
  name = EXCLUDED.name,
  rarity = EXCLUDED.rarity,
  level_req = EXCLUDED.level_req,
  element = EXCLUDED.element,
  profile = EXCLUDED.profile,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

-- <<< WEAPONS SEED <<<

-- ---------------------------------------------------------------------------
-- 3) player_equipment：目前只有 weapon 一個 slot（未來防具再加，CHECK 值域跟著擴充）。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS player_equipment (
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slot        TEXT NOT NULL CHECK (slot IN ('weapon')),
  item_id     TEXT NOT NULL REFERENCES rpg_weapons(id),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, slot)
);

INSERT INTO schema_migrations (version) VALUES ('183') ON CONFLICT DO NOTHING;
