-- 184_rpg_armor.sql
-- DORPG P8：防具系統（五部位依職業各一套＋通用飾品分 5 級，契約見
-- scratchpad/dorpg_p8/{CONTRACT.md,WIRE.md}）。本檔只建表／改約束；6 職業×5 部位×10 級（300）＋
-- 通用飾品 18 效果×5 級（90）共 390 件的 seed 由另一個 Workflow 產生，貼進下方兩對標記之間
-- （刻意放在 rpg_armor_items 建好之後，seed 才有表可插）。
--
-- ⚠️ 使用者手動套用到 Neon，不得自行套用；CREATE TABLE IF NOT EXISTS／索引 IF NOT EXISTS／
-- 約束一律先 DROP IF EXISTS 再重建，可安全重複執行。依規範（db-before-code-push.md）等使用者
-- 確認已套用才能 push 依賴這些新表/約束的程式碼。

-- ---------------------------------------------------------------------------
-- 1) rpg_armor_items：頭盔/手套/衣服/褲裙/鞋子（job_id NOT NULL，每職業各 10 級）＋通用飾品
--    （job_id NULL，18 效果×5 級）共用同一張表（CONTRACT §1）。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS rpg_armor_items (
  id            TEXT PRIMARY KEY,                 -- 防具 <job短碼>_<slot>_t<tier>；飾品 acc_<effect>_t<tier>
  job_id        TEXT NULL REFERENCES rpg_jobs(id), -- NULL＝通用（只有飾品是 NULL）
  slot          TEXT NOT NULL CHECK (slot IN ('helmet','gloves','armor','legs','boots','accessory')),
  tier          INT NOT NULL CHECK (tier BETWEEN 1 AND 10), -- 防具 1..10；飾品 1..5（應用層再收緊，見 armor.go ArmorRow.Validate）
  name          TEXT NOT NULL,
  rarity        TEXT NOT NULL DEFAULT 'common',   -- 防具 t1-3 common／4-6 rare／7-9 epic／10 legendary；飾品 t1 common／t2-3 rare／t4 epic／t5 legendary
  level_req     INT NOT NULL DEFAULT 1,           -- 防具 tier→1/10/20/30/40/50/60/70/80/90；飾品 tier→1/20/40/60/80
  profile       JSONB NOT NULL DEFAULT '{}',      -- ArmorProfile，見 internal/rpg/armor.go；缺欄位＝中性值
  description   TEXT NOT NULL DEFAULT '',
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rpg_armor_items_job_slot_tier ON rpg_armor_items(job_id, slot, tier);

-- >>> ARMOR SEED (generated) >>>
-- DORPG P8：rpg_armor_items (390 = 300 防具 + 90 飾品)
-- 產生自 scratchpad/dorpg_p8/armor_all.json（已通過 validate_armor.py，0 錯誤）

INSERT INTO rpg_armor_items (id, job_id, slot, tier, name, rarity, level_req, profile, description, is_active, sort_order)
VALUES
  ('acc_hp_t1', NULL, 'accessory', 1, '標準心率帶', 'common', 1, '{"hp_pct":4}'::jsonb, '心率帶，監測心肺負荷、強化最大心肺續航，提升HP上限 4%。', TRUE, 6010),
  ('acc_mp_t1', NULL, 'accessory', 1, '標準運動GPS錶', 'common', 1, '{"mp_pct":4}'::jsonb, '運動GPS錶，精準配速管理、強化精神續航，提升MP上限 4%。', TRUE, 6010),
  ('acc_str_t1', NULL, 'accessory', 1, '標準壓縮臂套', 'common', 1, '{"str":2}'::jsonb, '壓縮臂套，加強上肢肌力與擺臂力道，提升STR +2。', TRUE, 6010),
  ('acc_vit_t1', NULL, 'accessory', 1, '標準水壺腰帶', 'common', 1, '{"vit":2}'::jsonb, '水壺腰帶，全程無虞的補水後盾，強化體質耐力，提升VIT +2。', TRUE, 6010),
  ('acc_dex_t1', NULL, 'accessory', 1, '標準五趾機能襪', 'common', 1, '{"dex":2}'::jsonb, '五趾機能襪，提升足部抓地與步伐精準度，提升DEX +2。', TRUE, 6010),
  ('acc_agi_t1', NULL, 'accessory', 1, '標準壓縮小腿套', 'common', 1, '{"agi":2}'::jsonb, '壓縮小腿套，加速血液回流、維持配速穩定，提升AGI +2。', TRUE, 6010),
  ('acc_int_t1', NULL, 'accessory', 1, '標準骨傳導耳機', 'common', 1, '{"int":2}'::jsonb, '骨傳導耳機，開放式聽覺兼顧安全，賽場專注力更集中，提升INT +2。', TRUE, 6010),
  ('acc_luk_t1', NULL, 'accessory', 1, '標準選手號碼布', 'common', 1, '{"luk":2}'::jsonb, '選手號碼布，上場戰袍的號碼，帶來競賽好手氣，提升LUK +2。', TRUE, 6010),
  ('acc_interval_t1', NULL, 'accessory', 1, '標準提神咖啡凍', 'common', 1, '{"interval_pct":-3}'::jsonb, '提神咖啡凍，中樞神經刺激，反應速度更快一拍，縮短攻擊間隔 3%。', TRUE, 6010),
  ('acc_crit_t1', NULL, 'accessory', 1, '標準抗UV運動墨鏡', 'common', 1, '{"crit_pct":2}'::jsonb, '抗UV運動墨鏡，視野清晰，看得更準、出手更果斷，提升爆擊率 +2%。', TRUE, 6010),
  ('acc_critdmg_t1', NULL, 'accessory', 1, '標準碳板跑鞋墊', 'common', 1, '{"crit_dmg_pct":6}'::jsonb, '碳板跑鞋墊，推進力加乘，一擊必殺加重，提升爆擊傷害 +6%。', TRUE, 6010),
  ('acc_mpcost_t1', NULL, 'accessory', 1, '標準肌能貼布', 'common', 1, '{"mp_cost_reduce_pct":5}'::jsonb, '肌能貼布，減少動作負擔，讓技能施展更省力，降低技能MP消耗 5%。', TRUE, 6010),
  ('acc_hpregen_t1', NULL, 'accessory', 1, '標準能量膠', 'common', 1, '{"hp_regen_pct_per_5s":1}'::jsonb, '能量膠，快速醣分補給，持續回復體力，戰鬥中每5秒回復HP上限 1%。', TRUE, 6010),
  ('acc_mpregen_t1', NULL, 'accessory', 1, '標準鹽錠', 'common', 1, '{"mp_regen_pct_per_5s":1}'::jsonb, '鹽錠，定時服用電解質，持續回復精神續航，戰鬥中每5秒回復MP上限 1%。', TRUE, 6010),
  ('acc_atk_t1', NULL, 'accessory', 1, '標準反光臂環', 'common', 1, '{"atk_pct":2}'::jsonb, '反光臂環，夜跑安全兼具氣勢，出拳更有份量，提升ATK +2%。', TRUE, 6010),
  ('acc_matk_t1', NULL, 'accessory', 1, '標準專注運動頭帶', 'common', 1, '{"matk_pct":2}'::jsonb, '專注運動頭帶，專注力集中，施法更加銳利，提升MATK +2%。', TRUE, 6010),
  ('acc_dmgtaken_t1', NULL, 'accessory', 1, '標準防磨膏', 'common', 1, '{"damage_taken_pct":-3}'::jsonb, '防磨膏，減少摩擦傷害，跑起來更加從容，降低所受傷害 3%。', TRUE, 6010),
  ('acc_elemres_t1', NULL, 'accessory', 1, '標準排汗機能運動帽', 'common', 1, '{"element_resist_pct":2}'::jsonb, '排汗機能運動帽，抵禦日曬風雨，全天候作戰更安心，降低所受屬性傷害 2%。', TRUE, 6010),
  ('acc_hp_t2', NULL, 'accessory', 2, '強化心率帶', 'rare', 20, '{"hp_pct":6}'::jsonb, '心率帶，監測心肺負荷、強化最大心肺續航，提升HP上限 6%。', TRUE, 6020),
  ('acc_mp_t2', NULL, 'accessory', 2, '強化運動GPS錶', 'rare', 20, '{"mp_pct":6}'::jsonb, '運動GPS錶，精準配速管理、強化精神續航，提升MP上限 6%。', TRUE, 6020),
  ('acc_str_t2', NULL, 'accessory', 2, '強化壓縮臂套', 'rare', 20, '{"str":4}'::jsonb, '壓縮臂套，加強上肢肌力與擺臂力道，提升STR +4。', TRUE, 6020),
  ('acc_vit_t2', NULL, 'accessory', 2, '強化水壺腰帶', 'rare', 20, '{"vit":4}'::jsonb, '水壺腰帶，全程無虞的補水後盾，強化體質耐力，提升VIT +4。', TRUE, 6020),
  ('acc_dex_t2', NULL, 'accessory', 2, '強化五趾機能襪', 'rare', 20, '{"dex":4}'::jsonb, '五趾機能襪，提升足部抓地與步伐精準度，提升DEX +4。', TRUE, 6020),
  ('acc_agi_t2', NULL, 'accessory', 2, '強化壓縮小腿套', 'rare', 20, '{"agi":4}'::jsonb, '壓縮小腿套，加速血液回流、維持配速穩定，提升AGI +4。', TRUE, 6020),
  ('acc_int_t2', NULL, 'accessory', 2, '強化骨傳導耳機', 'rare', 20, '{"int":4}'::jsonb, '骨傳導耳機，開放式聽覺兼顧安全，賽場專注力更集中，提升INT +4。', TRUE, 6020),
  ('acc_luk_t2', NULL, 'accessory', 2, '強化選手號碼布', 'rare', 20, '{"luk":4}'::jsonb, '選手號碼布，上場戰袍的號碼，帶來競賽好手氣，提升LUK +4。', TRUE, 6020),
  ('acc_interval_t2', NULL, 'accessory', 2, '強化提神咖啡凍', 'rare', 20, '{"interval_pct":-5}'::jsonb, '提神咖啡凍，中樞神經刺激，反應速度更快一拍，縮短攻擊間隔 5%。', TRUE, 6020),
  ('acc_crit_t2', NULL, 'accessory', 2, '強化抗UV運動墨鏡', 'rare', 20, '{"crit_pct":4}'::jsonb, '抗UV運動墨鏡，視野清晰，看得更準、出手更果斷，提升爆擊率 +4%。', TRUE, 6020),
  ('acc_critdmg_t2', NULL, 'accessory', 2, '強化碳板跑鞋墊', 'rare', 20, '{"crit_dmg_pct":11}'::jsonb, '碳板跑鞋墊，推進力加乘，一擊必殺加重，提升爆擊傷害 +11%。', TRUE, 6020),
  ('acc_mpcost_t2', NULL, 'accessory', 2, '強化肌能貼布', 'rare', 20, '{"mp_cost_reduce_pct":10}'::jsonb, '肌能貼布，減少動作負擔，讓技能施展更省力，降低技能MP消耗 10%。', TRUE, 6020),
  ('acc_hpregen_t2', NULL, 'accessory', 2, '強化能量膠', 'rare', 20, '{"hp_regen_pct_per_5s":2}'::jsonb, '能量膠，快速醣分補給，持續回復體力，戰鬥中每5秒回復HP上限 2%。', TRUE, 6020),
  ('acc_mpregen_t2', NULL, 'accessory', 2, '強化鹽錠', 'rare', 20, '{"mp_regen_pct_per_5s":2}'::jsonb, '鹽錠，定時服用電解質，持續回復精神續航，戰鬥中每5秒回復MP上限 2%。', TRUE, 6020),
  ('acc_atk_t2', NULL, 'accessory', 2, '強化反光臂環', 'rare', 20, '{"atk_pct":4}'::jsonb, '反光臂環，夜跑安全兼具氣勢，出拳更有份量，提升ATK +4%。', TRUE, 6020),
  ('acc_matk_t2', NULL, 'accessory', 2, '強化專注運動頭帶', 'rare', 20, '{"matk_pct":4}'::jsonb, '專注運動頭帶，專注力集中，施法更加銳利，提升MATK +4%。', TRUE, 6020),
  ('acc_dmgtaken_t2', NULL, 'accessory', 2, '強化防磨膏', 'rare', 20, '{"damage_taken_pct":-5}'::jsonb, '防磨膏，減少摩擦傷害，跑起來更加從容，降低所受傷害 5%。', TRUE, 6020),
  ('acc_elemres_t2', NULL, 'accessory', 2, '強化排汗機能運動帽', 'rare', 20, '{"element_resist_pct":4}'::jsonb, '排汗機能運動帽，抵禦日曬風雨，全天候作戰更安心，降低所受屬性傷害 4%。', TRUE, 6020),
  ('acc_hp_t3', NULL, 'accessory', 3, '專業心率帶', 'rare', 40, '{"hp_pct":8}'::jsonb, '心率帶，監測心肺負荷、強化最大心肺續航，提升HP上限 8%。', TRUE, 6030),
  ('acc_mp_t3', NULL, 'accessory', 3, '專業運動GPS錶', 'rare', 40, '{"mp_pct":8}'::jsonb, '運動GPS錶，精準配速管理、強化精神續航，提升MP上限 8%。', TRUE, 6030),
  ('acc_str_t3', NULL, 'accessory', 3, '專業壓縮臂套', 'rare', 40, '{"str":6}'::jsonb, '壓縮臂套，加強上肢肌力與擺臂力道，提升STR +6。', TRUE, 6030),
  ('acc_vit_t3', NULL, 'accessory', 3, '專業水壺腰帶', 'rare', 40, '{"vit":6}'::jsonb, '水壺腰帶，全程無虞的補水後盾，強化體質耐力，提升VIT +6。', TRUE, 6030),
  ('acc_dex_t3', NULL, 'accessory', 3, '專業五趾機能襪', 'rare', 40, '{"dex":6}'::jsonb, '五趾機能襪，提升足部抓地與步伐精準度，提升DEX +6。', TRUE, 6030),
  ('acc_agi_t3', NULL, 'accessory', 3, '專業壓縮小腿套', 'rare', 40, '{"agi":6}'::jsonb, '壓縮小腿套，加速血液回流、維持配速穩定，提升AGI +6。', TRUE, 6030),
  ('acc_int_t3', NULL, 'accessory', 3, '專業骨傳導耳機', 'rare', 40, '{"int":6}'::jsonb, '骨傳導耳機，開放式聽覺兼顧安全，賽場專注力更集中，提升INT +6。', TRUE, 6030),
  ('acc_luk_t3', NULL, 'accessory', 3, '專業選手號碼布', 'rare', 40, '{"luk":6}'::jsonb, '選手號碼布，上場戰袍的號碼，帶來競賽好手氣，提升LUK +6。', TRUE, 6030),
  ('acc_interval_t3', NULL, 'accessory', 3, '專業提神咖啡凍', 'rare', 40, '{"interval_pct":-8}'::jsonb, '提神咖啡凍，中樞神經刺激，反應速度更快一拍，縮短攻擊間隔 8%。', TRUE, 6030),
  ('acc_crit_t3', NULL, 'accessory', 3, '專業抗UV運動墨鏡', 'rare', 40, '{"crit_pct":5}'::jsonb, '抗UV運動墨鏡，視野清晰，看得更準、出手更果斷，提升爆擊率 +5%。', TRUE, 6030),
  ('acc_critdmg_t3', NULL, 'accessory', 3, '專業碳板跑鞋墊', 'rare', 40, '{"crit_dmg_pct":16}'::jsonb, '碳板跑鞋墊，推進力加乘，一擊必殺加重，提升爆擊傷害 +16%。', TRUE, 6030),
  ('acc_mpcost_t3', NULL, 'accessory', 3, '專業肌能貼布', 'rare', 40, '{"mp_cost_reduce_pct":15}'::jsonb, '肌能貼布，減少動作負擔，讓技能施展更省力，降低技能MP消耗 15%。', TRUE, 6030),
  ('acc_hpregen_t3', NULL, 'accessory', 3, '專業能量膠', 'rare', 40, '{"hp_regen_pct_per_5s":3}'::jsonb, '能量膠，快速醣分補給，持續回復體力，戰鬥中每5秒回復HP上限 3%。', TRUE, 6030),
  ('acc_mpregen_t3', NULL, 'accessory', 3, '專業鹽錠', 'rare', 40, '{"mp_regen_pct_per_5s":3}'::jsonb, '鹽錠，定時服用電解質，持續回復精神續航，戰鬥中每5秒回復MP上限 3%。', TRUE, 6030),
  ('acc_atk_t3', NULL, 'accessory', 3, '專業反光臂環', 'rare', 40, '{"atk_pct":6}'::jsonb, '反光臂環，夜跑安全兼具氣勢，出拳更有份量，提升ATK +6%。', TRUE, 6030),
  ('acc_matk_t3', NULL, 'accessory', 3, '專業專注運動頭帶', 'rare', 40, '{"matk_pct":6}'::jsonb, '專注運動頭帶，專注力集中，施法更加銳利，提升MATK +6%。', TRUE, 6030),
  ('acc_dmgtaken_t3', NULL, 'accessory', 3, '專業防磨膏', 'rare', 40, '{"damage_taken_pct":-8}'::jsonb, '防磨膏，減少摩擦傷害，跑起來更加從容，降低所受傷害 8%。', TRUE, 6030),
  ('acc_elemres_t3', NULL, 'accessory', 3, '專業排汗機能運動帽', 'rare', 40, '{"element_resist_pct":5}'::jsonb, '排汗機能運動帽，抵禦日曬風雨，全天候作戰更安心，降低所受屬性傷害 5%。', TRUE, 6030),
  ('acc_hp_t4', NULL, 'accessory', 4, '菁英心率帶', 'epic', 60, '{"hp_pct":10}'::jsonb, '心率帶，監測心肺負荷、強化最大心肺續航，提升HP上限 10%。', TRUE, 6040),
  ('acc_mp_t4', NULL, 'accessory', 4, '菁英運動GPS錶', 'epic', 60, '{"mp_pct":10}'::jsonb, '運動GPS錶，精準配速管理、強化精神續航，提升MP上限 10%。', TRUE, 6040),
  ('acc_str_t4', NULL, 'accessory', 4, '菁英壓縮臂套', 'epic', 60, '{"str":8}'::jsonb, '壓縮臂套，加強上肢肌力與擺臂力道，提升STR +8。', TRUE, 6040),
  ('acc_vit_t4', NULL, 'accessory', 4, '菁英水壺腰帶', 'epic', 60, '{"vit":8}'::jsonb, '水壺腰帶，全程無虞的補水後盾，強化體質耐力，提升VIT +8。', TRUE, 6040),
  ('acc_dex_t4', NULL, 'accessory', 4, '菁英五趾機能襪', 'epic', 60, '{"dex":8}'::jsonb, '五趾機能襪，提升足部抓地與步伐精準度，提升DEX +8。', TRUE, 6040),
  ('acc_agi_t4', NULL, 'accessory', 4, '菁英壓縮小腿套', 'epic', 60, '{"agi":8}'::jsonb, '壓縮小腿套，加速血液回流、維持配速穩定，提升AGI +8。', TRUE, 6040),
  ('acc_int_t4', NULL, 'accessory', 4, '菁英骨傳導耳機', 'epic', 60, '{"int":8}'::jsonb, '骨傳導耳機，開放式聽覺兼顧安全，賽場專注力更集中，提升INT +8。', TRUE, 6040),
  ('acc_luk_t4', NULL, 'accessory', 4, '菁英選手號碼布', 'epic', 60, '{"luk":8}'::jsonb, '選手號碼布，上場戰袍的號碼，帶來競賽好手氣，提升LUK +8。', TRUE, 6040),
  ('acc_interval_t4', NULL, 'accessory', 4, '菁英提神咖啡凍', 'epic', 60, '{"interval_pct":-10}'::jsonb, '提神咖啡凍，中樞神經刺激，反應速度更快一拍，縮短攻擊間隔 10%。', TRUE, 6040),
  ('acc_crit_t4', NULL, 'accessory', 4, '菁英抗UV運動墨鏡', 'epic', 60, '{"crit_pct":7}'::jsonb, '抗UV運動墨鏡，視野清晰，看得更準、出手更果斷，提升爆擊率 +7%。', TRUE, 6040),
  ('acc_critdmg_t4', NULL, 'accessory', 4, '菁英碳板跑鞋墊', 'epic', 60, '{"crit_dmg_pct":20}'::jsonb, '碳板跑鞋墊，推進力加乘，一擊必殺加重，提升爆擊傷害 +20%。', TRUE, 6040),
  ('acc_mpcost_t4', NULL, 'accessory', 4, '菁英肌能貼布', 'epic', 60, '{"mp_cost_reduce_pct":20}'::jsonb, '肌能貼布，減少動作負擔，讓技能施展更省力，降低技能MP消耗 20%。', TRUE, 6040),
  ('acc_hpregen_t4', NULL, 'accessory', 4, '菁英能量膠', 'epic', 60, '{"hp_regen_pct_per_5s":3}'::jsonb, '能量膠，快速醣分補給，持續回復體力，戰鬥中每5秒回復HP上限 3%。', TRUE, 6040),
  ('acc_mpregen_t4', NULL, 'accessory', 4, '菁英鹽錠', 'epic', 60, '{"mp_regen_pct_per_5s":3}'::jsonb, '鹽錠，定時服用電解質，持續回復精神續航，戰鬥中每5秒回復MP上限 3%。', TRUE, 6040),
  ('acc_atk_t4', NULL, 'accessory', 4, '菁英反光臂環', 'epic', 60, '{"atk_pct":8}'::jsonb, '反光臂環，夜跑安全兼具氣勢，出拳更有份量，提升ATK +8%。', TRUE, 6040),
  ('acc_matk_t4', NULL, 'accessory', 4, '菁英專注運動頭帶', 'epic', 60, '{"matk_pct":8}'::jsonb, '專注運動頭帶，專注力集中，施法更加銳利，提升MATK +8%。', TRUE, 6040),
  ('acc_dmgtaken_t4', NULL, 'accessory', 4, '菁英防磨膏', 'epic', 60, '{"damage_taken_pct":-10}'::jsonb, '防磨膏，減少摩擦傷害，跑起來更加從容，降低所受傷害 10%。', TRUE, 6040),
  ('acc_elemres_t4', NULL, 'accessory', 4, '菁英排汗機能運動帽', 'epic', 60, '{"element_resist_pct":8}'::jsonb, '排汗機能運動帽，抵禦日曬風雨，全天候作戰更安心，降低所受屬性傷害 8%。', TRUE, 6040),
  ('acc_hp_t5', NULL, 'accessory', 5, '傳說心率帶', 'legendary', 80, '{"hp_pct":12}'::jsonb, '心率帶，監測心肺負荷、強化最大心肺續航，提升HP上限 12%。', TRUE, 6050),
  ('acc_mp_t5', NULL, 'accessory', 5, '傳說運動GPS錶', 'legendary', 80, '{"mp_pct":12}'::jsonb, '運動GPS錶，精準配速管理、強化精神續航，提升MP上限 12%。', TRUE, 6050),
  ('acc_str_t5', NULL, 'accessory', 5, '傳說壓縮臂套', 'legendary', 80, '{"str":10}'::jsonb, '壓縮臂套，加強上肢肌力與擺臂力道，提升STR +10。', TRUE, 6050),
  ('acc_vit_t5', NULL, 'accessory', 5, '傳說水壺腰帶', 'legendary', 80, '{"vit":10}'::jsonb, '水壺腰帶，全程無虞的補水後盾，強化體質耐力，提升VIT +10。', TRUE, 6050),
  ('acc_dex_t5', NULL, 'accessory', 5, '傳說五趾機能襪', 'legendary', 80, '{"dex":10}'::jsonb, '五趾機能襪，提升足部抓地與步伐精準度，提升DEX +10。', TRUE, 6050),
  ('acc_agi_t5', NULL, 'accessory', 5, '傳說壓縮小腿套', 'legendary', 80, '{"agi":10}'::jsonb, '壓縮小腿套，加速血液回流、維持配速穩定，提升AGI +10。', TRUE, 6050),
  ('acc_int_t5', NULL, 'accessory', 5, '傳說骨傳導耳機', 'legendary', 80, '{"int":10}'::jsonb, '骨傳導耳機，開放式聽覺兼顧安全，賽場專注力更集中，提升INT +10。', TRUE, 6050),
  ('acc_luk_t5', NULL, 'accessory', 5, '傳說選手號碼布', 'legendary', 80, '{"luk":10}'::jsonb, '選手號碼布，上場戰袍的號碼，帶來競賽好手氣，提升LUK +10。', TRUE, 6050),
  ('acc_interval_t5', NULL, 'accessory', 5, '傳說提神咖啡凍', 'legendary', 80, '{"interval_pct":-12}'::jsonb, '提神咖啡凍，中樞神經刺激，反應速度更快一拍，縮短攻擊間隔 12%。', TRUE, 6050),
  ('acc_crit_t5', NULL, 'accessory', 5, '傳說抗UV運動墨鏡', 'legendary', 80, '{"crit_pct":8}'::jsonb, '抗UV運動墨鏡，視野清晰，看得更準、出手更果斷，提升爆擊率 +8%。', TRUE, 6050),
  ('acc_critdmg_t5', NULL, 'accessory', 5, '傳說碳板跑鞋墊', 'legendary', 80, '{"crit_dmg_pct":25}'::jsonb, '碳板跑鞋墊，推進力加乘，一擊必殺加重，提升爆擊傷害 +25%。', TRUE, 6050),
  ('acc_mpcost_t5', NULL, 'accessory', 5, '傳說肌能貼布', 'legendary', 80, '{"mp_cost_reduce_pct":25}'::jsonb, '肌能貼布，減少動作負擔，讓技能施展更省力，降低技能MP消耗 25%。', TRUE, 6050),
  ('acc_hpregen_t5', NULL, 'accessory', 5, '傳說能量膠', 'legendary', 80, '{"hp_regen_pct_per_5s":4}'::jsonb, '能量膠，快速醣分補給，持續回復體力，戰鬥中每5秒回復HP上限 4%。', TRUE, 6050),
  ('acc_mpregen_t5', NULL, 'accessory', 5, '傳說鹽錠', 'legendary', 80, '{"mp_regen_pct_per_5s":4}'::jsonb, '鹽錠，定時服用電解質，持續回復精神續航，戰鬥中每5秒回復MP上限 4%。', TRUE, 6050),
  ('acc_atk_t5', NULL, 'accessory', 5, '傳說反光臂環', 'legendary', 80, '{"atk_pct":10}'::jsonb, '反光臂環，夜跑安全兼具氣勢，出拳更有份量，提升ATK +10%。', TRUE, 6050),
  ('acc_matk_t5', NULL, 'accessory', 5, '傳說專注運動頭帶', 'legendary', 80, '{"matk_pct":10}'::jsonb, '專注運動頭帶，專注力集中，施法更加銳利，提升MATK +10%。', TRUE, 6050),
  ('acc_dmgtaken_t5', NULL, 'accessory', 5, '傳說防磨膏', 'legendary', 80, '{"damage_taken_pct":-12}'::jsonb, '防磨膏，減少摩擦傷害，跑起來更加從容，降低所受傷害 12%。', TRUE, 6050),
  ('acc_elemres_t5', NULL, 'accessory', 5, '傳說排汗機能運動帽', 'legendary', 80, '{"element_resist_pct":10}'::jsonb, '排汗機能運動帽，抵禦日曬風雨，全天候作戰更安心，降低所受屬性傷害 10%。', TRUE, 6050),
  ('hk_helmet_t1', 'heavy_knight', 'helmet', 1, '重甲棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '重騎士專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 11010),
  ('hk_helmet_t2', 'heavy_knight', 'helmet', 2, '重甲排汗運動帽', 'common', 10, '{"def":1,"int":1}'::jsonb, '重騎士專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 11020),
  ('hk_helmet_t3', 'heavy_knight', 'helmet', 3, '重甲透氣網眼帽', 'common', 20, '{"def":2,"int":2}'::jsonb, '重騎士專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+2。', TRUE, 11030),
  ('hk_helmet_t4', 'heavy_knight', 'helmet', 4, '重甲遮陽跑帽', 'rare', 30, '{"def":3,"int":2}'::jsonb, '重騎士專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+2。', TRUE, 11040),
  ('hk_helmet_t5', 'heavy_knight', 'helmet', 5, '重甲反光夜跑帽', 'rare', 40, '{"def":3,"int":2}'::jsonb, '重騎士專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+2。', TRUE, 11050),
  ('hk_helmet_t6', 'heavy_knight', 'helmet', 6, '重甲輕量競速帽', 'rare', 50, '{"def":4,"int":3}'::jsonb, '重騎士專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+3。', TRUE, 11060),
  ('hk_helmet_t7', 'heavy_knight', 'helmet', 7, '重甲空力導風帽', 'epic', 60, '{"def":5,"int":3}'::jsonb, '重騎士專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+3。', TRUE, 11070),
  ('hk_helmet_t8', 'heavy_knight', 'helmet', 8, '重甲職業競賽帽', 'epic', 70, '{"def":6,"int":4}'::jsonb, '重騎士專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+6、INT+4。', TRUE, 11080),
  ('hk_helmet_t9', 'heavy_knight', 'helmet', 9, '重甲國手戰盔', 'epic', 80, '{"def":6,"int":4}'::jsonb, '重騎士專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+6、INT+4。', TRUE, 11090),
  ('hk_helmet_t10', 'heavy_knight', 'helmet', 10, '重甲巔峰競速盔', 'legendary', 90, '{"def":7,"int":5}'::jsonb, '重騎士專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+7、INT+5。', TRUE, 11100),
  ('hk_gloves_t1', 'heavy_knight', 'gloves', 1, '重甲棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '重騎士專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 12010),
  ('hk_gloves_t2', 'heavy_knight', 'gloves', 2, '重甲排汗運動手套', 'common', 10, '{"def":1,"str":2}'::jsonb, '重騎士專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 12020),
  ('hk_gloves_t3', 'heavy_knight', 'gloves', 3, '重甲透氣網眼手套', 'common', 20, '{"def":1,"str":4}'::jsonb, '重騎士專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+4。', TRUE, 12030),
  ('hk_gloves_t4', 'heavy_knight', 'gloves', 4, '重甲防滑訓練手套', 'rare', 30, '{"def":2,"str":5}'::jsonb, '重騎士專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+5。', TRUE, 12040),
  ('hk_gloves_t5', 'heavy_knight', 'gloves', 5, '重甲觸控機能手套', 'rare', 40, '{"def":3,"str":6}'::jsonb, '重騎士專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+6。', TRUE, 12050),
  ('hk_gloves_t6', 'heavy_knight', 'gloves', 6, '重甲輕量競速手套', 'rare', 50, '{"def":4,"str":7}'::jsonb, '重騎士專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+7。', TRUE, 12060),
  ('hk_gloves_t7', 'heavy_knight', 'gloves', 7, '重甲抓地競賽手套', 'epic', 60, '{"def":4,"str":8}'::jsonb, '重騎士專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+8。', TRUE, 12070),
  ('hk_gloves_t8', 'heavy_knight', 'gloves', 8, '重甲職業選手手套', 'epic', 70, '{"def":5,"str":9}'::jsonb, '重騎士專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+5、STR+9。', TRUE, 12080),
  ('hk_gloves_t9', 'heavy_knight', 'gloves', 9, '重甲國手戰鬥手套', 'epic', 80, '{"def":5,"str":10}'::jsonb, '重騎士專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+5、STR+10。', TRUE, 12090),
  ('hk_gloves_t10', 'heavy_knight', 'gloves', 10, '重甲巔峰競速護手', 'legendary', 90, '{"def":6,"str":11}'::jsonb, '重騎士專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+6、STR+11。', TRUE, 12100),
  ('hk_armor_t1', 'heavy_knight', 'armor', 1, '重甲棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":3}'::jsonb, '重騎士專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+3%。', TRUE, 13010),
  ('hk_armor_t2', 'heavy_knight', 'armor', 2, '重甲機能排汗衣', 'common', 10, '{"def":2,"vit":2,"hp_pct":4}'::jsonb, '重騎士專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+2、VIT+2、HP上限+4%。', TRUE, 13020),
  ('hk_armor_t3', 'heavy_knight', 'armor', 3, '重甲涼感訓練衣', 'common', 20, '{"def":4,"vit":3,"hp_pct":5}'::jsonb, '重騎士專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+4、VIT+3、HP上限+5%。', TRUE, 13030),
  ('hk_armor_t4', 'heavy_knight', 'armor', 4, '重甲壓縮訓練衣', 'rare', 30, '{"def":6,"vit":4,"hp_pct":7}'::jsonb, '重騎士專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+6、VIT+4、HP上限+7%。', TRUE, 13040),
  ('hk_armor_t5', 'heavy_knight', 'armor', 5, '重甲輕量競速衣', 'rare', 40, '{"def":8,"vit":5,"hp_pct":8}'::jsonb, '重騎士專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+8、VIT+5、HP上限+8%。', TRUE, 13050),
  ('hk_armor_t6', 'heavy_knight', 'armor', 6, '重甲競賽背心', 'rare', 50, '{"def":10,"vit":6,"hp_pct":10}'::jsonb, '重騎士專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+10、VIT+6、HP上限+10%。', TRUE, 13060),
  ('hk_armor_t7', 'heavy_knight', 'armor', 7, '重甲空力競速背心', 'epic', 60, '{"def":11,"vit":7,"hp_pct":11}'::jsonb, '重騎士專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+11、VIT+7、HP上限+11%。', TRUE, 13070),
  ('hk_armor_t8', 'heavy_knight', 'armor', 8, '重甲職業選手戰袍', 'epic', 70, '{"def":13,"vit":8,"hp_pct":13}'::jsonb, '重騎士專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+13、VIT+8、HP上限+13%。', TRUE, 13080),
  ('hk_armor_t9', 'heavy_knight', 'armor', 9, '重甲國手戰袍', 'epic', 80, '{"def":15,"vit":9,"hp_pct":14}'::jsonb, '重騎士專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+15、VIT+9、HP上限+14%。', TRUE, 13090),
  ('hk_armor_t10', 'heavy_knight', 'armor', 10, '重甲巔峰競速戰甲', 'legendary', 90, '{"def":16,"vit":10,"hp_pct":16}'::jsonb, '重騎士專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+16、VIT+10、HP上限+16%。', TRUE, 13100),
  ('hk_legs_t1', 'heavy_knight', 'legs', 1, '重甲棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '重騎士專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 14010),
  ('hk_legs_t2', 'heavy_knight', 'legs', 2, '重甲排汗短褲', 'common', 10, '{"def":2,"vit":2,"hp_pct":2}'::jsonb, '重騎士專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+2%。', TRUE, 14020),
  ('hk_legs_t3', 'heavy_knight', 'legs', 3, '重甲透氣訓練褲', 'common', 20, '{"def":3,"vit":3,"hp_pct":3}'::jsonb, '重騎士專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+3、VIT+3、HP上限+3%。', TRUE, 14030),
  ('hk_legs_t4', 'heavy_knight', 'legs', 4, '重甲壓縮訓練褲', 'rare', 30, '{"def":4,"vit":3,"hp_pct":4}'::jsonb, '重騎士專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+4%。', TRUE, 14040),
  ('hk_legs_t5', 'heavy_knight', 'legs', 5, '重甲輕量競速褲', 'rare', 40, '{"def":6,"vit":4,"hp_pct":5}'::jsonb, '重騎士專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+5%。', TRUE, 14050),
  ('hk_legs_t6', 'heavy_knight', 'legs', 6, '重甲分段壓縮褲', 'rare', 50, '{"def":7,"vit":5,"hp_pct":6}'::jsonb, '重騎士專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+5、HP上限+6%。', TRUE, 14060),
  ('hk_legs_t7', 'heavy_knight', 'legs', 7, '重甲空力競速褲', 'epic', 60, '{"def":8,"vit":6,"hp_pct":7}'::jsonb, '重騎士專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+8、VIT+6、HP上限+7%。', TRUE, 14070),
  ('hk_legs_t8', 'heavy_knight', 'legs', 8, '重甲職業選手戰褲', 'epic', 70, '{"def":9,"vit":6,"hp_pct":8}'::jsonb, '重騎士專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+9、VIT+6、HP上限+8%。', TRUE, 14080),
  ('hk_legs_t9', 'heavy_knight', 'legs', 9, '重甲國手戰褲', 'epic', 80, '{"def":10,"vit":7,"hp_pct":9}'::jsonb, '重騎士專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+10、VIT+7、HP上限+9%。', TRUE, 14090),
  ('hk_legs_t10', 'heavy_knight', 'legs', 10, '重甲巔峰競速護甲褲', 'legendary', 90, '{"def":12,"vit":8,"hp_pct":10}'::jsonb, '重騎士專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+12、VIT+8、HP上限+10%。', TRUE, 14100),
  ('hk_boots_t1', 'heavy_knight', 'boots', 1, '重甲帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '重騎士專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 15010),
  ('hk_boots_t2', 'heavy_knight', 'boots', 2, '重甲慢跑鞋', 'common', 10, '{"def":1,"agi":1,"dex":1}'::jsonb, '重騎士專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 15020),
  ('hk_boots_t3', 'heavy_knight', 'boots', 3, '重甲緩震訓練鞋', 'common', 20, '{"def":1,"agi":2,"dex":2}'::jsonb, '重騎士專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 15030),
  ('hk_boots_t4', 'heavy_knight', 'boots', 4, '重甲透氣競速鞋', 'rare', 30, '{"def":2,"agi":2,"dex":2}'::jsonb, '重騎士專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+2、DEX+2。', TRUE, 15040),
  ('hk_boots_t5', 'heavy_knight', 'boots', 5, '重甲輕量競速鞋', 'rare', 40, '{"def":3,"agi":2,"dex":2}'::jsonb, '重騎士專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+2、DEX+2。', TRUE, 15050),
  ('hk_boots_t6', 'heavy_knight', 'boots', 6, '重甲碳板競速鞋', 'rare', 50, '{"def":4,"agi":3,"dex":3}'::jsonb, '重騎士專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+3、DEX+3。', TRUE, 15060),
  ('hk_boots_t7', 'heavy_knight', 'boots', 7, '重甲空力競速釘鞋', 'epic', 60, '{"def":4,"agi":3,"dex":3}'::jsonb, '重騎士專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+3、DEX+3。', TRUE, 15070),
  ('hk_boots_t8', 'heavy_knight', 'boots', 8, '重甲職業選手戰靴', 'epic', 70, '{"def":5,"agi":3,"dex":3}'::jsonb, '重騎士專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+5、AGI+3、DEX+3。', TRUE, 15080),
  ('hk_boots_t9', 'heavy_knight', 'boots', 9, '重甲國手競速戰靴', 'epic', 80, '{"def":5,"agi":4,"dex":4}'::jsonb, '重騎士專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+5、AGI+4、DEX+4。', TRUE, 15090),
  ('hk_boots_t10', 'heavy_knight', 'boots', 10, '重甲巔峰競速戰靴', 'legendary', 90, '{"def":6,"agi":4,"dex":4}'::jsonb, '重騎士專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+6、AGI+4、DEX+4。', TRUE, 15100),
  ('lk_helmet_t1', 'light_knight', 'helmet', 1, '巡街棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '輕騎士專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 21010),
  ('lk_helmet_t2', 'light_knight', 'helmet', 2, '巡街排汗運動帽', 'common', 10, '{"def":1,"int":2}'::jsonb, '輕騎士專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+2。', TRUE, 21020),
  ('lk_helmet_t3', 'light_knight', 'helmet', 3, '巡街透氣網眼帽', 'common', 20, '{"def":1,"int":3}'::jsonb, '輕騎士專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+3。', TRUE, 21030),
  ('lk_helmet_t4', 'light_knight', 'helmet', 4, '巡街遮陽跑帽', 'rare', 30, '{"def":2,"int":3}'::jsonb, '輕騎士專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+3。', TRUE, 21040),
  ('lk_helmet_t5', 'light_knight', 'helmet', 5, '巡街反光夜跑帽', 'rare', 40, '{"def":3,"int":4}'::jsonb, '輕騎士專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+4。', TRUE, 21050),
  ('lk_helmet_t6', 'light_knight', 'helmet', 6, '巡街輕量競速帽', 'rare', 50, '{"def":4,"int":5}'::jsonb, '輕騎士專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+5。', TRUE, 21060),
  ('lk_helmet_t7', 'light_knight', 'helmet', 7, '巡街空力導風帽', 'epic', 60, '{"def":4,"int":6}'::jsonb, '輕騎士專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+6。', TRUE, 21070),
  ('lk_helmet_t8', 'light_knight', 'helmet', 8, '巡街職業競賽帽', 'epic', 70, '{"def":5,"int":6}'::jsonb, '輕騎士專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+6。', TRUE, 21080),
  ('lk_helmet_t9', 'light_knight', 'helmet', 9, '巡街國手戰盔', 'epic', 80, '{"def":5,"int":7}'::jsonb, '輕騎士專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+7。', TRUE, 21090),
  ('lk_helmet_t10', 'light_knight', 'helmet', 10, '巡街巔峰競速盔', 'legendary', 90, '{"def":6,"int":8}'::jsonb, '輕騎士專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+6、INT+8。', TRUE, 21100),
  ('lk_gloves_t1', 'light_knight', 'gloves', 1, '巡街棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '輕騎士專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 22010),
  ('lk_gloves_t2', 'light_knight', 'gloves', 2, '巡街排汗運動手套', 'common', 10, '{"def":1,"str":2}'::jsonb, '輕騎士專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 22020),
  ('lk_gloves_t3', 'light_knight', 'gloves', 3, '巡街透氣網眼手套', 'common', 20, '{"def":1,"str":3}'::jsonb, '輕騎士專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+3。', TRUE, 22030),
  ('lk_gloves_t4', 'light_knight', 'gloves', 4, '巡街防滑訓練手套', 'rare', 30, '{"def":2,"str":4}'::jsonb, '輕騎士專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+4。', TRUE, 22040),
  ('lk_gloves_t5', 'light_knight', 'gloves', 5, '巡街觸控機能手套', 'rare', 40, '{"def":2,"str":5}'::jsonb, '輕騎士專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+5。', TRUE, 22050),
  ('lk_gloves_t6', 'light_knight', 'gloves', 6, '巡街輕量競速手套', 'rare', 50, '{"def":3,"str":6}'::jsonb, '輕騎士專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+6。', TRUE, 22060),
  ('lk_gloves_t7', 'light_knight', 'gloves', 7, '巡街抓地競賽手套', 'epic', 60, '{"def":3,"str":7}'::jsonb, '輕騎士專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+7。', TRUE, 22070),
  ('lk_gloves_t8', 'light_knight', 'gloves', 8, '巡街職業選手手套', 'epic', 70, '{"def":4,"str":8}'::jsonb, '輕騎士專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+8。', TRUE, 22080),
  ('lk_gloves_t9', 'light_knight', 'gloves', 9, '巡街國手戰鬥手套', 'epic', 80, '{"def":4,"str":9}'::jsonb, '輕騎士專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+9。', TRUE, 22090),
  ('lk_gloves_t10', 'light_knight', 'gloves', 10, '巡街巔峰競速護手', 'legendary', 90, '{"def":5,"str":10}'::jsonb, '輕騎士專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+5、STR+10。', TRUE, 22100),
  ('lk_armor_t1', 'light_knight', 'armor', 1, '巡街棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '輕騎士專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 23010),
  ('lk_armor_t2', 'light_knight', 'armor', 2, '巡街機能排汗衣', 'common', 10, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '輕騎士專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 23020),
  ('lk_armor_t3', 'light_knight', 'armor', 3, '巡街涼感訓練衣', 'common', 20, '{"def":3,"vit":3,"hp_pct":4}'::jsonb, '輕騎士專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+3、VIT+3、HP上限+4%。', TRUE, 23030),
  ('lk_armor_t4', 'light_knight', 'armor', 4, '巡街壓縮訓練衣', 'rare', 30, '{"def":5,"vit":3,"hp_pct":5}'::jsonb, '輕騎士專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+5、VIT+3、HP上限+5%。', TRUE, 23040),
  ('lk_armor_t5', 'light_knight', 'armor', 5, '巡街輕量競速衣', 'rare', 40, '{"def":7,"vit":4,"hp_pct":6}'::jsonb, '輕騎士專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+7、VIT+4、HP上限+6%。', TRUE, 23050),
  ('lk_armor_t6', 'light_knight', 'armor', 6, '巡街競賽背心', 'rare', 50, '{"def":8,"vit":5,"hp_pct":8}'::jsonb, '輕騎士專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+8、VIT+5、HP上限+8%。', TRUE, 23060),
  ('lk_armor_t7', 'light_knight', 'armor', 7, '巡街空力競速背心', 'epic', 60, '{"def":10,"vit":6,"hp_pct":9}'::jsonb, '輕騎士專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+10、VIT+6、HP上限+9%。', TRUE, 23070),
  ('lk_armor_t8', 'light_knight', 'armor', 8, '巡街職業選手戰袍', 'epic', 70, '{"def":11,"vit":6,"hp_pct":10}'::jsonb, '輕騎士專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+11、VIT+6、HP上限+10%。', TRUE, 23080),
  ('lk_armor_t9', 'light_knight', 'armor', 9, '巡街國手戰袍', 'epic', 80, '{"def":12,"vit":7,"hp_pct":11}'::jsonb, '輕騎士專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+12、VIT+7、HP上限+11%。', TRUE, 23090),
  ('lk_armor_t10', 'light_knight', 'armor', 10, '巡街巔峰競速戰甲', 'legendary', 90, '{"def":14,"vit":8,"hp_pct":12}'::jsonb, '輕騎士專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+14、VIT+8、HP上限+12%。', TRUE, 23100),
  ('lk_legs_t1', 'light_knight', 'legs', 1, '巡街棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '輕騎士專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 24010),
  ('lk_legs_t2', 'light_knight', 'legs', 2, '巡街排汗短褲', 'common', 10, '{"def":1,"vit":2,"hp_pct":2}'::jsonb, '輕騎士專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+2、HP上限+2%。', TRUE, 24020),
  ('lk_legs_t3', 'light_knight', 'legs', 3, '巡街透氣訓練褲', 'common', 20, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '輕騎士專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 24030),
  ('lk_legs_t4', 'light_knight', 'legs', 4, '巡街壓縮訓練褲', 'rare', 30, '{"def":4,"vit":3,"hp_pct":3}'::jsonb, '輕騎士專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+3%。', TRUE, 24040),
  ('lk_legs_t5', 'light_knight', 'legs', 5, '巡街輕量競速褲', 'rare', 40, '{"def":5,"vit":3,"hp_pct":4}'::jsonb, '輕騎士專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+5、VIT+3、HP上限+4%。', TRUE, 24050),
  ('lk_legs_t6', 'light_knight', 'legs', 6, '巡街分段壓縮褲', 'rare', 50, '{"def":6,"vit":4,"hp_pct":5}'::jsonb, '輕騎士專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+5%。', TRUE, 24060),
  ('lk_legs_t7', 'light_knight', 'legs', 7, '巡街空力競速褲', 'epic', 60, '{"def":7,"vit":4,"hp_pct":6}'::jsonb, '輕騎士專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+4、HP上限+6%。', TRUE, 24070),
  ('lk_legs_t8', 'light_knight', 'legs', 8, '巡街職業選手戰褲', 'epic', 70, '{"def":8,"vit":5,"hp_pct":6}'::jsonb, '輕騎士專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+8、VIT+5、HP上限+6%。', TRUE, 24080),
  ('lk_legs_t9', 'light_knight', 'legs', 9, '巡街國手戰褲', 'epic', 80, '{"def":9,"vit":5,"hp_pct":7}'::jsonb, '輕騎士專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+9、VIT+5、HP上限+7%。', TRUE, 24090),
  ('lk_legs_t10', 'light_knight', 'legs', 10, '巡街巔峰競速護甲褲', 'legendary', 90, '{"def":10,"vit":6,"hp_pct":8}'::jsonb, '輕騎士專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+10、VIT+6、HP上限+8%。', TRUE, 24100),
  ('lk_boots_t1', 'light_knight', 'boots', 1, '巡街帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '輕騎士專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 25010),
  ('lk_boots_t2', 'light_knight', 'boots', 2, '巡街慢跑鞋', 'common', 10, '{"def":1,"agi":2,"dex":2}'::jsonb, '輕騎士專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 25020),
  ('lk_boots_t3', 'light_knight', 'boots', 3, '巡街緩震訓練鞋', 'common', 20, '{"def":1,"agi":2,"dex":2}'::jsonb, '輕騎士專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 25030),
  ('lk_boots_t4', 'light_knight', 'boots', 4, '巡街透氣競速鞋', 'rare', 30, '{"def":2,"agi":3,"dex":3}'::jsonb, '輕騎士專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 25040),
  ('lk_boots_t5', 'light_knight', 'boots', 5, '巡街輕量競速鞋', 'rare', 40, '{"def":2,"agi":3,"dex":3}'::jsonb, '輕騎士專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 25050),
  ('lk_boots_t6', 'light_knight', 'boots', 6, '巡街碳板競速鞋', 'rare', 50, '{"def":3,"agi":4,"dex":4}'::jsonb, '輕騎士專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+4、DEX+4。', TRUE, 25060),
  ('lk_boots_t7', 'light_knight', 'boots', 7, '巡街空力競速釘鞋', 'epic', 60, '{"def":3,"agi":4,"dex":4}'::jsonb, '輕騎士專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+4、DEX+4。', TRUE, 25070),
  ('lk_boots_t8', 'light_knight', 'boots', 8, '巡街職業選手戰靴', 'epic', 70, '{"def":4,"agi":5,"dex":5}'::jsonb, '輕騎士專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+5、DEX+5。', TRUE, 25080),
  ('lk_boots_t9', 'light_knight', 'boots', 9, '巡街國手競速戰靴', 'epic', 80, '{"def":4,"agi":5,"dex":5}'::jsonb, '輕騎士專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+5、DEX+5。', TRUE, 25090),
  ('lk_boots_t10', 'light_knight', 'boots', 10, '巡街巔峰競速戰靴', 'legendary', 90, '{"def":5,"agi":6,"dex":6}'::jsonb, '輕騎士專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+5、AGI+6、DEX+6。', TRUE, 25100),
  ('mc_helmet_t1', 'merchant', 'helmet', 1, '行商棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '商人專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 31010),
  ('mc_helmet_t2', 'merchant', 'helmet', 2, '行商排汗運動帽', 'common', 10, '{"def":1,"int":1}'::jsonb, '商人專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 31020),
  ('mc_helmet_t3', 'merchant', 'helmet', 3, '行商透氣網眼帽', 'common', 20, '{"def":1,"int":2}'::jsonb, '商人專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+2。', TRUE, 31030),
  ('mc_helmet_t4', 'merchant', 'helmet', 4, '行商遮陽跑帽', 'rare', 30, '{"def":2,"int":3}'::jsonb, '商人專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+3。', TRUE, 31040),
  ('mc_helmet_t5', 'merchant', 'helmet', 5, '行商反光夜跑帽', 'rare', 40, '{"def":3,"int":3}'::jsonb, '商人專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+3。', TRUE, 31050),
  ('mc_helmet_t6', 'merchant', 'helmet', 6, '行商輕量競速帽', 'rare', 50, '{"def":3,"int":4}'::jsonb, '商人專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+4。', TRUE, 31060),
  ('mc_helmet_t7', 'merchant', 'helmet', 7, '行商空力導風帽', 'epic', 60, '{"def":4,"int":5}'::jsonb, '商人專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+5。', TRUE, 31070),
  ('mc_helmet_t8', 'merchant', 'helmet', 8, '行商職業競賽帽', 'epic', 70, '{"def":4,"int":5}'::jsonb, '商人專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+5。', TRUE, 31080),
  ('mc_helmet_t9', 'merchant', 'helmet', 9, '行商國手戰盔', 'epic', 80, '{"def":5,"int":6}'::jsonb, '商人專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+6。', TRUE, 31090),
  ('mc_helmet_t10', 'merchant', 'helmet', 10, '行商巔峰競速盔', 'legendary', 90, '{"def":5,"int":6}'::jsonb, '商人專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+6。', TRUE, 31100),
  ('mc_gloves_t1', 'merchant', 'gloves', 1, '行商棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '商人專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 32010),
  ('mc_gloves_t2', 'merchant', 'gloves', 2, '行商排汗運動手套', 'common', 10, '{"def":1,"str":2}'::jsonb, '商人專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 32020),
  ('mc_gloves_t3', 'merchant', 'gloves', 3, '行商透氣網眼手套', 'common', 20, '{"def":1,"str":3}'::jsonb, '商人專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+3。', TRUE, 32030),
  ('mc_gloves_t4', 'merchant', 'gloves', 4, '行商防滑訓練手套', 'rare', 30, '{"def":2,"str":3}'::jsonb, '商人專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+3。', TRUE, 32040),
  ('mc_gloves_t5', 'merchant', 'gloves', 5, '行商觸控機能手套', 'rare', 40, '{"def":2,"str":4}'::jsonb, '商人專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+4。', TRUE, 32050),
  ('mc_gloves_t6', 'merchant', 'gloves', 6, '行商輕量競速手套', 'rare', 50, '{"def":3,"str":5}'::jsonb, '商人專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+5。', TRUE, 32060),
  ('mc_gloves_t7', 'merchant', 'gloves', 7, '行商抓地競賽手套', 'epic', 60, '{"def":3,"str":6}'::jsonb, '商人專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+6。', TRUE, 32070),
  ('mc_gloves_t8', 'merchant', 'gloves', 8, '行商職業選手手套', 'epic', 70, '{"def":4,"str":6}'::jsonb, '商人專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+6。', TRUE, 32080),
  ('mc_gloves_t9', 'merchant', 'gloves', 9, '行商國手戰鬥手套', 'epic', 80, '{"def":4,"str":7}'::jsonb, '商人專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+7。', TRUE, 32090),
  ('mc_gloves_t10', 'merchant', 'gloves', 10, '行商巔峰競速護手', 'legendary', 90, '{"def":5,"str":8}'::jsonb, '商人專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+5、STR+8。', TRUE, 32100),
  ('mc_armor_t1', 'merchant', 'armor', 1, '行商棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '商人專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 33010),
  ('mc_armor_t2', 'merchant', 'armor', 2, '行商機能排汗衣', 'common', 10, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '商人專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 33020),
  ('mc_armor_t3', 'merchant', 'armor', 3, '行商涼感訓練衣', 'common', 20, '{"def":3,"vit":3,"hp_pct":5}'::jsonb, '商人專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+3、VIT+3、HP上限+5%。', TRUE, 33030),
  ('mc_armor_t4', 'merchant', 'armor', 4, '行商壓縮訓練衣', 'rare', 30, '{"def":5,"vit":4,"hp_pct":6}'::jsonb, '商人專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+5、VIT+4、HP上限+6%。', TRUE, 33040),
  ('mc_armor_t5', 'merchant', 'armor', 5, '行商輕量競速衣', 'rare', 40, '{"def":6,"vit":5,"hp_pct":7}'::jsonb, '商人專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+6、VIT+5、HP上限+7%。', TRUE, 33050),
  ('mc_armor_t6', 'merchant', 'armor', 6, '行商競賽背心', 'rare', 50, '{"def":8,"vit":5,"hp_pct":8}'::jsonb, '商人專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+8、VIT+5、HP上限+8%。', TRUE, 33060),
  ('mc_armor_t7', 'merchant', 'armor', 7, '行商空力競速背心', 'epic', 60, '{"def":9,"vit":6,"hp_pct":10}'::jsonb, '商人專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+9、VIT+6、HP上限+10%。', TRUE, 33070),
  ('mc_armor_t8', 'merchant', 'armor', 8, '行商職業選手戰袍', 'epic', 70, '{"def":10,"vit":7,"hp_pct":11}'::jsonb, '商人專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+10、VIT+7、HP上限+11%。', TRUE, 33080),
  ('mc_armor_t9', 'merchant', 'armor', 9, '行商國手戰袍', 'epic', 80, '{"def":11,"vit":8,"hp_pct":12}'::jsonb, '商人專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+11、VIT+8、HP上限+12%。', TRUE, 33090),
  ('mc_armor_t10', 'merchant', 'armor', 10, '行商巔峰競速戰甲', 'legendary', 90, '{"def":13,"vit":9,"hp_pct":13}'::jsonb, '商人專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+13、VIT+9、HP上限+13%。', TRUE, 33100),
  ('mc_legs_t1', 'merchant', 'legs', 1, '行商棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '商人專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 34010),
  ('mc_legs_t2', 'merchant', 'legs', 2, '行商排汗短褲', 'common', 10, '{"def":1,"vit":2,"hp_pct":2}'::jsonb, '商人專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+2、HP上限+2%。', TRUE, 34020),
  ('mc_legs_t3', 'merchant', 'legs', 3, '行商透氣訓練褲', 'common', 20, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '商人專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 34030),
  ('mc_legs_t4', 'merchant', 'legs', 4, '行商壓縮訓練褲', 'rare', 30, '{"def":3,"vit":3,"hp_pct":4}'::jsonb, '商人專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+3、VIT+3、HP上限+4%。', TRUE, 34040),
  ('mc_legs_t5', 'merchant', 'legs', 5, '行商輕量競速褲', 'rare', 40, '{"def":4,"vit":4,"hp_pct":5}'::jsonb, '商人專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+4、HP上限+5%。', TRUE, 34050),
  ('mc_legs_t6', 'merchant', 'legs', 6, '行商分段壓縮褲', 'rare', 50, '{"def":6,"vit":4,"hp_pct":5}'::jsonb, '商人專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+5%。', TRUE, 34060),
  ('mc_legs_t7', 'merchant', 'legs', 7, '行商空力競速褲', 'epic', 60, '{"def":6,"vit":5,"hp_pct":6}'::jsonb, '商人專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+5、HP上限+6%。', TRUE, 34070),
  ('mc_legs_t8', 'merchant', 'legs', 8, '行商職業選手戰褲', 'epic', 70, '{"def":7,"vit":5,"hp_pct":7}'::jsonb, '商人專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+5、HP上限+7%。', TRUE, 34080),
  ('mc_legs_t9', 'merchant', 'legs', 9, '行商國手戰褲', 'epic', 80, '{"def":8,"vit":6,"hp_pct":8}'::jsonb, '商人專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+8、VIT+6、HP上限+8%。', TRUE, 34090),
  ('mc_legs_t10', 'merchant', 'legs', 10, '行商巔峰競速護甲褲', 'legendary', 90, '{"def":9,"vit":7,"hp_pct":9}'::jsonb, '商人專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+9、VIT+7、HP上限+9%。', TRUE, 34100),
  ('mc_boots_t1', 'merchant', 'boots', 1, '行商帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '商人專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 35010),
  ('mc_boots_t2', 'merchant', 'boots', 2, '行商慢跑鞋', 'common', 10, '{"def":1,"agi":1,"dex":1}'::jsonb, '商人專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 35020),
  ('mc_boots_t3', 'merchant', 'boots', 3, '行商緩震訓練鞋', 'common', 20, '{"def":1,"agi":2,"dex":2}'::jsonb, '商人專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 35030),
  ('mc_boots_t4', 'merchant', 'boots', 4, '行商透氣競速鞋', 'rare', 30, '{"def":2,"agi":2,"dex":2}'::jsonb, '商人專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+2、DEX+2。', TRUE, 35040),
  ('mc_boots_t5', 'merchant', 'boots', 5, '行商輕量競速鞋', 'rare', 40, '{"def":2,"agi":3,"dex":3}'::jsonb, '商人專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 35050),
  ('mc_boots_t6', 'merchant', 'boots', 6, '行商碳板競速鞋', 'rare', 50, '{"def":3,"agi":3,"dex":3}'::jsonb, '商人專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+3、DEX+3。', TRUE, 35060),
  ('mc_boots_t7', 'merchant', 'boots', 7, '行商空力競速釘鞋', 'epic', 60, '{"def":3,"agi":3,"dex":3}'::jsonb, '商人專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+3、DEX+3。', TRUE, 35070),
  ('mc_boots_t8', 'merchant', 'boots', 8, '行商職業選手戰靴', 'epic', 70, '{"def":4,"agi":4,"dex":4}'::jsonb, '商人專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+4、DEX+4。', TRUE, 35080),
  ('mc_boots_t9', 'merchant', 'boots', 9, '行商國手競速戰靴', 'epic', 80, '{"def":4,"agi":4,"dex":4}'::jsonb, '商人專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+4、DEX+4。', TRUE, 35090),
  ('mc_boots_t10', 'merchant', 'boots', 10, '行商巔峰競速戰靴', 'legendary', 90, '{"def":5,"agi":5,"dex":5}'::jsonb, '商人專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+5、AGI+5、DEX+5。', TRUE, 35100),
  ('ar_helmet_t1', 'archer', 'helmet', 1, '獵風棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '弓箭手專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 41010),
  ('ar_helmet_t2', 'archer', 'helmet', 2, '獵風排汗運動帽', 'common', 10, '{"def":1,"int":1}'::jsonb, '弓箭手專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 41020),
  ('ar_helmet_t3', 'archer', 'helmet', 3, '獵風透氣網眼帽', 'common', 20, '{"def":1,"int":2}'::jsonb, '弓箭手專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+2。', TRUE, 41030),
  ('ar_helmet_t4', 'archer', 'helmet', 4, '獵風遮陽跑帽', 'rare', 30, '{"def":2,"int":2}'::jsonb, '弓箭手專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+2。', TRUE, 41040),
  ('ar_helmet_t5', 'archer', 'helmet', 5, '獵風反光夜跑帽', 'rare', 40, '{"def":2,"int":3}'::jsonb, '弓箭手專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+3。', TRUE, 41050),
  ('ar_helmet_t6', 'archer', 'helmet', 6, '獵風輕量競速帽', 'rare', 50, '{"def":3,"int":3}'::jsonb, '弓箭手專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+3。', TRUE, 41060),
  ('ar_helmet_t7', 'archer', 'helmet', 7, '獵風空力導風帽', 'epic', 60, '{"def":3,"int":4}'::jsonb, '弓箭手專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+4。', TRUE, 41070),
  ('ar_helmet_t8', 'archer', 'helmet', 8, '獵風職業競賽帽', 'epic', 70, '{"def":4,"int":5}'::jsonb, '弓箭手專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+5。', TRUE, 41080),
  ('ar_helmet_t9', 'archer', 'helmet', 9, '獵風國手戰盔', 'epic', 80, '{"def":4,"int":5}'::jsonb, '弓箭手專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+5。', TRUE, 41090),
  ('ar_helmet_t10', 'archer', 'helmet', 10, '獵風巔峰競速盔', 'legendary', 90, '{"def":5,"int":6}'::jsonb, '弓箭手專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+6。', TRUE, 41100),
  ('ar_gloves_t1', 'archer', 'gloves', 1, '獵風棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '弓箭手專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 42010),
  ('ar_gloves_t2', 'archer', 'gloves', 2, '獵風排汗運動手套', 'common', 10, '{"def":1,"str":1}'::jsonb, '弓箭手專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 42020),
  ('ar_gloves_t3', 'archer', 'gloves', 3, '獵風透氣網眼手套', 'common', 20, '{"def":1,"str":2}'::jsonb, '弓箭手專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 42030),
  ('ar_gloves_t4', 'archer', 'gloves', 4, '獵風防滑訓練手套', 'rare', 30, '{"def":1,"str":3}'::jsonb, '弓箭手專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+3。', TRUE, 42040),
  ('ar_gloves_t5', 'archer', 'gloves', 5, '獵風觸控機能手套', 'rare', 40, '{"def":2,"str":3}'::jsonb, '弓箭手專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+3。', TRUE, 42050),
  ('ar_gloves_t6', 'archer', 'gloves', 6, '獵風輕量競速手套', 'rare', 50, '{"def":2,"str":4}'::jsonb, '弓箭手專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+4。', TRUE, 42060),
  ('ar_gloves_t7', 'archer', 'gloves', 7, '獵風抓地競賽手套', 'epic', 60, '{"def":3,"str":5}'::jsonb, '弓箭手專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+5。', TRUE, 42070),
  ('ar_gloves_t8', 'archer', 'gloves', 8, '獵風職業選手手套', 'epic', 70, '{"def":3,"str":5}'::jsonb, '弓箭手專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+5。', TRUE, 42080),
  ('ar_gloves_t9', 'archer', 'gloves', 9, '獵風國手戰鬥手套', 'epic', 80, '{"def":4,"str":6}'::jsonb, '弓箭手專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+6。', TRUE, 42090),
  ('ar_gloves_t10', 'archer', 'gloves', 10, '獵風巔峰競速護手', 'legendary', 90, '{"def":4,"str":6}'::jsonb, '弓箭手專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+6。', TRUE, 42100),
  ('ar_armor_t1', 'archer', 'armor', 1, '獵風棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '弓箭手專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 43010),
  ('ar_armor_t2', 'archer', 'armor', 2, '獵風機能排汗衣', 'common', 10, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '弓箭手專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 43020),
  ('ar_armor_t3', 'archer', 'armor', 3, '獵風涼感訓練衣', 'common', 20, '{"def":3,"vit":2,"hp_pct":4}'::jsonb, '弓箭手專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+3、VIT+2、HP上限+4%。', TRUE, 43030),
  ('ar_armor_t4', 'archer', 'armor', 4, '獵風壓縮訓練衣', 'rare', 30, '{"def":4,"vit":3,"hp_pct":5}'::jsonb, '弓箭手專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+4、VIT+3、HP上限+5%。', TRUE, 43040),
  ('ar_armor_t5', 'archer', 'armor', 5, '獵風輕量競速衣', 'rare', 40, '{"def":5,"vit":4,"hp_pct":6}'::jsonb, '弓箭手專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+5、VIT+4、HP上限+6%。', TRUE, 43050),
  ('ar_armor_t6', 'archer', 'armor', 6, '獵風競賽背心', 'rare', 50, '{"def":7,"vit":4,"hp_pct":7}'::jsonb, '弓箭手專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+7、VIT+4、HP上限+7%。', TRUE, 43060),
  ('ar_armor_t7', 'archer', 'armor', 7, '獵風空力競速背心', 'epic', 60, '{"def":8,"vit":5,"hp_pct":8}'::jsonb, '弓箭手專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+8、VIT+5、HP上限+8%。', TRUE, 43070),
  ('ar_armor_t8', 'archer', 'armor', 8, '獵風職業選手戰袍', 'epic', 70, '{"def":9,"vit":6,"hp_pct":9}'::jsonb, '弓箭手專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+9、VIT+6、HP上限+9%。', TRUE, 43080),
  ('ar_armor_t9', 'archer', 'armor', 9, '獵風國手戰袍', 'epic', 80, '{"def":10,"vit":7,"hp_pct":10}'::jsonb, '弓箭手專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+10、VIT+7、HP上限+10%。', TRUE, 43090),
  ('ar_armor_t10', 'archer', 'armor', 10, '獵風巔峰競速戰甲', 'legendary', 90, '{"def":11,"vit":7,"hp_pct":11}'::jsonb, '弓箭手專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+11、VIT+7、HP上限+11%。', TRUE, 43100),
  ('ar_legs_t1', 'archer', 'legs', 1, '獵風棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '弓箭手專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 44010),
  ('ar_legs_t2', 'archer', 'legs', 2, '獵風排汗短褲', 'common', 10, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '弓箭手專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 44020),
  ('ar_legs_t3', 'archer', 'legs', 3, '獵風透氣訓練褲', 'common', 20, '{"def":2,"vit":2,"hp_pct":2}'::jsonb, '弓箭手專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+2%。', TRUE, 44030),
  ('ar_legs_t4', 'archer', 'legs', 4, '獵風壓縮訓練褲', 'rare', 30, '{"def":3,"vit":2,"hp_pct":3}'::jsonb, '弓箭手專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+3、VIT+2、HP上限+3%。', TRUE, 44040),
  ('ar_legs_t5', 'archer', 'legs', 5, '獵風輕量競速褲', 'rare', 40, '{"def":4,"vit":3,"hp_pct":4}'::jsonb, '弓箭手專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+4%。', TRUE, 44050),
  ('ar_legs_t6', 'archer', 'legs', 6, '獵風分段壓縮褲', 'rare', 50, '{"def":5,"vit":3,"hp_pct":4}'::jsonb, '弓箭手專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+5、VIT+3、HP上限+4%。', TRUE, 44060),
  ('ar_legs_t7', 'archer', 'legs', 7, '獵風空力競速褲', 'epic', 60, '{"def":6,"vit":4,"hp_pct":5}'::jsonb, '弓箭手專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+5%。', TRUE, 44070),
  ('ar_legs_t8', 'archer', 'legs', 8, '獵風職業選手戰褲', 'epic', 70, '{"def":7,"vit":4,"hp_pct":6}'::jsonb, '弓箭手專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+4、HP上限+6%。', TRUE, 44080),
  ('ar_legs_t9', 'archer', 'legs', 9, '獵風國手戰褲', 'epic', 80, '{"def":7,"vit":5,"hp_pct":7}'::jsonb, '弓箭手專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+5、HP上限+7%。', TRUE, 44090),
  ('ar_legs_t10', 'archer', 'legs', 10, '獵風巔峰競速護甲褲', 'legendary', 90, '{"def":8,"vit":5,"hp_pct":7}'::jsonb, '弓箭手專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+8、VIT+5、HP上限+7%。', TRUE, 44100),
  ('ar_boots_t1', 'archer', 'boots', 1, '獵風帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '弓箭手專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 45010),
  ('ar_boots_t2', 'archer', 'boots', 2, '獵風慢跑鞋', 'common', 10, '{"def":1,"agi":2,"dex":2}'::jsonb, '弓箭手專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 45020),
  ('ar_boots_t3', 'archer', 'boots', 3, '獵風緩震訓練鞋', 'common', 20, '{"def":1,"agi":3,"dex":3}'::jsonb, '弓箭手專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+3、DEX+3。', TRUE, 45030),
  ('ar_boots_t4', 'archer', 'boots', 4, '獵風透氣競速鞋', 'rare', 30, '{"def":1,"agi":3,"dex":3}'::jsonb, '弓箭手專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+3、DEX+3。', TRUE, 45040),
  ('ar_boots_t5', 'archer', 'boots', 5, '獵風輕量競速鞋', 'rare', 40, '{"def":2,"agi":4,"dex":4}'::jsonb, '弓箭手專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+4、DEX+4。', TRUE, 45050),
  ('ar_boots_t6', 'archer', 'boots', 6, '獵風碳板競速鞋', 'rare', 50, '{"def":2,"agi":5,"dex":5}'::jsonb, '弓箭手專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+5、DEX+5。', TRUE, 45060),
  ('ar_boots_t7', 'archer', 'boots', 7, '獵風空力競速釘鞋', 'epic', 60, '{"def":3,"agi":5,"dex":5}'::jsonb, '弓箭手專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+5、DEX+5。', TRUE, 45070),
  ('ar_boots_t8', 'archer', 'boots', 8, '獵風職業選手戰靴', 'epic', 70, '{"def":3,"agi":6,"dex":6}'::jsonb, '弓箭手專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+6、DEX+6。', TRUE, 45080),
  ('ar_boots_t9', 'archer', 'boots', 9, '獵風國手競速戰靴', 'epic', 80, '{"def":4,"agi":6,"dex":6}'::jsonb, '弓箭手專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+6、DEX+6。', TRUE, 45090),
  ('ar_boots_t10', 'archer', 'boots', 10, '獵風巔峰競速戰靴', 'legendary', 90, '{"def":4,"agi":7,"dex":7}'::jsonb, '弓箭手專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+7、DEX+7。', TRUE, 45100),
  ('cl_helmet_t1', 'cleric', 'helmet', 1, '聖護棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '聖職者專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 51010),
  ('cl_helmet_t2', 'cleric', 'helmet', 2, '聖護排汗運動帽', 'common', 10, '{"def":1,"int":2}'::jsonb, '聖職者專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+2。', TRUE, 51020),
  ('cl_helmet_t3', 'cleric', 'helmet', 3, '聖護透氣網眼帽', 'common', 20, '{"def":1,"int":3}'::jsonb, '聖職者專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+3。', TRUE, 51030),
  ('cl_helmet_t4', 'cleric', 'helmet', 4, '聖護遮陽跑帽', 'rare', 30, '{"def":2,"int":4}'::jsonb, '聖職者專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+4。', TRUE, 51040),
  ('cl_helmet_t5', 'cleric', 'helmet', 5, '聖護反光夜跑帽', 'rare', 40, '{"def":2,"int":5}'::jsonb, '聖職者專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+5。', TRUE, 51050),
  ('cl_helmet_t6', 'cleric', 'helmet', 6, '聖護輕量競速帽', 'rare', 50, '{"def":3,"int":6}'::jsonb, '聖職者專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+6。', TRUE, 51060),
  ('cl_helmet_t7', 'cleric', 'helmet', 7, '聖護空力導風帽', 'epic', 60, '{"def":3,"int":7}'::jsonb, '聖職者專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+7。', TRUE, 51070),
  ('cl_helmet_t8', 'cleric', 'helmet', 8, '聖護職業競賽帽', 'epic', 70, '{"def":4,"int":8}'::jsonb, '聖職者專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+8。', TRUE, 51080),
  ('cl_helmet_t9', 'cleric', 'helmet', 9, '聖護國手戰盔', 'epic', 80, '{"def":4,"int":9}'::jsonb, '聖職者專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+9。', TRUE, 51090),
  ('cl_helmet_t10', 'cleric', 'helmet', 10, '聖護巔峰競速盔', 'legendary', 90, '{"def":5,"int":10}'::jsonb, '聖職者專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+5、INT+10。', TRUE, 51100),
  ('cl_gloves_t1', 'cleric', 'gloves', 1, '聖護棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '聖職者專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 52010),
  ('cl_gloves_t2', 'cleric', 'gloves', 2, '聖護排汗運動手套', 'common', 10, '{"def":1,"str":1}'::jsonb, '聖職者專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 52020),
  ('cl_gloves_t3', 'cleric', 'gloves', 3, '聖護透氣網眼手套', 'common', 20, '{"def":1,"str":2}'::jsonb, '聖職者專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 52030),
  ('cl_gloves_t4', 'cleric', 'gloves', 4, '聖護防滑訓練手套', 'rare', 30, '{"def":1,"str":2}'::jsonb, '聖職者專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 52040),
  ('cl_gloves_t5', 'cleric', 'gloves', 5, '聖護觸控機能手套', 'rare', 40, '{"def":2,"str":2}'::jsonb, '聖職者專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+2。', TRUE, 52050),
  ('cl_gloves_t6', 'cleric', 'gloves', 6, '聖護輕量競速手套', 'rare', 50, '{"def":2,"str":3}'::jsonb, '聖職者專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+3。', TRUE, 52060),
  ('cl_gloves_t7', 'cleric', 'gloves', 7, '聖護抓地競賽手套', 'epic', 60, '{"def":3,"str":3}'::jsonb, '聖職者專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+3。', TRUE, 52070),
  ('cl_gloves_t8', 'cleric', 'gloves', 8, '聖護職業選手手套', 'epic', 70, '{"def":3,"str":4}'::jsonb, '聖職者專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+4。', TRUE, 52080),
  ('cl_gloves_t9', 'cleric', 'gloves', 9, '聖護國手戰鬥手套', 'epic', 80, '{"def":3,"str":4}'::jsonb, '聖職者專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+4。', TRUE, 52090),
  ('cl_gloves_t10', 'cleric', 'gloves', 10, '聖護巔峰競速護手', 'legendary', 90, '{"def":4,"str":5}'::jsonb, '聖職者專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+4、STR+5。', TRUE, 52100),
  ('cl_armor_t1', 'cleric', 'armor', 1, '聖護棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '聖職者專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 53010),
  ('cl_armor_t2', 'cleric', 'armor', 2, '聖護機能排汗衣', 'common', 10, '{"def":1,"vit":2,"hp_pct":3}'::jsonb, '聖職者專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+2、HP上限+3%。', TRUE, 53020),
  ('cl_armor_t3', 'cleric', 'armor', 3, '聖護涼感訓練衣', 'common', 20, '{"def":3,"vit":2,"hp_pct":4}'::jsonb, '聖職者專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+3、VIT+2、HP上限+4%。', TRUE, 53030),
  ('cl_armor_t4', 'cleric', 'armor', 4, '聖護壓縮訓練衣', 'rare', 30, '{"def":4,"vit":3,"hp_pct":5}'::jsonb, '聖職者專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+4、VIT+3、HP上限+5%。', TRUE, 53040),
  ('cl_armor_t5', 'cleric', 'armor', 5, '聖護輕量競速衣', 'rare', 40, '{"def":5,"vit":4,"hp_pct":6}'::jsonb, '聖職者專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+5、VIT+4、HP上限+6%。', TRUE, 53050),
  ('cl_armor_t6', 'cleric', 'armor', 6, '聖護競賽背心', 'rare', 50, '{"def":7,"vit":4,"hp_pct":7}'::jsonb, '聖職者專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+7、VIT+4、HP上限+7%。', TRUE, 53060),
  ('cl_armor_t7', 'cleric', 'armor', 7, '聖護空力競速背心', 'epic', 60, '{"def":7,"vit":5,"hp_pct":8}'::jsonb, '聖職者專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+7、VIT+5、HP上限+8%。', TRUE, 53070),
  ('cl_armor_t8', 'cleric', 'armor', 8, '聖護職業選手戰袍', 'epic', 70, '{"def":9,"vit":6,"hp_pct":9}'::jsonb, '聖職者專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+9、VIT+6、HP上限+9%。', TRUE, 53080),
  ('cl_armor_t9', 'cleric', 'armor', 9, '聖護國手戰袍', 'epic', 80, '{"def":10,"vit":7,"hp_pct":10}'::jsonb, '聖職者專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+10、VIT+7、HP上限+10%。', TRUE, 53090),
  ('cl_armor_t10', 'cleric', 'armor', 10, '聖護巔峰競速戰甲', 'legendary', 90, '{"def":11,"vit":7,"hp_pct":11}'::jsonb, '聖職者專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+11、VIT+7、HP上限+11%。', TRUE, 53100),
  ('cl_legs_t1', 'cleric', 'legs', 1, '聖護棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '聖職者專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 54010),
  ('cl_legs_t2', 'cleric', 'legs', 2, '聖護排汗短褲', 'common', 10, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '聖職者專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 54020),
  ('cl_legs_t3', 'cleric', 'legs', 3, '聖護透氣訓練褲', 'common', 20, '{"def":2,"vit":2,"hp_pct":2}'::jsonb, '聖職者專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+2%。', TRUE, 54030),
  ('cl_legs_t4', 'cleric', 'legs', 4, '聖護壓縮訓練褲', 'rare', 30, '{"def":3,"vit":2,"hp_pct":3}'::jsonb, '聖職者專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+3、VIT+2、HP上限+3%。', TRUE, 54040),
  ('cl_legs_t5', 'cleric', 'legs', 5, '聖護輕量競速褲', 'rare', 40, '{"def":4,"vit":3,"hp_pct":4}'::jsonb, '聖職者專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+4%。', TRUE, 54050),
  ('cl_legs_t6', 'cleric', 'legs', 6, '聖護分段壓縮褲', 'rare', 50, '{"def":5,"vit":3,"hp_pct":4}'::jsonb, '聖職者專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+5、VIT+3、HP上限+4%。', TRUE, 54060),
  ('cl_legs_t7', 'cleric', 'legs', 7, '聖護空力競速褲', 'epic', 60, '{"def":5,"vit":4,"hp_pct":5}'::jsonb, '聖職者專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+5、VIT+4、HP上限+5%。', TRUE, 54070),
  ('cl_legs_t8', 'cleric', 'legs', 8, '聖護職業選手戰褲', 'epic', 70, '{"def":6,"vit":4,"hp_pct":6}'::jsonb, '聖職者專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+6%。', TRUE, 54080),
  ('cl_legs_t9', 'cleric', 'legs', 9, '聖護國手戰褲', 'epic', 80, '{"def":7,"vit":5,"hp_pct":7}'::jsonb, '聖職者專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+7、VIT+5、HP上限+7%。', TRUE, 54090),
  ('cl_legs_t10', 'cleric', 'legs', 10, '聖護巔峰競速護甲褲', 'legendary', 90, '{"def":8,"vit":5,"hp_pct":7}'::jsonb, '聖職者專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+8、VIT+5、HP上限+7%。', TRUE, 54100),
  ('cl_boots_t1', 'cleric', 'boots', 1, '聖護帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '聖職者專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 55010),
  ('cl_boots_t2', 'cleric', 'boots', 2, '聖護慢跑鞋', 'common', 10, '{"def":1,"agi":1,"dex":1}'::jsonb, '聖職者專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 55020),
  ('cl_boots_t3', 'cleric', 'boots', 3, '聖護緩震訓練鞋', 'common', 20, '{"def":1,"agi":2,"dex":2}'::jsonb, '聖職者專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 55030),
  ('cl_boots_t4', 'cleric', 'boots', 4, '聖護透氣競速鞋', 'rare', 30, '{"def":1,"agi":2,"dex":2}'::jsonb, '聖職者專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 55040),
  ('cl_boots_t5', 'cleric', 'boots', 5, '聖護輕量競速鞋', 'rare', 40, '{"def":2,"agi":2,"dex":2}'::jsonb, '聖職者專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+2、DEX+2。', TRUE, 55050),
  ('cl_boots_t6', 'cleric', 'boots', 6, '聖護碳板競速鞋', 'rare', 50, '{"def":2,"agi":3,"dex":3}'::jsonb, '聖職者專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 55060),
  ('cl_boots_t7', 'cleric', 'boots', 7, '聖護空力競速釘鞋', 'epic', 60, '{"def":3,"agi":3,"dex":3}'::jsonb, '聖職者專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+3、DEX+3。', TRUE, 55070),
  ('cl_boots_t8', 'cleric', 'boots', 8, '聖護職業選手戰靴', 'epic', 70, '{"def":3,"agi":3,"dex":3}'::jsonb, '聖職者專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+3、DEX+3。', TRUE, 55080),
  ('cl_boots_t9', 'cleric', 'boots', 9, '聖護國手競速戰靴', 'epic', 80, '{"def":3,"agi":4,"dex":4}'::jsonb, '聖職者專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+4、DEX+4。', TRUE, 55090),
  ('cl_boots_t10', 'cleric', 'boots', 10, '聖護巔峰競速戰靴', 'legendary', 90, '{"def":4,"agi":4,"dex":4}'::jsonb, '聖職者專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+4、AGI+4、DEX+4。', TRUE, 55100),
  ('mg_helmet_t1', 'mage', 'helmet', 1, '咒紋棉質運動帽', 'common', 1, '{"def":1,"int":1}'::jsonb, '魔法師專用頭盔，Lv.1以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+1。', TRUE, 61010),
  ('mg_helmet_t2', 'mage', 'helmet', 2, '咒紋排汗運動帽', 'common', 10, '{"def":1,"int":2}'::jsonb, '魔法師專用頭盔，Lv.10以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+2。', TRUE, 61020),
  ('mg_helmet_t3', 'mage', 'helmet', 3, '咒紋透氣網眼帽', 'common', 20, '{"def":1,"int":4}'::jsonb, '魔法師專用頭盔，Lv.20以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+4。', TRUE, 61030),
  ('mg_helmet_t4', 'mage', 'helmet', 4, '咒紋遮陽跑帽', 'rare', 30, '{"def":1,"int":5}'::jsonb, '魔法師專用頭盔，Lv.30以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+1、INT+5。', TRUE, 61040),
  ('mg_helmet_t5', 'mage', 'helmet', 5, '咒紋反光夜跑帽', 'rare', 40, '{"def":2,"int":6}'::jsonb, '魔法師專用頭盔，Lv.40以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+6。', TRUE, 61050),
  ('mg_helmet_t6', 'mage', 'helmet', 6, '咒紋輕量競速帽', 'rare', 50, '{"def":2,"int":7}'::jsonb, '魔法師專用頭盔，Lv.50以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+2、INT+7。', TRUE, 61060),
  ('mg_helmet_t7', 'mage', 'helmet', 7, '咒紋空力導風帽', 'epic', 60, '{"def":3,"int":8}'::jsonb, '魔法師專用頭盔，Lv.60以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+8。', TRUE, 61070),
  ('mg_helmet_t8', 'mage', 'helmet', 8, '咒紋職業競賽帽', 'epic', 70, '{"def":3,"int":9}'::jsonb, '魔法師專用頭盔，Lv.70以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+9。', TRUE, 61080),
  ('mg_helmet_t9', 'mage', 'helmet', 9, '咒紋國手戰盔', 'epic', 80, '{"def":3,"int":10}'::jsonb, '魔法師專用頭盔，Lv.80以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+3、INT+10。', TRUE, 61090),
  ('mg_helmet_t10', 'mage', 'helmet', 10, '咒紋巔峰競速盔', 'legendary', 90, '{"def":4,"int":11}'::jsonb, '魔法師專用頭盔，Lv.90以上可裝備，頭部裝備，兼顧視野與防護，提供DEF+4、INT+11。', TRUE, 61100),
  ('mg_gloves_t1', 'mage', 'gloves', 1, '咒紋棉質手套', 'common', 1, '{"def":1,"str":1}'::jsonb, '魔法師專用手套，Lv.1以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 62010),
  ('mg_gloves_t2', 'mage', 'gloves', 2, '咒紋排汗運動手套', 'common', 10, '{"def":1,"str":1}'::jsonb, '魔法師專用手套，Lv.10以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+1。', TRUE, 62020),
  ('mg_gloves_t3', 'mage', 'gloves', 3, '咒紋透氣網眼手套', 'common', 20, '{"def":1,"str":2}'::jsonb, '魔法師專用手套，Lv.20以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 62030),
  ('mg_gloves_t4', 'mage', 'gloves', 4, '咒紋防滑訓練手套', 'rare', 30, '{"def":1,"str":2}'::jsonb, '魔法師專用手套，Lv.30以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 62040),
  ('mg_gloves_t5', 'mage', 'gloves', 5, '咒紋觸控機能手套', 'rare', 40, '{"def":1,"str":2}'::jsonb, '魔法師專用手套，Lv.40以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+1、STR+2。', TRUE, 62050),
  ('mg_gloves_t6', 'mage', 'gloves', 6, '咒紋輕量競速手套', 'rare', 50, '{"def":2,"str":3}'::jsonb, '魔法師專用手套，Lv.50以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+3。', TRUE, 62060),
  ('mg_gloves_t7', 'mage', 'gloves', 7, '咒紋抓地競賽手套', 'epic', 60, '{"def":2,"str":3}'::jsonb, '魔法師專用手套，Lv.60以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+2、STR+3。', TRUE, 62070),
  ('mg_gloves_t8', 'mage', 'gloves', 8, '咒紋職業選手手套', 'epic', 70, '{"def":3,"str":4}'::jsonb, '魔法師專用手套，Lv.70以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+4。', TRUE, 62080),
  ('mg_gloves_t9', 'mage', 'gloves', 9, '咒紋國手戰鬥手套', 'epic', 80, '{"def":3,"str":4}'::jsonb, '魔法師專用手套，Lv.80以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+4。', TRUE, 62090),
  ('mg_gloves_t10', 'mage', 'gloves', 10, '咒紋巔峰競速護手', 'legendary', 90, '{"def":3,"str":5}'::jsonb, '魔法師專用手套，Lv.90以上可裝備，手部裝備，強化出拳與擺臂力道，提供DEF+3、STR+5。', TRUE, 62100),
  ('mg_armor_t1', 'mage', 'armor', 1, '咒紋棉質排汗衣', 'common', 1, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '魔法師專用衣服，Lv.1以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 63010),
  ('mg_armor_t2', 'mage', 'armor', 2, '咒紋機能排汗衣', 'common', 10, '{"def":1,"vit":1,"hp_pct":2}'::jsonb, '魔法師專用衣服，Lv.10以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+1、VIT+1、HP上限+2%。', TRUE, 63020),
  ('mg_armor_t3', 'mage', 'armor', 3, '咒紋涼感訓練衣', 'common', 20, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '魔法師專用衣服，Lv.20以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 63030),
  ('mg_armor_t4', 'mage', 'armor', 4, '咒紋壓縮訓練衣', 'rare', 30, '{"def":3,"vit":3,"hp_pct":4}'::jsonb, '魔法師專用衣服，Lv.30以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+3、VIT+3、HP上限+4%。', TRUE, 63040),
  ('mg_armor_t5', 'mage', 'armor', 5, '咒紋輕量競速衣', 'rare', 40, '{"def":4,"vit":3,"hp_pct":5}'::jsonb, '魔法師專用衣服，Lv.40以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+4、VIT+3、HP上限+5%。', TRUE, 63050),
  ('mg_armor_t6', 'mage', 'armor', 6, '咒紋競賽背心', 'rare', 50, '{"def":5,"vit":4,"hp_pct":6}'::jsonb, '魔法師專用衣服，Lv.50以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+5、VIT+4、HP上限+6%。', TRUE, 63060),
  ('mg_armor_t7', 'mage', 'armor', 7, '咒紋空力競速背心', 'epic', 60, '{"def":6,"vit":5,"hp_pct":7}'::jsonb, '魔法師專用衣服，Lv.60以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+6、VIT+5、HP上限+7%。', TRUE, 63070),
  ('mg_armor_t8', 'mage', 'armor', 8, '咒紋職業選手戰袍', 'epic', 70, '{"def":7,"vit":5,"hp_pct":8}'::jsonb, '魔法師專用衣服，Lv.70以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+7、VIT+5、HP上限+8%。', TRUE, 63080),
  ('mg_armor_t9', 'mage', 'armor', 9, '咒紋國手戰袍', 'epic', 80, '{"def":8,"vit":6,"hp_pct":9}'::jsonb, '魔法師專用衣服，Lv.80以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+8、VIT+6、HP上限+9%。', TRUE, 63090),
  ('mg_armor_t10', 'mage', 'armor', 10, '咒紋巔峰競速戰甲', 'legendary', 90, '{"def":9,"vit":6,"hp_pct":10}'::jsonb, '魔法師專用衣服，Lv.90以上可裝備，軀幹裝備，防具主要防禦來源，提供DEF+9、VIT+6、HP上限+10%。', TRUE, 63100),
  ('mg_legs_t1', 'mage', 'legs', 1, '咒紋棉質運動褲', 'common', 1, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '魔法師專用褲裙，Lv.1以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 64010),
  ('mg_legs_t2', 'mage', 'legs', 2, '咒紋排汗短褲', 'common', 10, '{"def":1,"vit":1,"hp_pct":1}'::jsonb, '魔法師專用褲裙，Lv.10以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+1、VIT+1、HP上限+1%。', TRUE, 64020),
  ('mg_legs_t3', 'mage', 'legs', 3, '咒紋透氣訓練褲', 'common', 20, '{"def":2,"vit":2,"hp_pct":2}'::jsonb, '魔法師專用褲裙，Lv.20以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+2%。', TRUE, 64030),
  ('mg_legs_t4', 'mage', 'legs', 4, '咒紋壓縮訓練褲', 'rare', 30, '{"def":2,"vit":2,"hp_pct":3}'::jsonb, '魔法師專用褲裙，Lv.30以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+2、VIT+2、HP上限+3%。', TRUE, 64040),
  ('mg_legs_t5', 'mage', 'legs', 5, '咒紋輕量競速褲', 'rare', 40, '{"def":3,"vit":3,"hp_pct":3}'::jsonb, '魔法師專用褲裙，Lv.40以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+3、VIT+3、HP上限+3%。', TRUE, 64050),
  ('mg_legs_t6', 'mage', 'legs', 6, '咒紋分段壓縮褲', 'rare', 50, '{"def":4,"vit":3,"hp_pct":4}'::jsonb, '魔法師專用褲裙，Lv.50以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+4%。', TRUE, 64060),
  ('mg_legs_t7', 'mage', 'legs', 7, '咒紋空力競速褲', 'epic', 60, '{"def":4,"vit":3,"hp_pct":5}'::jsonb, '魔法師專用褲裙，Lv.60以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+4、VIT+3、HP上限+5%。', TRUE, 64070),
  ('mg_legs_t8', 'mage', 'legs', 8, '咒紋職業選手戰褲', 'epic', 70, '{"def":5,"vit":4,"hp_pct":5}'::jsonb, '魔法師專用褲裙，Lv.70以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+5、VIT+4、HP上限+5%。', TRUE, 64080),
  ('mg_legs_t9', 'mage', 'legs', 9, '咒紋國手戰褲', 'epic', 80, '{"def":6,"vit":4,"hp_pct":6}'::jsonb, '魔法師專用褲裙，Lv.80以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+4、HP上限+6%。', TRUE, 64090),
  ('mg_legs_t10', 'mage', 'legs', 10, '咒紋巔峰競速護甲褲', 'legendary', 90, '{"def":6,"vit":5,"hp_pct":6}'::jsonb, '魔法師專用褲裙，Lv.90以上可裝備，下半身裝備，防具次要防禦來源，提供DEF+6、VIT+5、HP上限+6%。', TRUE, 64100),
  ('mg_boots_t1', 'mage', 'boots', 1, '咒紋帆布運動鞋', 'common', 1, '{"def":1,"agi":1,"dex":1}'::jsonb, '魔法師專用鞋子，Lv.1以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 65010),
  ('mg_boots_t2', 'mage', 'boots', 2, '咒紋慢跑鞋', 'common', 10, '{"def":1,"agi":1,"dex":1}'::jsonb, '魔法師專用鞋子，Lv.10以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+1、DEX+1。', TRUE, 65020),
  ('mg_boots_t3', 'mage', 'boots', 3, '咒紋緩震訓練鞋', 'common', 20, '{"def":1,"agi":2,"dex":2}'::jsonb, '魔法師專用鞋子，Lv.20以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 65030),
  ('mg_boots_t4', 'mage', 'boots', 4, '咒紋透氣競速鞋', 'rare', 30, '{"def":1,"agi":2,"dex":2}'::jsonb, '魔法師專用鞋子，Lv.30以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 65040),
  ('mg_boots_t5', 'mage', 'boots', 5, '咒紋輕量競速鞋', 'rare', 40, '{"def":1,"agi":2,"dex":2}'::jsonb, '魔法師專用鞋子，Lv.40以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+1、AGI+2、DEX+2。', TRUE, 65050),
  ('mg_boots_t6', 'mage', 'boots', 6, '咒紋碳板競速鞋', 'rare', 50, '{"def":2,"agi":3,"dex":3}'::jsonb, '魔法師專用鞋子，Lv.50以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 65060),
  ('mg_boots_t7', 'mage', 'boots', 7, '咒紋空力競速釘鞋', 'epic', 60, '{"def":2,"agi":3,"dex":3}'::jsonb, '魔法師專用鞋子，Lv.60以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+2、AGI+3、DEX+3。', TRUE, 65070),
  ('mg_boots_t8', 'mage', 'boots', 8, '咒紋職業選手戰靴', 'epic', 70, '{"def":3,"agi":3,"dex":3}'::jsonb, '魔法師專用鞋子，Lv.70以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+3、DEX+3。', TRUE, 65080),
  ('mg_boots_t9', 'mage', 'boots', 9, '咒紋國手競速戰靴', 'epic', 80, '{"def":3,"agi":4,"dex":4}'::jsonb, '魔法師專用鞋子，Lv.80以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+4、DEX+4。', TRUE, 65090),
  ('mg_boots_t10', 'mage', 'boots', 10, '咒紋巔峰競速戰靴', 'legendary', 90, '{"def":3,"agi":4,"dex":4}'::jsonb, '魔法師專用鞋子，Lv.90以上可裝備，足部裝備，掌管步伐與落地穩定，提供DEF+3、AGI+4、DEX+4。', TRUE, 65100)
ON CONFLICT (id) DO UPDATE SET
  job_id = EXCLUDED.job_id,
  slot = EXCLUDED.slot,
  tier = EXCLUDED.tier,
  name = EXCLUDED.name,
  rarity = EXCLUDED.rarity,
  level_req = EXCLUDED.level_req,
  profile = EXCLUDED.profile,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

-- <<< ARMOR SEED <<<

-- ---------------------------------------------------------------------------
-- 2) player_equipment：slot 值域由僅 'weapon' 擴充成八格（武器＋五部位防具＋兩格飾品，
--    CONTRACT §1）；item_id 原本 FK 到 rpg_weapons，現在同一欄位視 slot 可能指向 rpg_weapons
--    或 rpg_armor_items，無法用單一 FK 表達，移除 FK 改由應用層依 slot 驗證 item 存在
--    （weapon 查 rpg_weapons，其餘查 rpg_armor_items；查無 item → 視為未裝備，不 500，見
--    internal/rpg/equipment.go）。兩條約束都先 DROP IF EXISTS 再重建/略過，整段可安全重複執行。
-- ---------------------------------------------------------------------------

ALTER TABLE player_equipment DROP CONSTRAINT IF EXISTS player_equipment_item_id_fkey;
ALTER TABLE player_equipment DROP CONSTRAINT IF EXISTS player_equipment_slot_check;
ALTER TABLE player_equipment ADD CONSTRAINT player_equipment_slot_check
  CHECK (slot IN ('weapon','helmet','gloves','armor','legs','boots','accessory1','accessory2'));

INSERT INTO schema_migrations (version) VALUES ('184') ON CONFLICT DO NOTHING;
